import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PublicProfileView } from "@/components/public-profile-view";
import { createServiceClient,isSupabaseConfigured } from "@/lib/supabase-server";
import { publicProfileFromRow } from "@/lib/profile-server";
import { getCurrentAccount } from "@/lib/user-auth";

type Props={params:Promise<{username:string}>};
async function data(username:string,viewerId?:string){if(!isSupabaseConfigured())return null;const client=createServiceClient();const {data:row}=await client.from("profiles").select("*").eq("username",username.toLowerCase()).eq("account_status","active").eq("profile_visibility","public").maybeSingle();if(!row)return null;if(viewerId){const {data:blocked}=await client.from("profile_blocks").select("blocked_id").eq("blocker_id",viewerId).eq("blocked_id",row.id).maybeSingle();if(blocked)return null;}const profile=await publicProfileFromRow(row);if(!profile)return null;const [{data:posts},{data:buddy},{data:listings},{data:events}]=await Promise.all([client.from("community_posts").select("id,body,category,created_at").eq("author_id",row.id).eq("status","active").order("created_at",{ascending:false}).limit(20),client.from("buddy_posts").select("id,activity_type,approximate_location,starts_at,description").eq("owner_id",row.id).eq("status","active").eq("moderation_status","approved").gte("expires_at",new Date().toISOString()).order("starts_at"),client.from("marketplace_listings").select("id,city_id,title,price_mode,price_amount,status,published_at").eq("seller_id",row.id).in("status",["active","reserved","sold"]).order("published_at",{ascending:false}).limit(20),client.from("community_events").select("id,title,starts_at,venue,status").eq("author_id",row.id).eq("status","published").gte("starts_at",new Date().toISOString()).order("starts_at").limit(20)]);return{profile,ownerId:String(row.id),content:{posts:posts||[],buddy:buddy||[],listings:listings||[],events:events||[]}};}
export async function generateMetadata({params}:Props):Promise<Metadata>{const username=decodeURIComponent((await params).username);const value=await data(username);return value?{title:`${value.profile.displayName} (@${value.profile.username})`,description:value.profile.bio||`Veřejný studentský profil ${value.profile.displayName} na StudentHub Brno.`,alternates:{canonical:`/profil/${value.profile.username}`}}:{title:"Profil nenalezen",robots:{index:false,follow:false}};}
export default async function PublicProfilePage({params}:Props){const viewer=await getCurrentAccount();const value=await data(decodeURIComponent((await params).username),viewer?.id);if(!value)notFound();return <PublicProfileView profile={value.profile} content={value.content} own={viewer?.id===value.ownerId}/>;}
