import { expect,test } from "@playwright/test";
import { readFile } from 'node:fs/promises';
import { createCanvas, loadImage } from '@napi-rs/canvas';
async function verifyExport(path:string|null) {
 expect(path).not.toBeNull();const image=await loadImage(await readFile(path!));expect(image.width).toBe(768);expect(image.height).toBe(1024);const canvas=createCanvas(image.width,image.height),ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const pixels=ctx.getImageData(0,0,image.width,image.height).data;let colored=0,black=0;for(let i=0;i<pixels.length;i+=4){if(pixels[i]!==pixels[i+1])colored++;if(pixels[i]<40&&pixels[i+1]<40&&pixels[i+2]<40)black++;}expect(colored).toBeGreaterThan(100);expect(black).toBeGreaterThan(2000);
}
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('studenthub-consent',JSON.stringify({analytics:false,marketing:false}));localStorage.setItem('studenthub-tutorial-state',JSON.stringify({tutorialVersion:3,introConfirmed:true,status:'completed',lastCompletedStep:null}));localStorage.setItem('studenthub-preference-v4',JSON.stringify({version:4,cityId:'brno',universityId:'vut',facultyId:'vut-fekt',completed:true}));});});
test('verzované assety neblokuje městský router',async({request})=>{for(const file of ['lines.png','mask.png','preview.webp','regions.json']){const r=await request.get(`/coloring/v1/desk/${file}`);expect(r.status()).toBe(200);expect(r.headers()['content-type']).toContain(file.endsWith('.json')?'application/json':'image/');}});
test('aktivita → galerie → editor, návrat, relace a starý odkaz',async({page,request})=>{
await page.goto('/brno/odpocinek');await expect(page.locator('.rest-activity')).toHaveCount(1);await expect(page.locator('.coloring-card')).toHaveCount(0);await page.locator('.rest-activity[href$="/omalovanky"]').click();await expect(page).toHaveURL(/\/brno\/odpocinek\/omalovanky$/);await expect(page.locator('.coloring-card')).toHaveCount(8);
 await page.locator('.coloring-card').nth(1).getByRole('link',{name:'Vybarvovat'}).click();await expect(page).toHaveURL(/\/omalovanky\/desk$/);await page.getByRole('button',{name:'Vyplnit vybranou oblast',exact:true}).click();await page.getByRole('button',{name:'Přiblížit',exact:true}).click();await page.locator('.coloring-editor').getByRole('link',{name:'Všechny omalovánky'}).click();await expect(page.locator('.coloring-card').nth(1)).toContainText('Rozpracovaná');await page.getByRole('link',{name:'← Odpočinek',exact:true}).click();await expect(page.locator('.rest-activity[href$="/omalovanky"]')).toContainText('1 rozpracovaná');await page.goBack();await expect(page).toHaveURL(/\/omalovanky$/);
 await page.goto('/brno/odpocinek/omalovanky/desk');await page.reload();await expect(page.locator('.coloring-stage canvas')).toHaveAttribute('style',/scale\(1.25\)/);expect(await page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('studenthub-coloring-v1:guest:desk')!).drawing.colors))).toHaveLength(1);
 if(page.viewportSize()!.width<768){await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));expect(await page.locator('.coloring-stage').evaluate(el=>el.getBoundingClientRect().bottom)).toBeLessThanOrEqual(await page.locator('.bottom-nav').evaluate(el=>el.getBoundingClientRect().top));}
 const old=await request.get('/brno/odpocinek/desk',{maxRedirects:0});expect(old.status()).toBe(308);expect(old.headers().location).toBe('/brno/odpocinek/omalovanky/desk');
});
for(const id of ['botanical','desk','library','cafe','brno','praha','olomouc','ostrava'])test(`kvalita motivu ${id}: barvy, štětec, kapátko, guma, export, reload`,async({page})=>{
 await page.goto(`/brno/odpocinek/omalovanky/${id}`);const canvas=page.locator('.coloring-stage canvas');await expect(canvas).toBeVisible();await page.getByRole('button',{name:'Vyplnit vybranou oblast',exact:true}).click();await page.getByRole('button',{name:'Barva #f97316',exact:true}).click();await page.getByRole('button',{name:'Štětec',exact:true}).click();await canvas.scrollIntoViewIfNeeded();let box=await canvas.boundingBox();const regions=await(await page.request.get(`/coloring/v1/${id}/regions.json`)).json();const spot=regions.find((r:{area:number;x:number;y:number})=>r.area>5000);const sx=spot.x/768*box!.width,sy=spot.y/1024*box!.height;await page.mouse.move(box!.x+sx,box!.y+sy);await page.mouse.down();await page.mouse.move(box!.x+sx+10,box!.y+sy+10,{steps:20});await page.mouse.up();await page.getByRole('button',{name:'Kapátko',exact:true}).click();await canvas.click({position:{x:sx,y:sy}});await expect(page.getByLabel('Vlastní barva',{exact:true})).toHaveValue('#f97316');
 await page.getByRole('button',{name:'Guma (tahy štětce)',exact:true}).click();box=await canvas.boundingBox();await page.mouse.move(box!.x+box!.width*.5,box!.y+box!.height*.5);await page.mouse.down();await page.mouse.move(box!.x+box!.width*.54,box!.y+box!.height*.54,{steps:4});await page.mouse.up();await page.getByRole('button',{name:'Krok zpět',exact:true}).click();await page.getByRole('button',{name:'Krok vpřed',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Exportovat PNG',exact:true}).click();expect((await download).suggestedFilename()).toBe(`studenthub-${id}.png`);await page.reload();await expect(canvas).toBeVisible();await expect.poll(()=>canvas.evaluate(el=>{const c=el as HTMLCanvasElement,d=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data;let n=0;for(let i=0;i<d.length;i+=4)if(d[i]!==d[i+1])n++;return n;})).toBeGreaterThan(100);
});
test('posun plátna funguje také klávesnicí',async({page})=>{await page.goto('/brno/odpocinek/omalovanky/desk');const canvas=page.locator('.coloring-stage canvas');await expect(canvas).toBeVisible();await expect(page.getByRole('button',{name:'Vyplnit vybranou oblast',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Posouvat plátno',exact:true}).click();await canvas.focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowDown');await expect(canvas).toHaveAttribute('style',/translate\(20px, 20px\)/);await page.keyboard.press('Escape');await expect(canvas).toHaveAttribute('style',/translate\(0px, 0px\)/);});
test('skutečné pixely, vyplnění, lokální uložení, undo, export a reset',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/brno/odpocinek/omalovanky');await expect(page.getByRole('heading',{name:'Antistresové omalovánky',exact:true})).toBeVisible();await expect(page.locator('.coloring-card')).toHaveCount(8);await page.locator('.coloring-card').nth(1).getByRole('link',{name:'Vybarvovat'}).click();const canvas=page.locator('.coloring-stage canvas');await expect(canvas).toBeVisible();
 const pixels=()=>canvas.evaluate(el=>{const c=el as HTMLCanvasElement,d=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data;let black=0,colors=0;for(let i=0;i<d.length;i+=4){if(d[i]<40&&d[i+1]<40&&d[i+2]<40)black++;if(d[i]!==d[i+1]||d[i+1]!==d[i+2])colors++;}return{black,colors,w:c.width,h:c.height};});
 await expect.poll(async()=> (await pixels()).black).toBeGreaterThan(2000);const regions=await (await page.request.get('/coloring/v1/desk/regions.json')).json();const target=regions.find((r:{area:number})=>r.area>5000);const box=await canvas.boundingBox();expect(box).not.toBeNull();await canvas.click({position:{x:target.x/768*box!.width,y:target.y/1024*box!.height}});await expect.poll(async()=> (await pixels()).colors).toBeGreaterThan(1000);
 await page.getByRole('button',{name:'Krok zpět',exact:true}).click();await expect.poll(async()=> (await pixels()).colors).toBe(0);await page.getByRole('button',{name:'Krok vpřed',exact:true}).click();await expect.poll(async()=> (await pixels()).colors).toBeGreaterThan(1000);await page.reload();await expect(canvas).toBeVisible();await expect.poll(async()=> (await pixels()).colors).toBeGreaterThan(1000);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Exportovat PNG',exact:true}).click();const exported=await download;expect(exported.suggestedFilename()).toBe('studenthub-desk.png');await verifyExport(await exported.path());
 await page.getByRole('button',{name:'Reset omalovánky',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Vymazat tuto omalovánku?'});await expect(dialog).toBeVisible();await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();expect((await pixels()).colors).toBeGreaterThan(1000);await page.getByRole('button',{name:'Reset omalovánky',exact:true}).click();await dialog.getByRole('button',{name:'Vymazat',exact:true}).click();await expect.poll(async()=> (await pixels()).colors).toBe(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);expect(errors).toEqual([]);await page.screenshot({path:`artifacts/coloring/${info.project.name}-light.png`,fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.screenshot({path:`artifacts/coloring/${info.project.name}-dark.png`,fullPage:true});
});
test('štětec, zoom, posun, offline kreslení a města sdílejí postup',async({page,context})=>{
 await page.goto('/brno/odpocinek/omalovanky/desk');const canvas=page.locator('.coloring-stage canvas');await expect(canvas).toBeVisible();await page.getByRole('button',{name:'Štětec',exact:true}).click();await canvas.scrollIntoViewIfNeeded();const box=await canvas.boundingBox();await page.mouse.move(box!.x+box!.width*.4,box!.y+box!.height*.4);await page.mouse.down();await page.mouse.move(box!.x+box!.width*.6,box!.y+box!.height*.6,{steps:8});await page.mouse.up();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('studenthub-coloring-v1:guest:desk')||'{}').drawing?.strokes.length)).toBe(1);
 await page.getByRole('button',{name:'Přiblížit',exact:true}).click();await expect(canvas).toHaveAttribute('style',/scale\(1.25\)/);await page.getByRole('button',{name:'Posouvat plátno',exact:true}).click();await canvas.scrollIntoViewIfNeeded();const moved=await canvas.boundingBox();await page.mouse.move(moved!.x+moved!.width/2,moved!.y+moved!.height/2);await page.mouse.down();await page.mouse.move(moved!.x+moved!.width/2+20,moved!.y+moved!.height/2+20,{steps:4});await page.mouse.up();await expect(canvas).toHaveAttribute('style',/translate\(20px,20px\)|translate\(20px, 20px\)/);
 await context.setOffline(true);await page.getByRole('button',{name:'Vyplnit vybranou oblast',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Uloženo na tomto zařízení'})).toBeVisible();await context.setOffline(false);await page.goto('/praha/odpocinek/omalovanky/desk');await expect(canvas).toBeVisible();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('studenthub-coloring-v1:guest:desk')||'{}').drawing?.strokes.length)).toBe(1);
});
test('skutečné dotykové gesto a tlak stylusu přes Pointer Events',async({page,context})=>{
 await page.goto('/brno/odpocinek/omalovanky/desk');const canvas=page.locator('.coloring-stage canvas');await expect(canvas).toBeVisible();await canvas.scrollIntoViewIfNeeded();const box=await canvas.boundingBox();const x=box!.x+box!.width/2,y=box!.y+box!.height/2,cdp=await context.newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:2});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-40,y,id:1},{x:x+40,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-60,y,id:1},{x:x+60,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect(canvas).toHaveAttribute('style',/scale\(1.5\)/);expect(await page.evaluate(()=>localStorage.getItem('studenthub-coloring-v1:guest:desk'))).toBeNull();
 await page.getByRole('button',{name:'Štětec',exact:true}).click();await canvas.scrollIntoViewIfNeeded();const b=await canvas.boundingBox(),px=b!.x+b!.width/2,py=b!.y+b!.height/2;
 await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x:px,y:py,button:'left',buttons:1,pointerType:'pen',force:.8});await cdp.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:px+15,y:py+15,buttons:1,pointerType:'pen',force:.8});await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:px+15,y:py+15,button:'left',buttons:0,pointerType:'pen'});
 await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('studenthub-coloring-v1:guest:desk')||'{}').drawing?.strokes.length)).toBe(1);const pressures=await page.evaluate(()=>JSON.parse(localStorage.getItem('studenthub-coloring-v1:guest:desk')!).drawing.strokes[0].points.map((p:number[])=>p[2]));expect(pressures.some((v:number)=>Math.abs(v-.8)<.01)).toBe(true);
 await page.getByRole('button',{name:'Celá obrazovka',exact:true}).click();await expect(page.getByRole('dialog',{name:'Můj studijní kout',exact:true})).toBeVisible();await page.getByRole('button',{name:'Reset omalovánky',exact:true}).click();await expect(page.locator('[aria-modal=true]')).toHaveCount(1);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Ukončit celou obrazovku',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
});
