import { expect,test } from "@playwright/test";
import { dotsGames } from "../../lib/connect-dots";
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('studenthub-consent',JSON.stringify({analytics:false,marketing:false}));localStorage.setItem('studenthub-tutorial-state',JSON.stringify({tutorialVersion:3,introConfirmed:true,status:'completed',lastCompletedStep:null}));localStorage.setItem('studenthub-preference-v4',JSON.stringify({version:4,cityId:'brno',universityId:'vut',facultyId:'vut-fekt',completed:true}));});});
test('dvě aktivity, galerie, správné body, historie, reload, dokončení a omalovánka',async({page,context},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const capture=async(name:string)=>{expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.screenshot({path:`artifacts/dots/${info.project.name}-${name}-${theme}.png`,fullPage:true});}};
 await page.goto('/brno/odpocinek');await expect(page.locator('.rest-activity')).toHaveCount(2);await capture('activities');await page.locator('a.rest-activity[href$="spojovani-bodu"]').click();await expect(page.locator('.dots-card')).toHaveCount(6);await capture('gallery');await page.locator('.dots-card').nth(1).getByRole('link',{name:'Začít',exact:true}).click();await expect(page.getByRole('button',{name:'Bod 1',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Bod 3',exact:true}).click();await expect(page.locator('.dots-hint')).toContainText('Pokračujte bodem 1');expect(await page.evaluate(()=>localStorage.getItem('studenthub-dots-v1:guest:desk'))).toBeNull();
 for(let i=1;i<=3;i++)await page.getByRole('button',{name:`Bod ${i}`,exact:true}).click();await expect(page.locator('.dots-hint')).toContainText('bod 4');await capture('started');
 await page.getByRole('button',{name:'Krok zpět',exact:true}).click();await expect(page.locator('.dots-hint')).toContainText('bod 3');await page.getByRole('button',{name:'Krok vpřed',exact:true}).click();await expect(page.locator('.dots-hint')).toContainText('bod 4');
 await page.reload();await expect(page.locator('.dots-hint')).toContainText('bod 4');await context.setOffline(true);await page.getByRole('button',{name:'Bod 4',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Uloženo na tomto zařízení'})).toBeVisible();await context.setOffline(false);
 for(let i=5;i<=6;i++)await page.getByRole('button',{name:`Bod ${i}`,exact:true}).click();await expect(page.getByRole('heading',{name:'Dokončeno',exact:true})).toBeVisible();await expect(page.locator('.dots-reveal')).toBeVisible();await capture('complete');
 await page.getByRole('link',{name:'Vybarvit tento obrázek',exact:true}).click();await expect(page).toHaveURL(/\/omalovanky\/desk$/);await expect(page.locator('.coloring-stage canvas')).toBeVisible();await page.goBack();await expect(page.getByRole('heading',{name:'Dokončeno',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Dokončeno',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Všechny obrázky',exact:true}).click();await page.getByRole('button',{name:'Dokončené',exact:true}).click();await expect(page.locator('.dots-card')).toHaveCount(1);await page.getByRole('button',{name:'Rozpracované',exact:true}).click();await expect(page.locator('.dots-card')).toHaveCount(0);await page.getByRole('link',{name:'← Odpočinek',exact:true}).click();await expect(page.locator('.rest-activity')).toHaveCount(2);expect(errors).toEqual([]);
});
for(const game of dotsGames)test(`motiv ${game.id}: všechna propojení, dotyková plocha, hluboký odkaz a dokončená kresba`,async({page},info)=>{
 await page.goto(`/brno/odpocinek/spojovani-bodu/${game.slug}`);await page.reload();await expect(page.getByRole('button',{name:'Bod 1',exact:true})).toBeVisible();
 const points=await page.locator('.dots-point').evaluateAll(elements=>elements.map(e=>{const b=e.getBoundingClientRect();return{x:b.x+b.width/2,y:b.y+b.height/2,width:b.width,height:b.height};}));for(const p of points){expect(p.width).toBeGreaterThanOrEqual(43);expect(p.height).toBeGreaterThanOrEqual(43);}for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++)expect(Math.hypot(points[i].x-points[j].x,points[i].y-points[j].y)).toBeGreaterThan(22);
 for(let i=1;i<=game.points.length;i++)await page.getByRole('button',{name:`Bod ${i}`,exact:true}).click();await expect(page.locator('.dots-reveal')).toBeVisible();await expect(page.getByRole('heading',{name:'Dokončeno',exact:true})).toBeVisible();await page.screenshot({path:`artifacts/dots/${info.project.name}-${game.id}-finished.png`,fullPage:true});
 const line=await page.locator('[data-testid=dots-line]').getAttribute('points');expect(line?.split(' ')).toHaveLength(game.points.length+1);expect(await page.evaluate(id=>JSON.parse(localStorage.getItem(`studenthub-dots-v1:guest:${id}`)!).drawing.cursor,game.id)).toBe(game.points.length);
 await page.goto(`/praha/odpocinek/spojovani-bodu/${game.slug}`);await expect(page.getByRole('heading',{name:'Dokončeno',exact:true})).toBeVisible();
});
test('klávesnice, tažení, zoom, modal, reset a omezený pohyb',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/brno/odpocinek/spojovani-bodu/desk');const canvas=page.locator('.dots-stage svg');await expect(page.getByRole('button',{name:'Bod 1',exact:true})).toBeVisible();await canvas.focus();await page.keyboard.press('Enter');await expect(page.locator('.dots-hint')).toContainText('bod 2');
 const a=await page.getByRole('button',{name:'Bod 1',exact:true}).boundingBox(),b=await page.getByRole('button',{name:'Bod 2',exact:true}).boundingBox();await page.mouse.move(a!.x+a!.width/2,a!.y+a!.height/2);await page.mouse.down();await page.mouse.move(b!.x+b!.width/2,b!.y+b!.height/2,{steps:10});await page.mouse.up();await expect(page.locator('.dots-hint')).toContainText('bod 3');
 await page.getByRole('button',{name:'Přiblížit',exact:true}).click();await expect(canvas).toHaveAttribute('style',/scale\(1.25\)/);await page.getByRole('button',{name:'Posouvat plátno',exact:true}).click();await canvas.focus();await page.keyboard.press('ArrowRight');await expect(canvas).toHaveAttribute('style',/translate\(20px/);await page.getByRole('button',{name:'Celá obrazovka',exact:true}).click();await expect(page.locator('[aria-modal=true]')).toHaveCount(1);await page.keyboard.press('Escape');await expect(page.locator('[aria-modal=true]')).toHaveCount(0);
 await page.getByRole('button',{name:'Začít znovu',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Začít tento obrázek znovu?'});await expect(dialog).toBeVisible();await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await page.getByRole('button',{name:'Začít znovu',exact:true}).click();await dialog.getByRole('button',{name:'Začít znovu',exact:true}).click();await expect(page.locator('.dots-hint')).toContainText('bod 1');
});
