import { expect,test } from "@playwright/test";

test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem("studenthub-consent",JSON.stringify({analytics:false,marketing:false}));localStorage.setItem("studenthub-preference-v4",JSON.stringify({version:4,cityId:"brno",universityId:"",facultyId:"",studyYear:null,studyYearCycleStart:null,completed:true}));localStorage.setItem("studenthub-tutorial-version","studenthub-marketplace-v4")})});

async function openFilters(page:import("@playwright/test").Page){const button=page.locator('button[aria-controls="places-filters"]');if(!(await button.isVisible().catch(()=>false)))return;await button.click();if(await button.getAttribute("aria-expanded")!=="true"){await page.waitForTimeout(250);await button.click()}await expect(button).toHaveAttribute("aria-expanded","true")}

test("katalog nabízí všech 12 kategorií a komunitní filtry",async({page})=>{const response=await page.goto("/brno/mista");expect(response?.headers()["content-security-policy"]).toContain("https://tile.openstreetmap.org");await openFilters(page);const filters=page.locator("#places-filters");await expect(filters).toBeVisible();const category=filters.locator("select").first();await expect(category.locator("option")).toHaveText(["Všechny","Restaurace","Kavárna","Hospoda a bar","Bistro a rychlé občerstvení","Menza","Knihovna","Studovna","Coworking","Veřejné toalety","Sport a pohyb","Studentské služby","Ostatní"]);await expect(filters.getByLabel("Původ záznamu")).toBeVisible();await expect(filters.getByText("Aktuálně otevřeno",{exact:true})).toBeVisible();await expect(filters.getByText("Wi‑Fi",{exact:true})).toBeVisible();});

test("kolečko mění mapu bez posunu celé stránky",async({page},testInfo)=>{test.skip(testInfo.project.name==="mobile-390","Mobil používá dotykové pinch-zoom gesto, ne kolečko myši.");await page.goto("/brno/mista");const map=page.locator(".leaflet-host");await expect(map).toBeVisible();await map.scrollIntoViewIfNeeded();const box=await map.boundingBox();expect(box).toBeTruthy();const before=await page.evaluate(()=>({scroll:window.scrollY,tiles:[...document.querySelectorAll<HTMLImageElement>(".leaflet-tile")].map((image)=>image.src).sort().join("|")}));if(box){await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.wheel(0,-620)}await expect.poll(async()=>page.evaluate(()=>[...document.querySelectorAll<HTMLImageElement>(".leaflet-tile")].map((image)=>image.src).sort().join("|"))).not.toBe(before.tiles);const afterScroll=await page.evaluate(()=>window.scrollY);expect(Math.abs(afterScroll-before.scroll)).toBeLessThanOrEqual(2);});

test("ověřený profil vyplní návrh, potvrdí mapu a odešle ho ke schválení",async({page})=>{await page.route("**/api/auth/me",(route)=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({user:{id:"test",verified:true},profile:{complete:true}})}));let multipart="";await page.route("**/api/place-suggestions",async(route)=>{if(route.request().method()!=="POST")return route.continue();multipart=(await route.request().postDataBuffer())?.toString("utf8")||"";return route.fulfill({status:201,contentType:"application/json",body:JSON.stringify({id:"75111111-1111-4111-8111-111111111111",status:"pending",message:"Návrh je bezpečně uložený."})})});await page.goto("/brno/mista",{waitUntil:"domcontentloaded"});const suggest=page.getByTestId("suggest-place");await expect(suggest).toBeVisible();await suggest.click();const dialog=page.getByRole("dialog",{name:"Navrhnout nové místo"});await expect(dialog).toBeVisible();await expect(page.locator('[aria-modal="true"]')).toHaveCount(1);await dialog.getByLabel("Název *").fill("Nová studentská studovna");await dialog.getByLabel("Kategorie *").selectOption("study_room");await dialog.getByLabel("Bezpečný veřejný zdroj *").fill("https://example.com/studovna");await dialog.getByLabel("Popis *").fill("Veřejná studovna s pravidelnou otevírací dobou a klidným zázemím.");await dialog.getByLabel("Proč je místo užitečné studentům? *").fill("Nabízí klidné stoly blízko centra.");await dialog.getByLabel("Potvrzená veřejná adresa *").fill("Veveří 1, Brno");await dialog.getByLabel("Potvrzuji, že značka leží přesně u veřejného místa. *").check();await dialog.getByLabel(/Potvrzuji pravdivost údajů/).check();await dialog.getByLabel(/Potvrzuji, že mám právo zveřejnit/).check();await dialog.getByRole("button",{name:"Odeslat ke schválení"}).click();await expect(dialog.getByRole("heading",{name:"Návrh je ve frontě"})).toBeVisible();expect(multipart).toContain("Nová studentská studovna");expect(multipart).toContain("study_room");expect(multipart).toContain("locationConfirmed");});
