import { expect, test } from "@playwright/test";

async function dismissOverlays(page: import("@playwright/test").Page) {
  const consent = page.getByTestId("cookie-consent"); if (await consent.isVisible()) await consent.getByRole("button", { name: "Pouze nezbytné" }).click();
  const picker = page.getByTestId("first-run-picker"); if (await picker.isVisible()) await picker.getByRole("button", { name: "Pokračovat bez výběru školy pro celé město Brno" }).click();
}
test.beforeEach(async ({ page }) => { await page.goto("/"); await dismissOverlays(page); });

test("načte použitelný dashboard bez veřejných demo dat", async ({ page }) => { await expect(page.getByRole("heading", { name: "StudentHub Brno" })).toBeVisible(); await expect(page.locator("#hlavni-obsah").getByRole("link", { name: "Potřebuji technickou pomoc", exact: true })).toBeVisible(); await expect(page.getByText("DEMO DATA")).toHaveCount(0); await expect(page.getByText(/Nezávislý projekt\. Není oficiálně spojený/)).toHaveCount(1); await expect(page.locator('link[rel="canonical"]')).toHaveAttribute("href", /\/brno$/); });

test("filtruje ověřené akademické události", async ({ page }) => { await page.goto("/brno/kalendar"); await page.getByLabel("Kategorie").selectOption("Zkouškové období"); await expect(page.getByText("2 ověřených událostí")).toBeVisible(); await expect(page.getByRole("heading", { name: /Zkouškové období zimního semestru FIT VUT/ })).toBeVisible(); await expect(page.getByRole("link", { name: /Časový plán FIT VUT/ })).toHaveAttribute("href", /^https:\/\//); });

test("filtruje místa a nabídky mají poctivý prázdný stav", async ({ page }) => { await page.goto("/brno/mista"); await page.getByLabel("Kategorie").selectOption("Knihovna"); await expect(page.getByText("Ústřední knihovna VUT")).toBeVisible(); await expect(page.getByText("DEMO")).toHaveCount(0); await page.goto("/brno/nabidky"); await expect(page.getByRole("heading", { name: "Zatím nemáme ověřené nabídky" })).toBeVisible(); await expect(page.getByRole("link", { name: "oficiální katalog ISIC" })).toHaveAttribute("href", "https://www.isic.cz/slevy"); });

test("migruje starou preferenci a resetuje ji na Brno", async ({ page }) => { await page.evaluate(() => { localStorage.removeItem("studenthub-preference-v2"); localStorage.setItem("studenthub-preference-v1", JSON.stringify({ universityId: "muni", facultyId: "muni-fi", completed: true })); }); await page.reload(); await dismissOverlays(page); await expect(page.getByRole("heading", { name: "Přehled pro FI" })).toBeVisible(); const migrated = await page.evaluate(() => localStorage.getItem("studenthub-preference-v2")); expect(migrated).toContain('"version":2'); expect(migrated).toContain('"cityId":"brno"'); await page.goto("/nastaveni"); await page.getByRole("button", { name: "Resetovat město a školu" }).click(); await expect(page.getByRole("button", { name: "Výběr byl resetován" })).toBeVisible(); expect(await page.evaluate(() => localStorage.getItem("studenthub-preference-v2"))).toContain('"completed":false'); });

test("výběr fakulty funguje pro všech pět univerzit a kontext se mění bez reloadu", async ({ page }, testInfo) => {
  const samples = [["muni", "muni-fi", "MUNI · FI"], ["vut", "vut-fit", "VUT · FIT"], ["mendelu", "mendelu-pef", "MENDELU · PEF"], ["vetuni", "vetuni-fvl", "VETUNI · FVL"], ["jamu", "jamu-hf", "JAMU · HF"]] as const;
  for (const [university, faculty, context] of samples) {
    await page.goto("/nastaveni"); await page.getByLabel("Moje škola").selectOption(university); const facultySelect = page.getByLabel("Moje fakulta"); await expect(facultySelect.locator(`option[value="${faculty}"]`)).toHaveCount(1); await facultySelect.selectOption(faculty); await page.getByRole("button", { name: "Uložit výběr" }).click();
    if (testInfo.project.name !== "desktop-1440") await page.getByRole("button", { name: "Otevřít nabídku" }).click();
    await expect(page.getByTestId("selected-study-context")).toContainText(context);
    if (testInfo.project.name !== "desktop-1440") await page.getByRole("dialog", { name: "Postranní panel" }).getByRole("button", { name: "Zavřít nabídku" }).click();
    await page.reload(); await dismissOverlays(page); expect(await page.evaluate(() => localStorage.getItem("studenthub-preference-v2"))).toContain(`"facultyId":"${faculty}"`);
    await page.goto(`/brno/kalendar?university=${university}&faculty=${faculty}`); await expect(page).toHaveURL(new RegExp(`university=${university}.*faculty=${faculty}`)); await expect(page.getByLabel("Fakulta", { exact: true })).toHaveValue(faculty);
  }
  await page.getByRole("group", { name: "Barevný režim" }).getByRole("button", { name: "Tmavý režim" }).click(); await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
});

test("kalendář opraví neplatnou kombinaci URL a neukáže jinou fakultu", async ({ page }) => { await page.goto("/brno/kalendar?university=muni&faculty=vut-fit"); await expect(page).toHaveURL(/university=muni/); await expect(page).not.toHaveURL(/faculty=vut-fit/); await expect(page.getByRole("heading", { name: /FIT VUT/ })).toHaveCount(0); await page.getByRole("button", { name: "Resetovat filtry" }).click(); await expect(page).toHaveURL(/\/brno\/kalendar$/); });

test("explicitní MUNI FI scope má přednost a dashboard nepropustí VUT", async ({ page }) => { await page.evaluate(() => localStorage.setItem("studenthub-preference-v2", JSON.stringify({ version: 2, cityId: "brno", universityId: "vut", facultyId: "vut-fit", campusId: null, completed: true }))); await page.goto("/brno?university=muni&faculty=muni-fi"); await expect(page.getByRole("heading", { name: "Přehled pro FI" })).toBeVisible(); await expect(page.getByText(/FIT VUT|FSI VUT/)).toHaveCount(0); await expect(page.getByRole("heading", { name: "Začátek podzimního semestru 2026", exact: true }).first()).toBeVisible(); });

test("uložená preference MUNI FI filtruje KPI, termíny i místa bez URL parametrů", async ({ page }) => { await page.evaluate(() => localStorage.setItem("studenthub-preference-v2", JSON.stringify({ version: 2, cityId: "brno", universityId: "muni", facultyId: "muni-fi", campusId: null, completed: true }))); await page.goto("/brno"); await expect(page.getByRole("heading", { name: "Přehled pro FI" })).toBeVisible(); await expect(page.getByText(/FIT VUT|FSI VUT/)).toHaveCount(0); await expect(page.getByText("Další zkouškové období")).toHaveCount(0); await expect(page.getByRole("heading", { name: "Menza Vinařská MUNI", exact: true })).toBeVisible(); await expect(page.getByRole("heading", { name: "Ústřední knihovna VUT", exact: true })).toHaveCount(0); });

test("URL filtr míst respektuje MUNI Bohunice", async ({ page }) => { await page.goto("/brno/mista?university=muni&campus=Bohunice"); await expect(page.getByText("Knihovna univerzitního kampusu MUNI")).toBeVisible(); await expect(page.getByText("Ústřední knihovna VUT")).toHaveCount(0); await expect(page.getByLabel("Univerzita / nejbližší kampus")).toHaveValue("muni"); });

test("exportuje český celodenní rozsah bez posunu data", async ({ page, request }) => {
  await page.goto("/brno/kalendar?university=vut&faculty=vut-fit");
  const card = page.locator("article.event-card").filter({ hasText: "Výuka v zimním semestru FIT VUT" }); await expect(card).toBeVisible();
  const icsHref = await card.getByRole("link", { name: "Stáhnout .ics" }).getAttribute("href"); expect(icsHref).toBeTruthy();
  const response = await request.get(icsHref!); expect(response.status()).toBe(200); const body = await response.text();
  expect(body).toContain("DTSTART;VALUE=DATE:20260914"); expect(body).toContain("DTEND;VALUE=DATE:20261212");
  const googleHref = await card.getByRole("link", { name: "Google Calendar" }).getAttribute("href"); expect(new URL(googleHref!).searchParams.get("dates")).toBe("20260914/20261212");
  const bulk = await request.get("/api/calendar/all.ics?city=brno&university=vut&faculty=vut-fit&q=Výuka"); expect(bulk.status()).toBe(200); const bulkBody = await bulk.text(); expect(bulkBody).toContain("DTSTART;VALUE=DATE:20260914"); expect(bulkBody).toContain("DTEND;VALUE=DATE:20261212"); expect(bulkBody).not.toContain("Zkouškové období zimního semestru FIT VUT");
});

test("formulář spolku odešle přesný scope VUT + FEKT", async ({ page }, testInfo) => { test.skip(testInfo.project.name !== "desktop-1440"); let payload: Record<string, unknown> | undefined; await page.route("**/api/submissions", async (route) => { payload = route.request().postDataJSON(); await route.fulfill({ status: 201, contentType: "application/json", body: JSON.stringify({ message: "Návrh byl uložen." }) }); }); await page.goto("/navrhnout-obsah"); await page.getByLabel("Název spolku / týmu *").fill("FEKT studentský tým"); await page.getByLabel("Univerzita *").selectOption("vut"); await page.getByLabel("Fakulta", { exact: true }).selectOption("vut-fekt"); await page.getByLabel("Kontaktní e-mail *").fill("spolek@example.cz"); await page.getByLabel("Název obsahu *").fill("Veřejná technická přednáška"); await page.getByLabel("Popis a důvod zveřejnění *").fill("Veřejná studentská přednáška s ověřitelným programem a kontaktem na pořadatele."); await page.getByText(/Potvrzuji, že mohu obsah zaslat/).click(); await page.getByRole("button", { name: "Odeslat ke schválení" }).click(); await expect(page.getByRole("heading", { name: "Návrh čeká na schválení" })).toBeVisible(); expect(payload).toMatchObject({ universityId: "vut", facultyId: "vut-fekt" }); });

test("všechny tři formuláře odmítnou nevalidní JSON na serveru", async ({ request }, testInfo) => { test.skip(testInfo.project.name !== "desktop-1440"); for (const endpoint of ["/api/service-requests", "/api/jobs", "/api/submissions"]) { const response = await request.post(endpoint, { data: { company: "spam" } }); expect(response.status(), endpoint).toBe(422); } });

test("staré URL přesměrují a školní stránky uvádějí nezávislost", async ({ page }) => { await page.goto("/kalendar"); await expect(page).toHaveURL(/\/brno\/kalendar$/); for (const school of ["muni", "vut", "mendelu"]) { await page.goto(`/${school}`); await expect(page).toHaveURL(new RegExp(`/brno/skoly/${school}$`)); await expect(page.getByText(/Nezávislý projekt:/)).toBeVisible(); await expect(page.getByText(/nenahrazuje školní informační systém/)).toBeVisible(); } });

test("validuje a uloží poptávku technické pomoci", async ({ page }, testInfo) => { test.skip(testInfo.project.name !== "desktop-1440"); await page.goto("/pomoc"); await page.getByRole("button", { name: "Odeslat poptávku" }).click(); await expect(page.getByText("Uveďte prosím jméno.")).toBeVisible(); await page.getByLabel("Jméno *").fill("Testovací Student"); await page.getByLabel("E-mail").fill("student@example.cz"); await page.getByLabel("Popis problému *").fill("Notebook se při startu vypíná a potřebuji bezpečně zkontrolovat hardware."); await page.getByLabel("Preferovaný termín *").fill("2026-08-10"); await page.getByText(/Souhlasím se zpracováním uvedených údajů/).click(); await page.getByRole("button", { name: "Odeslat poptávku" }).click(); await expect(page.getByTestId("request-success")).toBeVisible(); });

test("chrání administraci bez přihlášení", async ({ page }) => { await page.goto("/admin"); await expect(page).toHaveURL(/\/admin\/prihlaseni/); await expect(page.getByRole("heading", { name: "Administrace" })).toBeVisible(); await expect(page.locator('input[name="email"]')).toHaveValue(""); });

test("cookie souhlas je opt-in a lze jej změnit", async ({ page }) => { await page.evaluate(() => localStorage.clear()); await page.reload(); const dialog = page.getByTestId("cookie-consent"); await expect(dialog).toBeVisible(); await dialog.getByRole("button", { name: "Pouze nezbytné" }).click(); expect(await page.evaluate(() => localStorage.getItem("studenthub-consent"))).toContain('"analytics":false'); const picker = page.getByTestId("first-run-picker"); await picker.getByRole("button", { name: "Pokračovat bez výběru školy pro celé město Brno" }).click(); await page.getByRole("button", { name: "Nastavení cookies" }).click(); await expect(page.getByText("Analytické")).toBeVisible(); });

test("cookies a onboarding nikdy nevytvoří dva modály současně", async ({ page }) => { await page.evaluate(() => localStorage.clear()); await page.reload(); const modals = page.locator('[role="dialog"][aria-modal="true"]'); await expect(modals).toHaveCount(1); await expect(page.getByTestId("cookie-consent")).toBeVisible(); await expect(page.getByRole("button", { name: "Pouze nezbytné" })).toBeFocused(); expect(await page.evaluate(() => document.querySelector(".app-shell")?.hasAttribute("inert"))).toBe(true); await page.keyboard.press("Escape"); await expect(page.getByTestId("first-run-picker")).toBeVisible(); await expect(modals).toHaveCount(1); await expect(page.getByRole("button", { name: "Zavřít výběr školy" })).toBeFocused(); await page.keyboard.press("Escape"); await expect(modals).toHaveCount(0); });

test("modal brigády a mobilní menu drží focus a podporují Escape", async ({ page }, testInfo) => { await page.goto("/brno/brigady"); const proposal = page.getByRole("button", { name: "Navrhnout brigádu" }); await proposal.click(); await expect(page.getByRole("dialog", { name: "Navrhnout brigádu" })).toBeVisible(); await expect(page.getByRole("button", { name: "Zavřít formulář" })).toBeFocused(); await page.keyboard.press("Escape"); await expect(proposal).toBeFocused(); if (testInfo.project.name !== "desktop-1440") { const menu = page.getByRole("button", { name: "Otevřít nabídku" }); await menu.click(); const menuDialog = page.getByRole("dialog", { name: "Postranní panel" }); await expect(menuDialog).toBeVisible(); await expect(menuDialog.getByRole("button", { name: "Zavřít nabídku" })).toBeFocused(); await page.keyboard.press("Escape"); await expect(menu).toBeFocused(); } });

test("motiv podporuje systém, světlo a tmu s perzistencí", async ({ page }) => { const group = page.getByRole("group", { name: "Barevný režim" }); await group.getByRole("button", { name: "Tmavý režim" }).click(); await expect(page.locator("html")).toHaveAttribute("data-theme", "dark"); await page.reload(); await dismissOverlays(page); await expect(group.getByRole("button", { name: "Tmavý režim" })).toHaveAttribute("aria-pressed", "true"); await group.getByRole("button", { name: "Podle zařízení" }).click(); expect(await page.evaluate(() => localStorage.getItem("studenthub-theme"))).toBe("system"); });

test("navigace a layout nepřetékají na všech breakpointech", async ({ page }, testInfo) => { const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth); expect(overflow).toBeLessThanOrEqual(1); if (testInfo.project.name === "desktop-1440") await expect(page.getByRole("navigation", { name: "Hlavní navigace" })).toBeVisible(); else { const navigation = page.getByRole("navigation", { name: "Mobilní navigace" }); await expect(navigation).toBeVisible(); await navigation.getByRole("link", { name: "Místa", exact: true }).click(); await expect(page).toHaveURL(/\/brno\/mista/); } });

test("přihlášená administrace používá stejná data, nepřetéká a lze se odhlásit", async ({ page }) => { await page.goto("/admin/prihlaseni"); await page.getByLabel("E-mail").fill("audit@example.cz"); await page.getByLabel("Heslo").fill("local-test-password-2026"); await page.getByRole("button", { name: "Přihlásit se" }).click(); await page.waitForURL("**/admin"); await expect(page.getByText("Lokální ověřený fallback.")).toBeVisible(); await expect(page.getByText("27 zdrojů")).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1); await page.getByRole("button", { name: "Odhlásit" }).click(); await expect(page).toHaveURL(/\/admin\/prihlaseni/); });

test("veřejný dashboard nemá interní síťové ani konzolové chyby a uloží auditní screenshot", async ({ page }, testInfo) => { const consoleErrors: string[] = []; const failedInternal: string[] = []; page.on("console", (message) => { if (message.type() === "error") consoleErrors.push(message.text()); }); page.on("requestfailed", (request) => { const reason = request.failure()?.errorText || "neznámá chyba"; if (request.url().startsWith(page.url().split("/brno")[0]) && reason !== "net::ERR_ABORTED") failedInternal.push(`${request.method()} ${request.url()} · ${reason}`); }); await page.goto("/brno"); await page.getByRole("heading", { name: /StudentHub Brno|Přehled pro/ }).waitFor(); expect(consoleErrors).toEqual([]); expect(failedInternal).toEqual([]); await page.screenshot({ path: `artifacts/audit-${testInfo.project.name}.png`, fullPage: true }); });

test("neaktivní nebo neznámé město není veřejné", async ({ page }) => { const response = await page.goto("/praha"); expect(response?.status()).toBe(404); await expect(page.getByRole("heading", { name: "Tady nic není" })).toBeVisible(); });
