import { NextResponse } from "next/server";
import { defaultCitySlug } from "@/lib/cities";
import { getPublishedCity } from "@/lib/city-data";
import { insertRecord } from "@/lib/data-store";
import { allowRequest, requestFingerprint } from "@/lib/rate-limit";
import { pageViewSchema } from "@/lib/schemas";
import { createHash } from "node:crypto";

function deviceType(userAgent: string) { if (/bot|crawler|spider|headless|preview/i.test(userAgent)) return "bot"; if (/ipad|tablet/i.test(userAgent)) return "tablet"; if (/mobile|android|iphone/i.test(userAgent)) return "mobile"; return userAgent ? "desktop" : "other"; }
export async function POST(request: Request) { if (!/(?:^|;\s*)sh_analytics_consent=1(?:;|$)/.test(request.headers.get("cookie") || "")) return new NextResponse(null, { status: 204 }); const fingerprint = requestFingerprint(request); if (!allowRequest(`view:${fingerprint}`, 120, 60 * 60 * 1000)) return new NextResponse(null, { status: 204 }); const parsed = pageViewSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ message: "Neplatná událost." }, { status: 422 }); const userAgent = request.headers.get("user-agent") || ""; const device = deviceType(userAgent); if (device === "bot") return new NextResponse(null, { status: 204 }); const city = await getPublishedCity(parsed.data.cityId || defaultCitySlug); if (!city) return new NextResponse(null, { status: 204 }); const salt = process.env.RATE_LIMIT_SALT || "local-analytics"; const sessionHash = createHash("sha256").update(`${salt}:${parsed.data.sessionId}`).digest("hex"); await insertRecord("page_views", { path: parsed.data.path, city_id: city.id, university_id: parsed.data.universityId || null, faculty_id: parsed.data.facultyId || null, referral_code: parsed.data.referralCode || null, session_hash: sessionHash, device_type: device, referrer_domain: parsed.data.referrerDomain || null, is_bot: false, viewed_at: new Date().toISOString(), day_bucket: new Date().toISOString().slice(0, 10) }); return new NextResponse(null, { status: 204 }); }
