import { PGlite } from "@electric-sql/pglite";
import { readFile } from "node:fs/promises";
import { expect,it } from "vitest";
it("soukromé kresby: migrace, RLS, revize, vlastník a payload",{timeout:30000},async()=>{
 const db=new PGlite();try{await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email_confirmed_at timestamptz);create table public.profiles(id uuid primary key,account_status text,is_blocked boolean);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to authenticated,anon;grant select on public.profiles to authenticated;create function public.consume_marketplace_rate_limit(text,text,integer,integer) returns boolean language sql as $$select true$$;insert into auth.users values ('11111111-1111-4111-8111-111111111111',now()),('22222222-2222-4222-8222-222222222222',now());insert into profiles select id,'active',false from auth.users;`);
 await db.exec(`revoke select on public.profiles from authenticated;create function public.is_active_profile() returns boolean language sql security definer set search_path='' as $$select exists(select 1 from public.profiles p join auth.users u on u.id=p.id where p.id=auth.uid() and p.account_status='active' and not p.is_blocked and u.email_confirmed_at is not null)$$;grant execute on function public.is_active_profile() to authenticated;`);
 const sql=await readFile('supabase/migrations/202610100001_private_coloring_progress.sql','utf8');await db.exec(sql);await db.exec(sql);const repair=await readFile('supabase/migrations/202610100002_coloring_conflict_no_retry.sql','utf8');await db.exec(repair);await db.exec(repair);await db.exec(`set role authenticated;set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111'`);
 const payload=JSON.stringify({assetVersion:1,colors:{1:'#abcdef'},strokes:[],completed:false});
 const save=()=>db.query<{revision:number}>("select revision from public.save_coloring_progress('desk',$1,$2::jsonb,10)",[0,payload]);expect((await save()).rows[0].revision).toBe(1);await expect(save()).rejects.toMatchObject({message:'coloring_revision_conflict',code:'P0001'});expect((await db.query<{revision:number}>("select revision from public.save_coloring_progress('desk',1,$1::jsonb,20)",[payload])).rows[0].revision).toBe(2);
 await db.exec(`set request.jwt.claim.sub='22222222-2222-4222-8222-222222222222'`);expect((await db.query('select * from public.coloring_progress')).rows).toHaveLength(0);await expect(db.exec("update public.coloring_progress set user_id='22222222-2222-4222-8222-222222222222'")).rejects.toThrow();
 await expect(db.query("select public.save_coloring_progress('desk',0,$1::jsonb,0)",[JSON.stringify({assetVersion:1,colors:{},strokes:[{points:[[0,0,0]]}],completed:false})])).rejects.toThrow('coloring_invalid_payload');
 await db.exec('reset role;set role anon');await expect(db.query('select * from public.coloring_progress')).rejects.toThrow();
 }finally{await db.close();}
});
