import { NextResponse } from "next/server";
import { cleanPlaceText, removePlacePhotos } from "@/lib/place-community-server";
import { allowRequest, requestFingerprint } from "@/lib/rate-limit";
import { createServiceClient } from "@/lib/supabase-server";
import { getCurrentAccount } from "@/lib/user-auth";
import { z } from "zod";

const updateSchema=z.object({action:z.enum(["update","withdraw"]),name:z.string().trim().min(2).max(160).optional(),description:z.string().trim().min(20).max(2000).optional(),usefulnessReason:z.string().trim().min(10).max(1000).optional(),sourceUrl:z.string().url().startsWith("https://").optional(),openingHours:z.string().trim().max(600).optional(),accessConditions:z.string().trim().max(800).optional()});
export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){const account=await getCurrentAccount();if(!account)return NextResponse.json({message:"Přihlaste se."},{status:401});if(!allowRequest(`place-suggestion-edit:${account.id}:${requestFingerprint(request)}`,30,60*60*1000))return NextResponse.json({message:"Limit úprav byl vyčerpán."},{status:429});const parsed=updateSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Neplatná úprava."},{status:422});const id=(await context.params).id;const client=createServiceClient();const {data:item}=await client.from("place_submissions").select("*").eq("id",id).eq("author_id",account.id).maybeSingle();if(!item)return NextResponse.json({message:"Návrh nebyl nalezen."},{status:404});if(!["draft","pending","changes_requested"].includes(item.status))return NextResponse.json({message:"Tento návrh už nelze přímo upravit."},{status:409});const now=new Date().toISOString();if(parsed.data.action==="withdraw"){const {error}=await client.from("place_submissions").update({status:"withdrawn",reviewed_at:now}).eq("id",id).eq("author_id",account.id);if(error)return NextResponse.json({message:"Návrh se nepodařilo stáhnout."},{status:422});await client.from("place_submission_history").insert({submission_id:id,actor_id:account.id,action:"withdrawn",snapshot:{previousStatus:item.status}});return NextResponse.json({message:"Návrh byl stažen."});}const value=parsed.data;const changes={...(value.name?{name:cleanPlaceText(value.name)}:{}),...(value.description?{description:cleanPlaceText(value.description,true)}:{}),...(value.usefulnessReason?{usefulness_reason:cleanPlaceText(value.usefulnessReason,true)}:{}),...(value.sourceUrl?{source_url:value.sourceUrl}:{}),...(value.openingHours!==undefined?{opening_hours:value.openingHours||null}:{}),...(value.accessConditions!==undefined?{access_conditions:cleanPlaceText(value.accessConditions,true)||null}:{}),status:"pending",submitted_at:now};const {error}=await client.from("place_submissions").update(changes).eq("id",id).eq("author_id",account.id);if(error)return NextResponse.json({message:"Návrh se nepodařilo upravit."},{status:422});await client.from("place_submission_history").insert({submission_id:id,actor_id:account.id,action:"edited",snapshot:Object.keys(changes)});return NextResponse.json({message:"Úpravy byly odeslány ke kontrole."});}
export async function DELETE(_request:Request,context:{params:Promise<{id:string}>}){const account=await getCurrentAccount();if(!account)return NextResponse.json({message:"Přihlaste se."},{status:401});const id=(await context.params).id;const client=createServiceClient();const {data:item}=await client.from("place_submissions").select("status").eq("id",id).eq("author_id",account.id).maybeSingle();if(!item||!["draft","withdrawn"].includes(item.status))return NextResponse.json({message:"Odstranit lze pouze rozpracovaný nebo stažený návrh."},{status:409});const {data:photos}=await client.from("place_submission_photos").select("storage_path").eq("submission_id",id);await removePlacePhotos((photos||[]).map((photo)=>photo.storage_path));await client.from("place_submissions").delete().eq("id",id).eq("author_id",account.id);return new NextResponse(null,{status:204});}
