import type { ContentSource } from "@/lib/sources/types";

const muniSource = "https://is.muni.cz/predmety/obdobi";

type RegisteredSource = Omit<ContentSource, "academicYear" | "confidence" | "requiresReview" | "notes" | "sourceDocumentTitle">;
const registeredSources: RegisteredSource[] = [
  ...["muni-prav", "muni-lf", "muni-prf", "muni-ff", "muni-pedf", "muni-faf", "muni-esf", "muni-fi", "muni-fss", "muni-fsps"].map((facultyId) => ({
    id: `src-${facultyId}`, universityId: "muni", facultyId, sourceType: "academic_calendar" as const,
    sourceUrl: muniSource, officialDomain: "is.muni.cz", format: "html" as const, parserKey: "muni-is-periods",
    enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_publish" as const,
    termsNote: "Veřejný strukturovaný přehled harmonogramů období IS MUNI, mapovaný podle fakultních sloupců.",
  })),
  { id: "src-vut-fekt", universityId: "vut", facultyId: "vut-fekt", sourceType: "academic_calendar", sourceUrl: "https://www.fekt.vut.cz/pro_studenty/casovy_plan", officialDomain: "fekt.vut.cz", format: "html", parserKey: "linked-document-review", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_review", termsNote: "Stránka odkazuje na roční časový plán; změnu dokumentu kontroluje editor." },
  { id: "src-vut-fit", universityId: "vut", facultyId: "vut-fit", sourceType: "academic_calendar", sourceUrl: "https://www.fit.vut.cz/study/calendar/", officialDomain: "fit.vut.cz", format: "html", parserKey: "vut-fit-html", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_publish", termsNote: "Veřejný strukturovaný časový plán FIT VUT bez přihlášení." },
  { id: "src-vut-fast", universityId: "vut", facultyId: "vut-fast", sourceType: "academic_calendar", sourceUrl: "https://www.fce.vut.cz/pro-studenty/casovy-plan-studia", officialDomain: "fce.vut.cz", format: "html", parserKey: "linked-document-review", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_review", termsNote: "Oficiální časový plán FAST; před publikací se kontroluje konkrétní studijní program." },
  { id: "src-vut-fsi", universityId: "vut", facultyId: "vut-fsi", sourceType: "academic_calendar", sourceUrl: "https://www.fme.vutbr.cz/studenti/plan?degree=0&mode=0", officialDomain: "fme.vutbr.cz", format: "html", parserKey: "vut-fsi-html", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_publish", termsNote: "Veřejný časový plán FSI s volbou akademického roku." },
  { id: "src-vut-fa", universityId: "vut", facultyId: "vut-fa", sourceType: "academic_calendar", sourceUrl: "https://www.fa.vut.cz/pages/casovy_plan.aspx", officialDomain: "fa.vut.cz", format: "html", parserKey: "linked-document-review", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_review", termsNote: "Oficiální časový plán FA obsahuje roční a oborové termíny; změny před publikací kontroluje editor." },
  { id: "src-vut-fch", universityId: "vut", facultyId: "vut-fch", sourceType: "academic_calendar", sourceUrl: "https://www.fch.vut.cz/studenti/studium/prvak", officialDomain: "fch.vut.cz", format: "html", parserKey: "linked-document-review", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_review", termsNote: "Oficiální studentský rozcestník odkazuje na časový plán; nutná kontrola dokumentu." },
  { id: "src-vut-fp", universityId: "vut", facultyId: "vut-fp", sourceType: "academic_calendar", sourceUrl: "https://www.fp.vut.cz/cs/pro-studenty/casovy-plan", officialDomain: "fp.vut.cz", format: "html", parserKey: "linked-document-review", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_review", termsNote: "Oficiální stránka časových plánů FP; dokument se schvaluje redakčně." },
  { id: "src-vut-favu", universityId: "vut", facultyId: "vut-favu", sourceType: "academic_calendar", sourceUrl: "https://www.favu.vut.cz/studenti/casovy-plan", officialDomain: "favu.vut.cz", format: "html", parserKey: "linked-document-review", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_review", termsNote: "Detailní časový plán FaVU obsahuje oborové výjimky; automatické publikování je vypnuté." },
  { id: "src-mendelu-af", universityId: "mendelu", facultyId: "mendelu-af", sourceType: "academic_calendar", sourceUrl: "https://af.mendelu.cz/o-fakulte/uredni-deska/", officialDomain: "af.mendelu.cz", format: "html", parserKey: "linked-document-review", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_review", termsNote: "Úřední deska obsahuje oficiální PDF harmonogram; změny schvaluje editor." },
  { id: "src-mendelu-ldf", universityId: "mendelu", facultyId: "mendelu-ldf", sourceType: "academic_calendar", sourceUrl: "https://ldf.mendelu.cz/student/harmonogram/", officialDomain: "ldf.mendelu.cz", format: "html", parserKey: "linked-document-review", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_review", termsNote: "Oficiální stránka odkazuje na roční PDF harmonogram LDF." },
  { id: "src-mendelu-pef", universityId: "mendelu", facultyId: "mendelu-pef", sourceType: "academic_calendar", sourceUrl: "https://pef.mendelu.cz/o-fakulte/uredni-deska/", officialDomain: "pef.mendelu.cz", format: "html", parserKey: "mendelu-pef-html", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_publish", termsNote: "Veřejná tabulka PEF obsahuje výuku, zkoušky a registrace pro aktuální rok." },
  { id: "src-mendelu-zf", universityId: "mendelu", facultyId: "mendelu-zf", sourceType: "academic_calendar", sourceUrl: "https://zf.mendelu.cz/harmonogram-akademickeho-roku/", officialDomain: "zf.mendelu.cz", format: "html", parserKey: "linked-document-review", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_review", termsNote: "Oficiální stránka ZF zveřejňuje harmonogram jako PDF; nutná kontrola." },
  { id: "src-mendelu-frrms", universityId: "mendelu", facultyId: "mendelu-frrms", sourceType: "academic_calendar", sourceUrl: "https://frrms.mendelu.cz/student/", officialDomain: "frrms.mendelu.cz", format: "html", parserKey: "not-found-monitor", enabled: true, refreshIntervalHours: 24, monitoringMode: "not_found_monitored", termsNote: "Jednoznačný veřejný harmonogram nebyl nalezen; oficiální studentská stránka se denně kontroluje." },
  { id: "src-vetuni-fvl", universityId: "vetuni", facultyId: "vetuni-fvl", sourceType: "academic_calendar", sourceUrl: "https://www.vetuni.cz/Rozpis_vyuky_pro_akademicky_rok", officialDomain: "vetuni.cz", format: "html", parserKey: "linked-document-review", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_review", termsNote: "Stabilní oficiální rozcestník každoročně odkazuje na společný PDF rozpis výuky VETUNI." },
  { id: "src-vetuni-fvhe", universityId: "vetuni", facultyId: "vetuni-fvhe", sourceType: "academic_calendar", sourceUrl: "https://www.vetuni.cz/Rozpis_vyuky_pro_akademicky_rok", officialDomain: "vetuni.cz", format: "html", parserKey: "linked-document-review", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_review", termsNote: "Stabilní oficiální rozcestník každoročně odkazuje na společný PDF rozpis výuky VETUNI." },
  { id: "src-jamu-hf", universityId: "jamu", facultyId: "jamu-hf", sourceType: "academic_calendar", sourceUrl: "https://is.jamu.cz/predmety/obdobi", officialDomain: "is.jamu.cz", format: "html", parserKey: "jamu-is-periods", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_publish", termsNote: "Veřejný strukturovaný přehled harmonogramů IS JAMU, sloupec Hudební fakulty." },
  { id: "src-jamu-df", universityId: "jamu", facultyId: "jamu-df", sourceType: "academic_calendar", sourceUrl: "https://is.jamu.cz/predmety/obdobi", officialDomain: "is.jamu.cz", format: "html", parserKey: "jamu-is-periods", enabled: true, refreshIntervalHours: 24, monitoringMode: "automatic_publish", termsNote: "Veřejný strukturovaný přehled harmonogramů IS JAMU, sloupec Divadelní fakulty." },
];

export const contentSources: ContentSource[] = registeredSources.map((source) => ({
  ...source,
  allowedDomains: source.universityId === "muni" ? ["muni.cz"] : source.universityId === "vut" ? ["vut.cz", "vutbr.cz"] : source.universityId === "mendelu" ? ["mendelu.cz"] : source.universityId === "vetuni" ? ["vetuni.cz"] : ["jamu.cz"],
  academicYear: source.sourceUrl.match(/20\d{2}[-_/](?:20)?\d{2}/)?.[0]?.replace(/[-_]/g, "/").replace(/\/(\d{2})$/, (_match, year: string) => `/${String(Number(year.slice(0, 2)) + 2000)}`) || null,
  confidence: source.monitoringMode === "automatic_publish" ? 0.96 : source.monitoringMode === "not_found_monitored" ? 0 : 0.6,
  requiresReview: source.monitoringMode !== "automatic_publish",
  notes: source.termsNote,
  sourceDocumentTitle: source.format === "pdf" ? "Oficiální harmonogram akademického roku" : undefined,
}));

export function sourceById(id: string) { return contentSources.find((source) => source.id === id); }
export function allowedSourceHosts() { return new Set(contentSources.flatMap((source) => [new URL(source.sourceUrl).hostname.toLowerCase(), ...(source.allowedDomains || [])])); }
