import { NextResponse } from "next/server";
import { z } from "zod";
import { getAdminUser } from "@/lib/admin-auth";
import { createServiceClient, isSupabaseConfigured } from "@/lib/supabase-server";

const schema = z.object({ targetType: z.enum(["post", "comment", "author", "settings"]), targetId: z.string().min(1), action: z.enum(["hide", "restore", "delete", "block_author", "dismiss_report", "set_threshold"]), reason: z.string().trim().max(800).default(""), threshold: z.number().int().min(2).max(20).optional(), reportId: z.string().uuid().optional() });

export async function PATCH(request: Request) {
  const admin = await getAdminUser(); if (!admin) return NextResponse.json({ message: "Nepřihlášeno." }, { status: 401 }); if (admin.role === "faculty_editor") return NextResponse.json({ message: "Fakultní editor nemá přístup k městské komunitní moderaci." }, { status: 403 }); if (!isSupabaseConfigured()) return NextResponse.json({ message: "Moderace vyžaduje připojenou databázi." }, { status: 503 });
  const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ message: "Neplatná moderátorská operace." }, { status: 422 }); const input = parsed.data; const client = createServiceClient();
  if (input.targetType === "settings") { const cityId = input.targetId; if (admin.role !== "super_admin" && admin.cityId !== cityId) return NextResponse.json({ message: "Město není ve vašem rozsahu." }, { status: 403 }); if (input.action !== "set_threshold" || !input.threshold) return NextResponse.json({ message: "Neplatný limit." }, { status: 422 }); const { error } = await client.from("community_moderation_settings").upsert({ city_id: cityId, auto_hide_threshold: input.threshold, updated_at: new Date().toISOString() }, { onConflict: "city_id" }); return error ? NextResponse.json({ message: error.message }, { status: 422 }) : NextResponse.json({ message: "Limit automatického skrytí byl uložen." }); }
  const table = input.targetType === "post" ? "community_posts" : input.targetType === "comment" ? "community_comments" : "community_profiles"; const key = input.targetType === "author" ? "user_id" : "id"; const { data: rawTarget } = await client.from(table).select("*").eq(key, input.targetId).maybeSingle(); const target = rawTarget as Record<string, unknown> | null; if (!target) return NextResponse.json({ message: "Obsah nebyl nalezen." }, { status: 404 });
  let cityId = String(target.city_id || ""); if (input.targetType === "comment") { const { data: parent } = await client.from("community_posts").select("city_id").eq("id", String(target.post_id)).maybeSingle(); cityId = String(parent?.city_id || ""); } if (!cityId) return NextResponse.json({ message: "Rozsah obsahu nelze ověřit." }, { status: 422 }); if (admin.role !== "super_admin" && admin.cityId !== cityId) return NextResponse.json({ message: "Obsah není ve vašem rozsahu." }, { status: 403 });
  if (input.action === "dismiss_report") { if (!input.reportId) return NextResponse.json({ message: "Chybí hlášení." }, { status: 422 }); const { error } = await client.from("community_reports").update({ status: "dismissed", reviewed_at: new Date().toISOString() }).eq("id", input.reportId).eq("city_id", cityId); if (error) return NextResponse.json({ message: error.message }, { status: 422 }); await client.from("community_moderation_history").insert({ city_id: cityId, target_type: input.targetType, target_id: input.targetId, action: "report_dismissed", actor_id: admin.id, reason: input.reason, snapshot: { report_id: input.reportId } }); return NextResponse.json({ message: "Hlášení bylo zamítnuto." }); }
  let action: "hidden" | "restored" | "deleted" | "author_blocked"; let error: { message: string } | null = null;
  if (input.action === "block_author") { const authorId = input.targetType === "author" ? input.targetId : String(target.author_id || ""); if (!authorId) return NextResponse.json({ message: "Autor už nemá aktivní účet." }, { status: 409 }); const [base, community] = await Promise.all([client.from("profiles").update({ is_blocked: true }).eq("id", authorId), client.from("community_profiles").update({ status: "blocked" }).eq("user_id", authorId)]); error = base.error || community.error; action = "author_blocked"; }
  else { if (input.targetType === "author") return NextResponse.json({ message: "Pro autora je dostupné pouze zablokování." }, { status: 422 }); const status = input.action === "hide" ? "hidden" : input.action === "restore" ? "active" : "deleted"; const result = await client.from(table).update({ status, ...(status === "deleted" ? { deleted_at: new Date().toISOString() } : {}), ...(input.targetType === "comment" && status !== "active" ? { is_best: false } : {}) }).eq("id", input.targetId); error = result.error; action = input.action === "hide" ? "hidden" : input.action === "restore" ? "restored" : "deleted"; }
  if (error) return NextResponse.json({ message: error.message }, { status: 422 }); await client.from("community_moderation_history").insert({ city_id: cityId, target_type: input.targetType, target_id: input.targetId, action, actor_id: admin.id, reason: input.reason, snapshot: { previous_status: target.status, nickname: target.author_nickname || target.nickname, report_count: target.report_count || 0 } });
  if (input.reportId) await client.from("community_reports").update({ status: "actioned", reviewed_at: new Date().toISOString() }).eq("id", input.reportId).eq("city_id", cityId);
  return NextResponse.json({ message: action === "hidden" ? "Obsah byl skryt." : action === "restored" ? "Obsah byl obnoven." : action === "deleted" ? "Obsah byl bezpečně odstraněn." : "Autor byl zablokován." });
}
