"use client";
import { KeyRound, Loader2, LockKeyhole, LogIn } from "lucide-react";
import { useState } from "react";

export function AdminLoginForm() {
  const [pending, setPending] = useState(false); const [recovery, setRecovery] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setPending(true); setError(""); setNotice(""); try { const response = await fetch(recovery ? "/api/admin/recover" : "/api/admin/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: form.get("email"), ...(!recovery && { password: form.get("password") }) }) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setError(result.message || (recovery ? "Požadavek se nepodařilo odeslat." : "Přihlášení se nezdařilo.")); return; } if (recovery) { setNotice(result.message); return; } window.location.assign("/admin"); } catch { setError("Síťové připojení selhalo. Zkuste to prosím znovu."); } finally { setPending(false); } }
  return <form className="admin-login-card" onSubmit={submit}><span className="admin-login-icon">{recovery ? <KeyRound size={26} /> : <LockKeyhole size={26} />}</span><h1>{recovery ? "Obnova přístupu" : "Administrace"}</h1><p>{recovery ? "Zadejte e-mail správce. Odpověď neprozradí, zda účet existuje." : "Přístup je určen pouze schváleným správcům a fakultním editorům."}</p><label><span>E-mail</span><input name="email" type="email" autoComplete="username" required /></label>{!recovery && <label><span>Heslo</span><input name="password" type="password" autoComplete="current-password" required /></label>}{error && <p className="field-error" role="alert">{error}</p>}{notice && <p className="success-message" role="status">{notice}</p>}<button className="button button-primary" disabled={pending}>{pending ? <Loader2 className="spin" size={18} /> : recovery ? <KeyRound size={18} /> : <LogIn size={18} />}{pending ? "Odesílám…" : recovery ? "Poslat obnovovací odkaz" : "Přihlásit se"}</button><button className="continue-link" type="button" disabled={pending} onClick={() => { setRecovery(!recovery); setError(""); setNotice(""); }}>{recovery ? "Zpět k přihlášení" : "Zapomenuté heslo?"}</button><small>V produkci ověřuje účet Supabase Auth. Nové heslo musí mít alespoň 12 znaků.</small></form>;
}
