"use client";

import { AlertTriangle, CheckCircle2, ExternalLink, RefreshCcw, Sparkles } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type Row = Record<string, unknown>;
const labels: Record<string, string> = { new: "Nové", needs_review: "Vyžaduje kontrolu", confirmed_correct: "Potvrzeno jako správné", approved_fix: "Schválená oprava", rejected: "Zamítnuto", resolved: "Vyřešeno", cannot_verify: "Nelze ověřit" };

export function CalendarAiAdminPanel({ canRun }: { canRun: boolean }) {
  const [payload, setPayload] = useState<{ configuration?: Row; latest?: Row | null; lastSuccessful?: Row | null; runs: Row[]; findings: Row[]; stats: Row }>({ runs: [], findings: [], stats: {} });
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/admin/calendar-ai", { cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok) { setError(String(data.message || "Kontrolu kalendáře se nepodařilo načíst.")); return; } setPayload(data); }, []);
  useEffect(() => { load(); }, [load]);
  async function run(sourceId?: string) { setBusy(true); setError(""); setNotice(""); const response = await fetch("/api/admin/calendar-ai", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(sourceId ? { sourceId } : {}) }); const data = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) setError(String(data.reason || data.message || (data.status === "blocked" ? "Kontrola je zablokovaná." : "Ruční kontrola selhala."))); else setNotice("Kontrola byla dokončena; veřejný kalendář se nezměnil."); await load(); }
  async function setStatus(id: string, status: string) { setError(""); const response = await fetch(`/api/admin/calendar-ai/findings/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setError(String(data.message || "Stav nálezu se nepodařilo změnit.")); return; } setNotice("Stav nálezu byl uložen."); await load(); }
  const latest = payload.latest || {}; const stats = payload.stats || {};
  return <section className="admin-panel"><div className="admin-section-head"><div><h2><Sparkles size={20} /> Kontrola kalendáře</h2><p>AI pouze porovnává veřejné akademické zdroje Brna. Žádná změna se bez ručního schválení nepublikuje.</p></div><div className="source-actions"><button className="button button-secondary" onClick={load}><RefreshCcw size={15} />Obnovit</button>{canRun && <button className="button button-primary" disabled={busy} onClick={() => run()}>{busy ? "Kontroluji…" : "Spustit kontrolu"}</button>}</div></div>
    <div className="admin-data-note"><AlertTriangle size={18} /><p><strong>Stav AI:</strong> {payload.configuration?.enabled && payload.configuration?.configured ? `aktivní · ${String(payload.configuration.model || "model")}` : "BLOCKED · AI credentials nejsou aktivní"}. Při blokaci zůstávají poslední ověřená data beze změny.</p></div>
    {error && <div className="error-state" role="alert">{error}</div>}{notice && <div className="success-message" role="status">{notice}</div>}
    <div className="admin-stats"><article><CheckCircle2 size={18} /><span>Zdroje</span><strong>{String(stats.sources ?? latest.source_count ?? 0)}</strong></article><article><RefreshCcw size={18} /><span>Zkontrolované termíny</span><strong>{String(latest.checked_event_count ?? 0)}</strong></article><article><AlertTriangle size={18} /><span>Otevřené nálezy</span><strong>{String(stats.openFindings ?? 0)}</strong></article><article><AlertTriangle size={18} /><span>Nedostupné zdroje</span><strong>{String(stats.unavailable ?? latest.unavailable_source_count ?? 0)}</strong></article><article><AlertTriangle size={18} /><span>Konflikty</span><strong>{String(stats.conflicts ?? latest.conflict_count ?? 0)}</strong></article></div>
    <p className="admin-muted">Poslední běh: {String(latest.started_at || "zatím neproběhl")} · stav {String(latest.status || "—")} · dokončení {String(latest.finished_at || "—")} · poslední úspěch {String(payload.lastSuccessful?.finished_at || "zatím žádný")} · ověřené zdroje {String(latest.checked_source_count || 0)} · chyba {String(latest.error_message || "žádná")}</p>
    <div className="approval-list">{payload.findings.length === 0 ? <div className="empty-state"><h3>Žádné nálezy</h3><p>Nové rozdíly, konflikty a nedostupné zdroje se objeví po kontrolovaném běhu.</p></div> : payload.findings.map((finding) => <article key={String(finding.id)}><div><span className="tag">{labels[String(finding.status)] || String(finding.status)} · {String(finding.academic_year || "rok neuveden")}</span><h3>{String(finding.difference)}</h3><small>{String(finding.university_id || "")} · {String(finding.faculty_id || "")} · {String(finding.term_type || "")}</small><small>Kontrola: {String(finding.checked_at || "—")} · jistota {Math.round(Number(finding.confidence || 0) * 100)} % · datum zdroje/HTTP: {String(finding.source_published_at || "neuvedeno")}</small><a href={String(finding.source_url)} target="_blank" rel="noopener noreferrer"><ExternalLink size={14} />Otevřít zdroj</a><details><summary>Porovnat hodnoty</summary><pre>{JSON.stringify({ current: finding.current_value, discovered: finding.discovered_value, ai: finding.ai_reason }, null, 2)}</pre></details></div><div className="source-actions">{canRun && Boolean(finding.source_id) && <button className="button button-secondary" disabled={busy} onClick={() => run(String(finding.source_id))}>Zkontrolovat zdroj termínu</button>}{["new", "needs_review", "cannot_verify"].includes(String(finding.status)) && <><button className="button button-secondary" onClick={() => setStatus(String(finding.id), "confirmed_correct")}>Potvrdit</button><a className="button button-secondary" href="/admin?section=academic_events">Ručně upravit termín</a>{Boolean(finding.academic_event_id) && <button className="button button-primary" onClick={() => setStatus(String(finding.id), "approved_fix")}>Potvrdit provedenou opravu</button>}<button className="button button-secondary" onClick={() => setStatus(String(finding.id), "rejected")}>Zamítnout</button></>}</div></article>)}</div>
  </section>;
}
