"use client";

import { AlertTriangle, CheckCircle2, ExternalLink, RefreshCcw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type Row = Record<string, unknown>;
type CityOption = { id: string; name: string };
type CoverageRow = { cityId: string; universityId: string; universityName: string; facultyId: string; facultyName: string; status: string; evidence: string; sources: Row[] };
const labels: Record<string, string> = { new: "Nové", needs_review: "Vyžaduje kontrolu", confirmed_correct: "Potvrzeno jako správné", approved_fix: "Schválená oprava", rejected: "Zamítnuto", resolved: "Vyřešeno", cannot_verify: "Nelze ověřit" };
const coverageLabels: Record<string, string> = { complete: "Úplné", covered_by_central: "Pokryto centrálně", partial: "Částečné", needs_review: "Vyžaduje kontrolu", blocked: "Blokováno", unavailable: "Nedostupné", stale: "Neaktuální" };

export function CalendarAiAdminPanel({ canRun }: { canRun: boolean }) {
  const [payload, setPayload] = useState<{ city?: CityOption; availableCities?: CityOption[]; configuration?: Row; latest?: Row | null; lastSuccessful?: Row | null; runs: Row[]; findings: Row[]; coverage?: CoverageRow[]; stats: Row }>({ runs: [], findings: [], coverage: [], stats: {} });
  const [cityId, setCityId] = useState("brno");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [showClosed, setShowClosed] = useState(false);
  const load = useCallback(async () => { const response = await fetch(`/api/admin/calendar-ai?city=${encodeURIComponent(cityId)}`, { cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok) { setError(String(data.message || "Kontrolu kalendáře se nepodařilo načíst.")); return; } setPayload(data); if (data.city?.id && data.city.id !== cityId) setCityId(String(data.city.id)); }, [cityId]);
  useEffect(() => { load(); }, [load]);
  async function run(sourceId?: string) { setBusy(true); setError(""); setNotice(""); const response = await fetch("/api/admin/calendar-ai", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ cityId, ...(sourceId ? { sourceId } : {}) }) }); const data = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) setError(String(data.reason || data.message || (data.status === "blocked" ? "Kontrola je zablokovaná." : "Ruční kontrola selhala."))); else setNotice("Kontrola byla dokončena; veřejný kalendář se nezměnil."); await load(); }
  async function setStatus(id: string, status: string) { setError(""); const response = await fetch(`/api/admin/calendar-ai/findings/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setError(String(data.message || "Stav nálezu se nepodařilo změnit.")); return; } setNotice("Stav nálezu byl uložen."); await load(); }
  const latest = payload.latest || {}; const stats = payload.stats || {};
  const visibleFindings = payload.findings.filter((finding) => showClosed || ["new", "needs_review", "cannot_verify"].includes(String(finding.status)));
  return <section className="admin-panel"><div className="admin-section-head"><div><h2><CheckCircle2 size={20} /> Kontrola kalendáře{payload.city?.name ? ` · ${payload.city.name}` : ""}</h2><p>Jednou denně kolem 13:00 porovnáváme oficiální zdroje s termíny, které už jsou v kalendáři. Nové termíny řeší stávající synchronizace. Zde jsou jen rozdíly a zdroje, které nelze ověřit; veřejný kalendář se automaticky nemění.</p></div><div className="source-actions">{(payload.availableCities?.length || 0) > 1 && <label>Město<select value={cityId} onChange={(event) => { setError(""); setNotice(""); setCityId(event.target.value); }}>{payload.availableCities?.map((city) => <option key={city.id} value={city.id}>{city.name}</option>)}</select></label>}<button className="button button-secondary" onClick={() => load()}><RefreshCcw size={15} />Obnovit</button>{canRun && <button className="button button-primary" disabled={busy} onClick={() => run()}>{busy ? "Kontroluji…" : "Spustit kontrolu"}</button>}</div></div>
    <div className="admin-data-note"><AlertTriangle size={18} /><p>Kontrola běží bez placené AI služby a bez API kreditu. Pokud se zdroj nepodaří bezpečně načíst, ponecháme uložené termíny beze změny a zobrazíme upozornění.</p></div>
    {error && <div className="error-state" role="alert">{error}</div>}{notice && <div className="success-message" role="status">{notice}</div>}
    <div className="admin-stats"><article><CheckCircle2 size={18} /><span>Zdroje</span><strong>{String(stats.sources ?? latest.source_count ?? 0)}</strong></article><article><CheckCircle2 size={18} /><span>Pokryté fakulty</span><strong>{String(stats.complete ?? 0)} / {String(stats.faculties ?? 0)}</strong></article><article><RefreshCcw size={18} /><span>Zkontrolované termíny</span><strong>{String(latest.checked_event_count ?? 0)}</strong></article><article><AlertTriangle size={18} /><span>Otevřené nálezy</span><strong>{String(stats.openFindings ?? 0)}</strong></article><article><AlertTriangle size={18} /><span>Blokované / nedostupné</span><strong>{String(stats.blocked ?? 0)}</strong></article><article><AlertTriangle size={18} /><span>Konflikty</span><strong>{String(stats.conflicts ?? latest.conflict_count ?? 0)}</strong></article></div>
    <p className="admin-muted">Poslední běh: {String(latest.started_at || "zatím neproběhl")} · stav {String(latest.status || "—")} · dokončení {String(latest.finished_at || "—")} · poslední úspěch {String(payload.lastSuccessful?.finished_at || "zatím žádný")} · ověřené zdroje {String(latest.checked_source_count || 0)} · chyba {String(latest.error_message || "žádná")}</p>
    <details className="admin-details" open><summary>Pokrytí fakult ({String(stats.complete ?? 0)} z {String(stats.faculties ?? 0)})</summary><div className="approval-list">{payload.coverage?.map((row) => <article key={row.facultyId}><div><span className="tag">{coverageLabels[row.status] || row.status}</span><h3>{row.universityName} · {row.facultyName}</h3><small>{row.evidence}</small>{row.sources.map((source) => <small key={String(source.id)}>{String(source.parser_key || "—")} · poslední úspěch {String(source.last_success_at || "zatím žádný")} · další kontrola {String(source.next_check_at || "—")} · stav {String(source.sync_status || "—")}</small>)}</div><div className="source-actions">{row.sources.map((source) => <a key={String(source.id)} className="button button-secondary" href={String(source.source_url)} target="_blank" rel="noopener noreferrer"><ExternalLink size={14} />Zdroj</a>)}</div></article>)}</div></details>
    <button className="button button-secondary" type="button" onClick={() => setShowClosed((value) => !value)}>{showClosed ? "Skrýt vyřízené nálezy" : "Zobrazit i vyřízené nálezy"}</button>
    <div className="approval-list">{visibleFindings.length === 0 ? <div className="empty-state"><h3>Žádné otevřené rozdíly</h3><p>Další kontrola proběhne automaticky, případně ji můžete spustit ručně.</p></div> : visibleFindings.map((finding) => <article key={String(finding.id)}><div><span className="tag">{labels[String(finding.status)] || String(finding.status)} · {String(finding.academic_year || "rok neuveden")}</span><h3>{String(finding.difference)}</h3><small>{String(finding.university_id || "")} · {String(finding.faculty_id || "")} · {String(finding.term_type || "")}</small><small>Kontrola: {String(finding.checked_at || "—")} · jistota {Math.round(Number(finding.confidence || 0) * 100)} % · datum zdroje/HTTP: {String(finding.source_published_at || "neuvedeno")}</small><a href={String(finding.source_url)} target="_blank" rel="noopener noreferrer"><ExternalLink size={14} />Otevřít zdroj</a><details><summary>Porovnat hodnoty</summary><pre>{JSON.stringify({ current: finding.current_value, discovered: finding.discovered_value }, null, 2)}</pre></details></div><div className="source-actions">{canRun && Boolean(finding.source_id) && <button className="button button-secondary" disabled={busy} onClick={() => run(String(finding.source_id))}>Zkontrolovat zdroj termínu</button>}{["new", "needs_review", "cannot_verify"].includes(String(finding.status)) && <><button className="button button-secondary" onClick={() => setStatus(String(finding.id), "confirmed_correct")}>Potvrdit</button><a className="button button-secondary" href="/admin?section=academic_events">Ručně upravit termín</a>{Boolean(finding.academic_event_id) && <button className="button button-primary" onClick={() => setStatus(String(finding.id), "approved_fix")}>Potvrdit provedenou opravu</button>}<button className="button button-secondary" onClick={() => setStatus(String(finding.id), "rejected")}>Zamítnout</button></>}</div></article>)}</div>
  </section>;
}
