"use client";

import { useCallback, useEffect, useState } from "react";
import { Flag, MessageCircle, ShieldAlert } from "lucide-react";

type Row = Record<string, unknown>;
type Data = { statistics: { requested: number; active: number; reports: number }; items: Row[]; actions: Row[] };

export function ChatAdminPanel() {
  const [data, setData] = useState<Data>({ statistics: { requested: 0, active: 0, reports: 0 }, items: [], actions: [] }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/admin/chat", { cache: "no-store" }); if (!response.ok) return setError("Frontu chatových hlášení se nepodařilo načíst."); setData(await response.json()); setError(""); }, []);
  useEffect(() => { void load(); }, [load]);
  async function act(reportId: string, action: string) { const reason = prompt("Interní důvod moderátorské akce (povinný)"); if (!reason || reason.trim().length < 3) return; setBusy(true); const response = await fetch("/api/admin/chat", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reportId, action, reason }) }); setBusy(false); if (!response.ok) setError((await response.json()).message || "Akce selhala."); else await load(); }
  return <section className="admin-panel chat-admin-panel"><div className="admin-section-head"><div><h2>Hlášení soukromých zpráv</h2><p>Soukromé chaty se běžně nezobrazují. Moderátor vidí jen nahlášenou zprávu a nejvýše pět souvisejících zpráv nutných pro posouzení.</p></div></div><div className="admin-stats"><article><MessageCircle /><span>Žádosti</span><strong>{data.statistics.requested}</strong></article><article><MessageCircle /><span>Aktivní</span><strong>{data.statistics.active}</strong></article><article><Flag /><span>Hlášení</span><strong>{data.statistics.reports}</strong></article></div>{error && <div className="error-state" role="alert">{error}</div>}<div className="chat-admin-list">{data.items.length === 0 ? <p className="muted">Žádná hlášení nečekají na kontrolu.</p> : data.items.map((item) => { const message = item.message as Row | null; const context = Array.isArray(item.context) ? item.context as Row[] : []; return <article key={String(item.id)}><header><ShieldAlert size={18} /><div><strong>{String(item.reason)}</strong><small>{String(item.status)} · {String(item.created_at)}</small></div></header><blockquote>{message ? String(message.body) : "Zpráva už není dostupná."}</blockquote><details><summary>Omezený kontext ({context.length})</summary>{context.map((row) => <p key={String(row.id)}><small>{String(row.created_at)}</small>{String(row.body)}</p>)}</details><div className="card-actions"><button disabled={busy} className="button button-secondary" onClick={() => act(String(item.id), "dismiss_report")}>Zamítnout hlášení</button><button disabled={busy} className="button button-secondary" onClick={() => act(String(item.id), "hide_message")}>Skrýt zprávu</button><button disabled={busy} className="button button-secondary" onClick={() => act(String(item.id), "restrict_chat")}>Omezit chat</button><button disabled={busy} className="button button-danger" onClick={() => act(String(item.id), "suspend_profile")}>Pozastavit účet</button></div></article>; })}</div><details className="admin-audit-log"><summary>Audit moderace ({data.actions.length})</summary><ul>{data.actions.map((row) => <li key={String(row.id)}>{String(row.created_at)} · {String(row.action)} · {String(row.reason)}</li>)}</ul></details></section>;
}
