"use client";
/* Signed private avatars expire; bypass the Next image optimizer cache. */
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { Archive, ArrowUp, Ban, BellOff, Check, ChevronLeft, Flag, MoreVertical, Send, UserRound, WifiOff } from "lucide-react";
import { createBrowserClient } from "@supabase/ssr";
import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { ChatConversation, ChatMessage } from "@/lib/chat-types";
import { chatUnreadEvent } from "@/components/chat-badge";

const reportReasons = [
  ["harassment", "Obtěžování"], ["spam", "Spam"], ["fraud", "Podvod"], ["unsafe_meeting", "Nebezpečné setkání"], ["prohibited_sale", "Zakázaný prodej"], ["other", "Jiný důvod"],
] as const;

export function ChatThread({ conversationId, dock = false, onClose }: { conversationId: string; dock?: boolean; onClose?: () => void }) {
  const router = useRouter(); const [conversation, setConversation] = useState<ChatConversation | null>(null); const [messages, setMessages] = useState<ChatMessage[]>([]); const [cursor, setCursor] = useState<string | null>(null);
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [offline, setOffline] = useState(false); const [reporting, setReporting] = useState<string | null>(null); const [reportReason, setReportReason] = useState<(typeof reportReasons)[number][0]>("spam");
  const scrollRef = useRef<HTMLDivElement>(null); const editorRef = useRef<HTMLTextAreaElement>(null);
  const refresh = useCallback(async (scroll = false) => {
    const [conversationResponse, messagesResponse] = await Promise.all([fetch(`/api/chat/conversations/${conversationId}`, { cache: "no-store" }), fetch(`/api/chat/conversations/${conversationId}/messages`, { cache: "no-store" })]).catch(() => [] as unknown as [Response, Response]);
    if (!conversationResponse?.ok || !messagesResponse?.ok) { setOffline(!navigator.onLine); setError(conversationResponse?.status === 404 ? "Konverzace už není dostupná." : "Chat se nepodařilo obnovit."); setLoading(false); return; }
    const [conversationBody, messageBody] = await Promise.all([conversationResponse.json(), messagesResponse.json()]); setConversation(conversationBody.conversation); setMessages(messageBody.items || []); setCursor(messageBody.nextCursor || null); setError(""); setOffline(false); setLoading(false);
    if (document.visibilityState === "visible") { await fetch(`/api/chat/conversations/${conversationId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "read" }) }); window.dispatchEvent(new CustomEvent(chatUnreadEvent)); }
    if (scroll) requestAnimationFrame(() => scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" }));
  }, [conversationId]);
  useEffect(() => { void refresh(true); const focused = () => document.visibilityState === "visible" && void refresh(); window.addEventListener("focus", focused); window.addEventListener("online", focused); document.addEventListener("visibilitychange", focused); const timer = window.setInterval(focused, 20000);
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; const client = url && key ? createBrowserClient(url, key) : null;
    const channel = client?.channel(`chat-${conversationId}`).on("postgres_changes", { event: "INSERT", schema: "public", table: "chat_messages", filter: `conversation_id=eq.${conversationId}` }, () => void refresh(true)).on("postgres_changes", { event: "UPDATE", schema: "public", table: "chat_messages", filter: `conversation_id=eq.${conversationId}` }, () => void refresh()).subscribe();
    return () => { window.removeEventListener("focus", focused); window.removeEventListener("online", focused); document.removeEventListener("visibilitychange", focused); window.clearInterval(timer); if (client && channel) void client.removeChannel(channel); };
  }, [conversationId, refresh]);
  async function loadOlder() { if (!cursor) return; const response = await fetch(`/api/chat/conversations/${conversationId}/messages?before=${encodeURIComponent(cursor)}`, { cache: "no-store" }); if (!response.ok) return; const body = await response.json(); setMessages((current) => [...(body.items || []), ...current]); setCursor(body.nextCursor || null); }
  async function send(event: React.FormEvent) { event.preventDefault(); if (!message.trim() || sending) return; const value = message.trim(); setSending(true); setMessage(""); setError(""); const response = await fetch(`/api/chat/conversations/${conversationId}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: value, clientNonce: crypto.randomUUID() }) }).catch(() => null); setSending(false); if (!response?.ok) { const body = await response?.json().catch(() => ({})); setMessage(value); setError(body?.message || "Zprávu se nepodařilo odeslat."); return; } await refresh(true); editorRef.current?.focus(); }
  async function action(action: string, extra: Record<string, unknown> = {}) { const response = await fetch(`/api/chat/conversations/${conversationId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...extra }) }); if (!response.ok) { setError((await response.json()).message || "Akci se nepodařilo provést."); return; } if (action === "leave" || action === "archive") { onClose?.(); router.push("/chat"); return; } await refresh(); }
  async function report() { if (!reporting) return; const response = await fetch(`/api/chat/messages/${reporting}/report`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason: reportReason, detail: "" }) }); setReporting(null); setError(response.ok ? "Hlášení bylo předáno moderátorům." : (await response.json()).message || "Hlášení selhalo."); }
  if (loading) return <div className="chat-loading" role="status">Načítám zabezpečenou konverzaci…</div>;
  if (!conversation) return <div className="chat-empty"><WifiOff size={28} /><p>{error || "Konverzace není dostupná."}</p><Link className="button button-secondary" href="/chat">Zpět na zprávy</Link></div>;
  const blocked = conversation.status === "restricted" || conversation.status === "left" || conversation.status === "declined";
  return <section className={dock ? "chat-thread chat-thread-dock" : "chat-thread"} aria-label={`Konverzace s ${conversation.other.displayName}`}>
    <header className="chat-thread-head">{!dock && <Link href="/chat" className="icon-button" aria-label="Zpět na konverzace"><ChevronLeft /></Link>}<div className="chat-avatar" aria-hidden="true">{conversation.other.avatarUrl ? <img src={conversation.other.avatarUrl} alt="" /> : <UserRound size={19} />}</div><div className="chat-peer"><strong>{conversation.other.displayName}</strong><span>{conversation.status === "requested" ? "Žádost o kontakt" : conversation.status === "active" ? "Soukromá konverzace" : "Konverzace není aktivní"}</span></div><details className="chat-actions"><summary className="icon-button" aria-label="Akce konverzace"><MoreVertical /></summary><div><button type="button" onClick={() => action(conversation.mutedUntil ? "mute" : "mute", { until: conversation.mutedUntil ? null : new Date(Date.now() + 365 * 86400000).toISOString() })}><BellOff size={15} />{conversation.mutedUntil ? "Zapnout upozornění" : "Ztlumit"}</button><button type="button" onClick={() => action("archive")}><Archive size={15} />Archivovat</button><button type="button" onClick={() => action("block")}><Ban size={15} />Zablokovat uživatele</button></div></details></header>
    <div className={`chat-context ${conversation.context.active ? "" : "inactive"}`}>{conversation.context.href ? <Link href={conversation.context.href}><span>{conversation.context.title}</span>{conversation.context.detail && <small>{conversation.context.detail}</small>}</Link> : <div><span>{conversation.context.title}</span><small>Obsah už není aktivní</small></div>}</div>
    {conversation.canAccept && <div className="chat-request-actions"><p>Tento člověk vám poslal jednu žádost. Odpověď ji automaticky přijme.</p><div><button className="button button-secondary" onClick={() => action("decline")}>Odmítnout</button><button className="button button-primary" onClick={() => action("accept")}><Check size={16} />Přijmout</button></div></div>}
    <div className="chat-messages" ref={scrollRef}>{cursor && <button className="chat-load-older" onClick={loadOlder}><ArrowUp size={14} />Starší zprávy</button>}{messages.length === 0 && <p className="chat-no-messages">Zatím tu není žádná zpráva.</p>}{messages.map((item) => <article key={item.id} className={item.own ? "chat-message own" : "chat-message"}><div><p>{item.body}</p><time dateTime={item.createdAt}>{new Intl.DateTimeFormat("cs-CZ", { hour: "2-digit", minute: "2-digit", day: "numeric", month: "numeric" }).format(new Date(item.createdAt))}</time></div>{!item.own && item.state === "active" && <button type="button" aria-label="Nahlásit zprávu" title="Nahlásit zprávu" onClick={() => setReporting(item.id)}><Flag size={12} /></button>}</article>)}</div>
    {reporting && <div className="chat-report" role="dialog" aria-label="Nahlásit zprávu"><label>Důvod<select value={reportReason} onChange={(event) => setReportReason(event.target.value as typeof reportReason)}>{reportReasons.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><button className="button button-danger" onClick={report}>Odeslat hlášení</button><button className="button button-ghost" onClick={() => setReporting(null)}>Zrušit</button></div>}
    {(error || offline) && <p className={error.includes("předáno") ? "chat-status success" : "chat-status error"} role="status">{offline ? "Jste offline. Zprávy se obnoví po připojení." : error}</p>}
    {!blocked && <form className="chat-editor" onSubmit={send}><label className="sr-only" htmlFor={`chat-message-${conversationId}`}>Zpráva</label><textarea ref={editorRef} id={`chat-message-${conversationId}`} rows={1} maxLength={2000} value={message} disabled={conversation.status === "requested" && conversation.requestedByMe} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }} placeholder={conversation.status === "requested" && conversation.requestedByMe ? "Čeká na přijetí žádosti" : "Napište zprávu…"} /><button type="submit" className="icon-button chat-send" disabled={sending || !message.trim()} aria-label="Odeslat zprávu"><Send size={18} /></button></form>}
  </section>;
}
