import Link from "next/link";
import { ArrowRight, CalendarDays, ChevronRight, House, MessageCircle, ShoppingBag, Users } from "lucide-react";
import type { City } from "@/lib/cities";
import type { CityDashboardPreviews } from "@/lib/city-dashboard-previews";
import { formatShortDate } from "@/lib/format";

function price(mode: string, amount?: number) { if (mode === "free" || amount === 0) return "Zdarma"; if (mode === "negotiable") return "Dohodou"; return amount == null ? "Cena neuvedena" : `${new Intl.NumberFormat("cs-CZ").format(amount)} Kč`; }

export function CityDashboardActivitySections({ city, previews }: { city: City; previews: CityDashboardPreviews }) {
  const base = `/${city.slug}`;
  const sections = [
    previews.communityEvents.length ? <section className="dashboard-section" key="events"><div className="section-head"><div><span className="section-icon"><CalendarDays size={18} /></span><h2>Co se děje</h2></div><Link href={`${base}/kalendar?view=community`}>Všechny akce <ArrowRight size={16} /></Link></div><div className="compact-list">{previews.communityEvents.map((item) => <Link className="compact-row" href={`${base}/kalendar?view=community#${item.id}`} key={item.id}><span className="place-index">{new Date(item.startsAt).getDate()}</span><div><span className="tag">{item.category}</span><h3>{item.title}</h3><p>{formatShortDate(item.startsAt)}{item.venue ? ` · ${item.venue}` : ""}</p></div><ChevronRight size={17} /></Link>)}</div></section> : null,
    city.modules.community && previews.communityPosts.length ? <section className="dashboard-section" key="community"><div className="section-head"><div><span className="section-icon"><MessageCircle size={18} /></span><h2>Nejnovější z komunity</h2></div><Link href={`${base}/komunita`}>Otevřít komunitu <ArrowRight size={16} /></Link></div><div className="compact-list">{previews.communityPosts.map((item) => <Link className="compact-row" href={`${base}/komunita?post=${item.id}`} key={item.id}><span className="place-index">K</span><div><span className="tag">{item.category}</span><h3>{item.body}</h3><p>Zveřejněno {formatShortDate(item.createdAt)}</p></div><ChevronRight size={17} /></Link>)}</div></section> : null,
    city.modules.marketplace && previews.marketplaceListings.length ? <section className="dashboard-section" key="marketplace"><div className="section-head"><div><span className="section-icon"><ShoppingBag size={18} /></span><h2>Nejnovější z Burzy</h2></div><Link href={`${base}/burza`}>Celá Burza <ArrowRight size={16} /></Link></div><div className="compact-list">{previews.marketplaceListings.map((item) => <Link className="compact-row" href={`${base}/burza/${item.id}`} key={item.id}><span className="place-index">B</span><div><span className="tag">{price(item.priceMode, item.priceAmount)}</span><h3>{item.title}</h3><p>{item.shortDescription}</p></div><ChevronRight size={17} /></Link>)}</div></section> : null,
    city.modules.housing && previews.housingListings.length ? <section className="dashboard-section" key="housing"><div className="section-head"><div><span className="section-icon"><House size={18} /></span><h2>Bydlení</h2></div><Link href={`${base}/bydleni`}>Všechny nabídky <ArrowRight size={16} /></Link></div><div className="compact-list">{previews.housingListings.map((item) => <Link className="compact-row" href={`${base}/bydleni/${item.id}`} key={item.id}><span className="place-index">D</span><div><span className="tag">{item.listingType === "wanted" ? "Hledám" : "Nabízím"}</span><h3>{item.title}</h3><p>{item.locality} · {new Intl.NumberFormat("cs-CZ").format(item.priceMonthly)} Kč / měsíc</p></div><ChevronRight size={17} /></Link>)}</div></section> : null,
    city.modules.buddy && previews.buddyPosts.length ? <section className="dashboard-section" key="buddy"><div className="section-head"><div><span className="section-icon"><Users size={18} /></span><h2>Hledám parťáka</h2></div><Link href={`${base}/partak`}>Všechny aktivity <ArrowRight size={16} /></Link></div><div className="compact-list">{previews.buddyPosts.map((item) => <Link className="compact-row" href={`${base}/partak?post=${item.id}`} key={item.id}><span className="place-index">P</span><div><span className="tag">{item.activityType}</span><h3>{item.title}</h3><p>{formatShortDate(item.startsAt)}{item.approximateLocation ? ` · ${item.approximateLocation}` : ""}</p></div><ChevronRight size={17} /></Link>)}</div></section> : null,
  ].filter(Boolean);
  return sections.length ? <div className="dashboard-preview-grid">{sections}</div> : null;
}
