"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ArrowRight, BriefcaseBusiness, CalendarClock, CalendarDays, ChevronRight, CircleHelp, Clock3, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import { useMemo } from "react";
import { AdSlot } from "@/components/ad-slot";
import { DashboardHeading, PersonalizedDashboard } from "@/components/personalized-dashboard";
import { useAcademicCatalog } from "@/components/academic-catalog-provider";
import type { City } from "@/lib/cities";
import type { AcademicEvent, Job, Offer, Place } from "@/lib/types";
import { useStudentPreference } from "@/lib/client-preferences";
import { daysUntil, formatDayNumber, formatShortDate, formatShortMonth } from "@/lib/format";
import { resolveStudySelection } from "@/lib/universities";
import { filterAcademicEvents, filterJobs, filterOffers, filterPlaces } from "@/lib/personalization";

function Empty({ children }: { children: React.ReactNode }) { return <div className="empty-state compact-empty"><p>{children}</p></div>; }

export function CityDashboardContent({ city, events, places, offers, jobs }: { city: City; events: AcademicEvent[]; places: Place[]; offers: Offer[]; jobs: Job[] }) {
  const search = useSearchParams(); const catalog = useAcademicCatalog(); const preference = useStudentPreference(catalog);
  const explicitScope = search.has("university") || search.has("faculty") || search.has("campus");
  const selection = useMemo(() => {
    const resolved = explicitScope ? resolveStudySelection(search.get("university"), search.get("faculty"), catalog) : { universityId: preference.universityId || "", facultyId: preference.facultyId || "" };
    const university = catalog.universities.find((item) => item.id === resolved.universityId);
    const requestedCampus = explicitScope ? search.get("campus") || "" : preference.campusId || "";
    const campus = university?.campuses.find((item) => item.id === requestedCampus || item.name.toLocaleLowerCase("cs-CZ") === requestedCampus.toLocaleLowerCase("cs-CZ"));
    return { universityId: resolved.universityId || undefined, facultyId: resolved.facultyId || undefined, campus: campus?.id || campus?.name };
  }, [catalog, explicitScope, preference.campusId, preference.facultyId, preference.universityId, search]);
  const personalized = useMemo(() => ({ events: filterAcademicEvents(events, selection), places: filterPlaces(places, selection), offers: filterOffers(offers, selection), jobs: filterJobs(jobs, selection) }), [events, jobs, offers, places, selection]);
  const upcoming = personalized.events; const nextEvent = upcoming[0]; const exam = upcoming.find((event) => event.category.includes("Zkouš")); const base = `/${city.slug}`;
  function scoped(path: string) { const query = new URLSearchParams(); if (selection.universityId) query.set("university", selection.universityId); if (selection.facultyId) query.set("faculty", selection.facultyId); if (selection.campus) query.set("campus", selection.campus); return `${path}${query.size ? `?${query}` : ""}`; }
  return <div className="page-stack"><DashboardHeading city={city} selection={selection} /><PersonalizedDashboard events={personalized.events} offers={personalized.offers} jobs={personalized.jobs} city={city} selection={selection} />
    <section className="hero-grid" aria-label="Nejdůležitější přehled"><article className="countdown-card"><div className="card-kicker"><CalendarClock size={18} />{exam ? "Další zkouškové období" : "Ověřené termíny"}</div>{exam ? <><div className="countdown-number"><strong>{Math.max(0, daysUntil(exam.start))}</strong><span>dní</span></div><h2>{exam.title}</h2><p>Začíná {formatShortDate(exam.start)}</p></> : <><h2>Čekáme na ověřený termín</h2><p>Nezobrazujeme odhad ani neověřená školní data.</p></>}<Link href={scoped(`${base}/kalendar`)} className="text-link">Zobrazit kalendář <ArrowRight size={16} /></Link></article><article className="next-card"><div className="card-kicker"><Clock3 size={18} />Nejbližší termín</div>{nextEvent ? <><div className="date-tile"><strong>{formatDayNumber(nextEvent.start)}</strong><span>{formatShortMonth(nextEvent.start)}</span></div><div><span className="tag tag-blue">{nextEvent.category}</span><h2>{nextEvent.title}</h2><p>{nextEvent.faculty} · {formatShortDate(nextEvent.start)}</p></div></> : <div><h2>Zatím bez ověřených termínů</h2><p>Po úspěšné kontrole veřejných zdrojů se objeví tady.</p></div>}</article><article className="help-card"><div className="help-icon"><CircleHelp size={25} /></div><div><span className="tag tag-green">Lokální pomoc</span><h2>Nefunguje notebook nebo Wi‑Fi?</h2><p>Popište problém. Kontaktní údaje zůstanou neveřejné.</p></div><Link href="/pomoc" className="button button-light">Vyplnit poptávku <ChevronRight size={17} /></Link></article></section>
    <section className="dashboard-section"><div className="section-head"><div><span className="section-icon"><CalendarDays size={18} /></span><h2>Nejbližší termíny</h2></div><Link href={scoped(`${base}/kalendar`)}>Celý kalendář <ArrowRight size={16} /></Link></div><div className="timeline-list">{upcoming.length ? upcoming.slice(0, 4).map((event) => <article key={event.id}><time dateTime={event.start}><strong>{formatDayNumber(event.start)}</strong><span>{formatShortMonth(event.start)}</span></time><div><span className="tag">{event.category}</span><h3>{event.title}</h3><p>{event.school} · ověřeno {formatShortDate(event.lastVerifiedAt)}</p></div><ChevronRight size={18} aria-hidden="true" /></article>) : <Empty>Zatím nemáme žádné ověřené budoucí termíny.</Empty>}</div></section>
    <div className="two-column-grid"><section className="dashboard-section"><div className="section-head"><div><span className="section-icon"><Sparkles size={18} /></span><h2>Aktuální nabídky</h2></div><Link href={scoped(`${base}/nabidky`)}>Všechny <ArrowRight size={16} /></Link></div><div className="compact-list">{personalized.offers.length ? personalized.offers.slice(0, 3).map((offer) => <Link href={`${scoped(`${base}/nabidky`)}#${offer.id}`} key={offer.id} className="compact-row"><span className="offer-discount">{offer.discount}</span><div>{offer.sponsored && <small className="sponsored">SPONZOROVÁNO</small>}<h3>{offer.title}</h3><p>{offer.partner} · do {formatShortDate(offer.validTo)}</p></div><ChevronRight size={17} /></Link>) : <Empty>Zatím nemáme ověřené nabídky partnerů.</Empty>}</div></section><section className="dashboard-section"><div className="section-head"><div><span className="section-icon"><MapPin size={18} /></span><h2>Doporučená místa</h2></div><Link href={scoped(`${base}/mista`)}>Na mapu <ArrowRight size={16} /></Link></div><div className="compact-list">{personalized.places.length ? personalized.places.slice(0, 3).map((place) => <Link href={`${scoped(`${base}/mista`)}#${place.id}`} key={place.id} className="compact-row"><span className="place-index">{place.category.slice(0, 1)}</span><div><span className="tag">{place.category}</span><h3>{place.name}</h3><p>{place.address}</p></div><ChevronRight size={17} /></Link>) : <Empty>Zatím nemáme ověřená místa.</Empty>}</div></section></div>
    <section className="dashboard-section"><div className="section-head"><div><span className="section-icon"><BriefcaseBusiness size={18} /></span><h2>Nejnovější brigády</h2></div><Link href={scoped(`${base}/brigady`)}>Všechny brigády <ArrowRight size={16} /></Link></div><div className="jobs-preview">{personalized.jobs.length ? personalized.jobs.slice(0, 3).map((job) => <Link key={job.id} href={`${scoped(`${base}/brigady`)}#${job.id}`}><div>{job.featured && <small className="sponsored">ZVÝRAZNĚNO</small>}<h3>{job.title}</h3><p>{job.company}</p></div><dl><div><dt>Odměna</dt><dd>{job.reward} Kč/h</dd></div><div><dt>Rozsah</dt><dd>{job.workload}</dd></div></dl><span><MapPin size={15} />{job.location}</span></Link>) : <Empty>Zatím nemáme ověřené brigády. Firmy je mohou poslat ke schválení.</Empty>}</div></section><AdSlot /><div className="trust-note"><ShieldCheck size={18} /><p>Kontaktní údaje z poptávek nejsou veřejné. Veřejná data publikujeme až po ověření zdroje nebo schválení administrátorem.</p></div>
  </div>;
}
