"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect,useState } from "react";
import { assetPath,coloringAssets,completion,type Drawing,type Region } from "@/lib/coloring";
import { cachedAsset,readLocalDrawing } from "@/lib/coloring-local";
type Progress={id:string;percentage:number;completed:boolean;updatedAt:string;started:boolean};
export function ColoringGallery({city,owner,compact=false}:{city:string;owner:string;compact?:boolean}){
 const [items,setItems]=useState<Progress[]>([]),[filter,setFilter]=useState("all"),[error,setError]=useState("");
 useEffect(()=>{let cancelled=false;async function load(){let rows:Progress[]=[];
  if(owner!=="guest")try{const response=await fetch('/api/coloring',{cache:'no-store'});if(!response.ok)throw Error();const data=await response.json();rows=data.items.map((r:{coloring_id:string;percentage:number;completed:boolean;updated_at:string;drawing:Drawing})=>({id:r.coloring_id,percentage:r.percentage,completed:r.completed,updatedAt:r.updated_at,started:!!(Object.keys(r.drawing.colors).length||r.drawing.strokes.length)}));}catch{if(!cancelled)setError("Cloudový postup není dostupný. Zobrazuji místní kresby.");}
  for(const asset of coloringAssets){const local=readLocalDrawing(owner,asset.id);if(local&&(local.dirty||!rows.some(r=>r.id===asset.id))){let percentage=0;try{const regions=JSON.parse(await (await cachedAsset(assetPath(asset.id,"regions.json"))).text()) as Region[];percentage=completion(local.drawing,regions);}catch{percentage=local.drawing.completed?100:0;}rows=rows.filter(r=>r.id!==asset.id);rows.push({id:asset.id,percentage,completed:local.drawing.completed,updatedAt:local.updatedAt,started:!!(Object.keys(local.drawing.colors).length||local.drawing.strokes.length)});}}
  if(!cancelled)setItems(rows);}
 void load();return()=>{cancelled=true};},[owner]);
 const assets=compact?coloringAssets.filter(a=>items.some(r=>r.id===a.id&&r.started&&!r.completed)).sort((a,b)=>(items.find(r=>r.id===b.id)?.updatedAt||"").localeCompare(items.find(r=>r.id===a.id)?.updatedAt||"")).slice(0,3):coloringAssets.filter(a=>{const p=items.find(r=>r.id===a.id);return filter==="all"||filter==="done"&&p?.completed||filter==="started"&&p&&!p.completed&&p.started;});
 return <section className="coloring-section" aria-label={compact?"Moje omalovánky":"Antistresové omalovánky"}>{compact?<h2><Link href={`/${city}/odpocinek/omalovanky`}>Moje omalovánky</Link></h2>:<><Link href={`/${city}/odpocinek`}>← Odpočinek</Link><h1>Antistresové omalovánky</h1><p>Antistresové omalovánky. Vyberte obrázek a na chvíli vypněte.</p>{owner==="guest"&&<p className="muted">Postup zůstane na tomto zařízení. <Link href={`/${city}/nastaveni`}>Přihlášení</Link> umožní pokračovat i jinde.</p>}<div className="coloring-tabs" aria-label="Stav omalovánek">{[["all","Všechny"],["started","Rozpracované"],["done","Dokončené"]].map(([v,label])=><button type="button" key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)}>{label}</button>)}</div></>}
 {error&&<p role="status">{error}</p>}<div className="coloring-gallery">{assets.map(asset=>{const p=items.find(r=>r.id===asset.id);return <article className="coloring-card" key={asset.id}><Link href={`/${city}/odpocinek/omalovanky/${asset.id}`}><Image src={assetPath(asset.id,"preview.webp")} alt={asset.alt} width={256} height={341} unoptimized /></Link><div><h2>{asset.title}</h2><p>{asset.collection} · {asset.difficulty}</p><p>{p?.completed?"Dokončená":p?.started?"Rozpracovaná":"Nová"} · {p?.percentage||0} %</p>{compact&&p&&<p>Upraveno {new Date(p.updatedAt).toLocaleDateString("cs-CZ")}</p>}<Link className="button button-primary" href={`/${city}/odpocinek/omalovanky/${asset.id}`}>{p?.started||p?.completed?"Pokračovat":"Vybarvovat"}</Link></div></article>;})}</div>{!assets.length&&<p>V této kategorii zatím nemáte žádnou omalovánku.</p>}{compact&&<Link href={`/${city}/odpocinek/omalovanky`}>Všechny omalovánky</Link>}</section>;
}
