"use client";
import Link from "next/link";
import { useCallback,useEffect,useRef,useState } from "react";
import { ArrowLeft,Download,Eraser,Hand,Maximize,Paintbrush,PaintBucket,Pipette,Redo2,RotateCcw,Undo2,ZoomIn,ZoomOut } from "lucide-react";
import { assetPath,completion,emptyDrawing,historyChange,historyRedo,historyUndo,regionAt,simplifyPoints,type ColoringAsset,type Drawing,type History,type Point,type Region,type Stroke } from "@/lib/coloring";
import { cachedAsset } from "@/lib/coloring-local";
import { useColoringProgress } from "@/components/coloring-progress";
import { useModalDialog } from "@/lib/use-modal-dialog";
import { coloringRenderer } from "@/lib/coloring-renderer";
type Tool="fill"|"brush"|"erase"|"pan"|"pick";
type Assets={lines:HTMLImageElement;mask:Uint8ClampedArray;width:number;height:number;regions:Region[]};
const palette=["#6366f1","#a78bfa","#ec4899","#f97316","#facc15","#22c55e","#14b8a6","#38bdf8","#a16207","#ffffff"];
export function ColoringEditor({city,asset,owner}:{city:string;asset:ColoringAsset;owner:string}){
 const progress=useColoringProgress(asset.id,owner),[assets,setAssets]=useState<Assets|null>(null),[error,setError]=useState(""),[tool,setTool]=useState<Tool>("fill"),[color,setColor]=useState(palette[0]),[width,setWidth]=useState(14),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[reset,setReset]=useState(false),[region,setRegion]=useState(1);
 const canvas=useRef<HTMLCanvasElement>(null),stage=useRef<HTMLDivElement>(null),history=useRef<History>({past:[],present:emptyDrawing(),future:[]}),[historyCount,setHistoryCount]=useState({past:0,future:0});
 const stroke=useRef<Stroke|null>(null),pointers=useRef(new Map<number,{x:number;y:number}>()),gesture=useRef<{distance:number;zoom:number;x:number;y:number;pan:{x:number;y:number}}|null>(null),drag=useRef<{x:number;y:number;pan:{x:number;y:number}}|null>(null),lastPen=useRef(0),frame=useRef<number>(0);
 const renderer=useRef<ReturnType<typeof coloringRenderer>|null>(null),pendingFill=useRef<number|null>(null);
 const [full,setFull]=useState(false);
 const closeFull=()=>setFull(false),fullDialogRef=useModalDialog<HTMLDivElement>(full&&!reset,closeFull);
 const closeReset=()=>setReset(false),dialog=useModalDialog<HTMLDivElement>(reset,closeReset);
 useEffect(()=>{let cancelled=false;const urls:string[]=[];async function load(){try{const [lineBlob,maskBlob,json]=await Promise.all([cachedAsset(assetPath(asset.id,"lines.png")),cachedAsset(assetPath(asset.id,"mask.png")),cachedAsset(assetPath(asset.id,"regions.json"))]);const image=async(blob:Blob)=>{const url=URL.createObjectURL(blob);urls.push(url);const img=new Image();img.src=url;await img.decode();return img;};const [lines,mask]=await Promise.all([image(lineBlob),image(maskBlob)]);const c=document.createElement('canvas');c.width=mask.width;c.height=mask.height;const ctx=c.getContext('2d')!;ctx.drawImage(mask,0,0);if(!cancelled)setAssets({lines,mask:ctx.getImageData(0,0,c.width,c.height).data,width:c.width,height:c.height,regions:JSON.parse(await json.text())});}catch{if(!cancelled)setError("Obrázek nelze načíst. Připojte se k internetu a zkuste obnovit stránku.");}}void load();return()=>{cancelled=true;urls.forEach(URL.revokeObjectURL);cancelAnimationFrame(frame.current);};},[asset.id]);
 useEffect(()=>{renderer.current=assets?coloringRenderer(assets):null;},[assets]);
 const render=useCallback((drawing:Drawing,active:Stroke|null=null)=>{if(assets&&canvas.current)renderer.current?.(canvas.current,drawing,active);},[assets]);
 useEffect(()=>{render(progress.value.drawing);history.current.present=progress.value.drawing;},[progress.value.drawing,render]);
 function commit(drawing:Drawing){if(!progress.ready||!assets)return;if(progress.change(drawing)){history.current=historyChange(history.current,drawing);setHistoryCount({past:history.current.past.length,future:0});}}
 function step(back:boolean){const next=back?historyUndo(history.current):historyRedo(history.current);if(progress.change(next.present)){history.current=next;setHistoryCount({past:next.past.length,future:next.future.length});}}
 function point(e:{clientX:number;clientY:number;pressure?:number}):Point{const r=canvas.current!.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height)),e.pressure&&e.pressure>0?e.pressure:.5];}
 function down(e:React.PointerEvent<HTMLCanvasElement>){if(!assets||!progress.ready)return;if(e.pointerType==="pen")lastPen.current=Date.now();if(e.pointerType==="touch"&&Date.now()-lastPen.current<800)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===2){stroke.current=null;render(progress.value.drawing);const [a,b]=[...pointers.current.values()];gesture.current={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom,x:(a.x+b.x)/2,y:(a.y+b.y)/2,pan};return;}if(pointers.current.size>1)return;
  if(tool==="pan"){drag.current={x:e.clientX,y:e.clientY,pan};return;}const p=point(e),id=regionAt(assets.mask,assets.width,assets.height,p[0]*assets.width,p[1]*assets.height);
  if(tool==="fill"&&id){pendingFill.current=id;setRegion(id);}
  else if(tool==="pick"){const ctx=canvas.current!.getContext('2d')!,pixel=ctx.getImageData(Math.min(assets.width-1,Math.floor(p[0]*assets.width)),Math.min(assets.height-1,Math.floor(p[1]*assets.height)),1,1).data;setColor('#'+[...pixel.slice(0,3)].map(v=>v.toString(16).padStart(2,'0')).join(''));}
  else if(tool==="brush"||tool==="erase"){stroke.current={color,width,erase:tool==="erase",points:[p]};render(progress.value.drawing,stroke.current);}}
 function move(e:React.PointerEvent<HTMLCanvasElement>){if(!pointers.current.has(e.pointerId))return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(gesture.current&&pointers.current.size===2){const [a,b]=[...pointers.current.values()],g=gesture.current;setZoom(Math.max(1,Math.min(4,g.zoom*Math.hypot(a.x-b.x,a.y-b.y)/g.distance)));setPan({x:g.pan.x+(a.x+b.x)/2-g.x,y:g.pan.y+(a.y+b.y)/2-g.y});return;}if(drag.current){setPan({x:drag.current.pan.x+e.clientX-drag.current.x,y:drag.current.pan.y+e.clientY-drag.current.y});return;}if(stroke.current){if(stroke.current.points.length<4000)stroke.current.points.push(point(e));cancelAnimationFrame(frame.current);frame.current=requestAnimationFrame(()=>render(progress.value.drawing,stroke.current));}}
 function up(e:React.PointerEvent<HTMLCanvasElement>){pointers.current.delete(e.pointerId);if(pendingFill.current&&!gesture.current){commit({...progress.value.drawing,completed:false,colors:{...progress.value.drawing.colors,[pendingFill.current]:color}});}pendingFill.current=null;if(stroke.current){const s={...stroke.current,points:simplifyPoints(stroke.current.points)};stroke.current=null;cancelAnimationFrame(frame.current);commit({...progress.value.drawing,completed:false,strokes:[...progress.value.drawing.strokes,s]});}if(pointers.current.size<2)gesture.current=null;drag.current=null;}
 useEffect(()=>{const el=stage.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();setZoom(z=>Math.max(1,Math.min(4,z*Math.exp(-e.deltaY*.0015))));};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[assets]);
 function exportPng(){if(!canvas.current)return;canvas.current.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`studenthub-${asset.id}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');}
 const toolbar=[{id:"fill",label:"Vyplnit plochu",Icon:PaintBucket},{id:"brush",label:"Štětec",Icon:Paintbrush},{id:"erase",label:"Guma (tahy štětce)",Icon:Eraser},{id:"pick",label:"Kapátko",Icon:Pipette},{id:"pan",label:"Posouvat plátno",Icon:Hand}] as const;
 return <div className={`coloring-editor${full?" coloring-fullscreen":""}`} ref={fullDialogRef} role={full&&!reset?"dialog":undefined} aria-modal={full&&!reset||undefined} aria-label={full?asset.title:undefined}><Link href={`/${city}/odpocinek`} onClick={()=>void progress.retry()}><ArrowLeft size={16}/> Všechny omalovánky</Link>{full&&<button onClick={closeFull}>Ukončit celou obrazovku</button>}<h1>{asset.title}</h1><p className="coloring-status" role="status">{progress.status} {assets&&`· ${completion(progress.value.drawing,assets.regions)} %`}</p>{progress.status.includes("nezdařilo")&&<button onClick={()=>void progress.retry()}>Zkusit uložit znovu</button>}
 {progress.conflict&&<div className="coloring-notice" role="alert"><p>Na jiném zařízení je jiná verze. Obě kresby zatím zůstávají zachované. Před nahrazením můžete místní kresbu exportovat.</p><button onClick={()=>progress.resolve(true)}>Použít kresbu z profilu</button><button onClick={()=>progress.resolve(false)}>Nahradit ji místní kresbou</button><button onClick={exportPng}>Exportovat místní PNG</button></div>}
 {progress.ready&&progress.guest&&<div className="coloring-notice"><p>Na zařízení je také rozehraná anonymní kresba. Přenesení nahradí nyní otevřenou kresbu až po vašem potvrzení.</p><button onClick={progress.importGuest}>Přiřadit místní kresbu k profilu</button><button onClick={progress.dismissGuest}>Nepřenášet</button></div>}
 <div className="coloring-tools" role="group" aria-label="Nástroje">
 {toolbar.map(({id,label,Icon})=><button key={id} aria-label={label} title={label} aria-pressed={tool===id} onClick={()=>setTool(id)}><Icon size={21}/></button>)}
 <label>Tloušťka <input aria-label="Tloušťka štětce" type="range" min={1} max={70} value={width} onChange={e=>setWidth(Number(e.target.value))}/></label>
 <button disabled={!historyCount.past} aria-label="Krok zpět" title="Krok zpět" onClick={()=>step(true)}><Undo2 size={20}/></button>
 <button disabled={!historyCount.future} aria-label="Krok vpřed" title="Krok vpřed" onClick={()=>step(false)}><Redo2 size={20}/></button>
 <button aria-label="Oddálit" title="Oddálit" onClick={()=>setZoom(z=>Math.max(1,z-.25))}><ZoomOut size={20}/></button>
 <button aria-label="Přiblížit" title="Přiblížit" onClick={()=>setZoom(z=>Math.min(4,z+.25))}><ZoomIn size={20}/></button>
 <button onClick={()=>{setZoom(1);setPan({x:0,y:0});}}>{Math.round(zoom*100)} %</button>
 <button aria-label="Celá obrazovka" title="Celá obrazovka" aria-pressed={full} onClick={()=>setFull(v=>!v)}><Maximize size={20}/></button>
 <button aria-label="Reset omalovánky" title="Reset omalovánky" onClick={()=>setReset(true)}><RotateCcw size={20}/></button>
 <button aria-label="Exportovat PNG" title="Exportovat PNG" disabled={!assets} onClick={exportPng}><Download size={20}/></button></div>
 <div className="coloring-palette" aria-label="Paleta barev">{palette.map(c=><button key={c} style={{background:c}} aria-label={`Barva ${c}`} aria-pressed={color===c} title={c} onClick={()=>setColor(c)}/>)}<label>Vlastní barva <input aria-label="Vlastní barva" type="color" value={color} onChange={e=>setColor(e.target.value)}/></label></div>
 {error&&<p role="alert">{error}</p>}<div ref={stage} className="coloring-stage">{!assets?<p role="status">{error?"Obrázek není dostupný.":"Připravuji plátno…"}</p>:<canvas ref={canvas} aria-label={asset.alt} role="img" tabIndex={0} style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={e=>{stroke.current=null;up(e);render(progress.value.drawing);}} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();step(!e.shiftKey);}if(e.key==='Escape'){setZoom(1);setPan({x:0,y:0});}}}/> }</div>
 {assets&&<div className="coloring-keyboard"><label>Oblast pro klávesnici <select aria-label="Oblast omalovánky" value={region} onChange={e=>setRegion(Number(e.target.value))}>{assets.regions.map(r=><option key={r.id} value={r.id}>Oblast {r.id}</option>)}</select></label><button onClick={()=>commit({...progress.value.drawing,completed:false,colors:{...progress.value.drawing.colors,[region]:color}})}>Vyplnit vybranou oblast</button><label><input type="checkbox" checked={progress.value.drawing.completed} onChange={e=>commit({...progress.value.drawing,completed:e.target.checked})}/> Označit jako dokončenou</label></div>}
 <p className="muted">Klikněte na uzavřenou plochu nebo kreslete štětcem. Dva prsty přiblíží a posunou obrázek. Guma maže tahy; plochu vyčistíte bílou barvou.</p>
 {reset&&<div className="coloring-dialog-layer" data-modal-layer onClick={closeReset}><div className="coloring-dialog" ref={dialog} role="dialog" aria-modal="true" aria-labelledby="reset-coloring-title" tabIndex={-1} onClick={e=>e.stopPropagation()}><h2 id="reset-coloring-title">Vymazat tuto omalovánku?</h2><p>Vymažou se barvy a tahy tohoto obrázku. Ostatní kresby zůstanou.</p><button data-autofocus onClick={closeReset}>Zrušit</button><button onClick={()=>{commit(emptyDrawing());closeReset();}}>Vymazat</button></div></div>}</div>;
}
