"use client";

import Link from "next/link";
import { CheckCircle2, Loader2, Save, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import type { CommunityEvent, CommunityEventCategory } from "@/lib/types";

type Values = { title: string; category: CommunityEventCategory; startsAt: string; endsAt: string; venue: string; description: string; isFree: boolean; priceAmount: string; eventUrl: string };
function localValue(value?: string) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }

export function CommunityEventManager({ eventId }: { eventId: string }) {
  const [token, setToken] = useState(""); const [item, setItem] = useState<CommunityEvent | null>(null); const [status, setStatus] = useState<"loading" | "ready" | "error" | "deleted">("loading"); const [message, setMessage] = useState("");
  const { register, handleSubmit, reset, control, formState: { isSubmitting } } = useForm<Values>(); const free = useWatch({ control, name: "isFree" });
  useEffect(() => { const value = new URLSearchParams(window.location.hash.slice(1)).get("token") || ""; setToken(value); window.history.replaceState(null, "", `${window.location.pathname}${window.location.search}`); if (!eventId || !value) { setStatus("error"); setMessage("Odkaz pro správu není úplný."); return; } void (async () => { const response = await fetch(`/api/community-events/${encodeURIComponent(eventId)}`, { headers: { "x-management-token": value }, cache: "no-store" }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setStatus("error"); setMessage(payload.message || "Odkaz pro správu není platný."); return; } const event = payload.item as CommunityEvent; setItem(event); reset({ title: event.title, category: event.category, startsAt: localValue(event.startsAt), endsAt: localValue(event.endsAt), venue: event.venue, description: event.description, isFree: event.isFree, priceAmount: event.priceAmount == null ? "" : String(event.priceAmount), eventUrl: event.eventUrl || "" }); setStatus("ready"); })(); }, [eventId, reset]);
  async function save(values: Values) { setMessage(""); const response = await fetch(`/api/community-events/${encodeURIComponent(eventId)}`, { method: "PATCH", headers: { "content-type": "application/json", "x-management-token": token }, body: JSON.stringify({ ...values, startsAt: new Date(values.startsAt).toISOString(), endsAt: values.endsAt ? new Date(values.endsAt).toISOString() : "", priceAmount: values.priceAmount ? Number(values.priceAmount) : undefined }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setMessage(payload.message || "Změny se nepodařilo uložit."); return; } setItem(payload.item); setMessage("Akce byla upravena."); }
  async function remove() { if (!window.confirm("Opravdu chcete akci odstranit? Tento krok nelze vrátit.")) return; const response = await fetch(`/api/community-events/${encodeURIComponent(eventId)}`, { method: "DELETE", headers: { "x-management-token": token } }); if (!response.ok) { const payload = await response.json().catch(() => ({})); setMessage(payload.message || "Akci se nepodařilo odstranit."); return; } setStatus("deleted"); }
  return <div className="page-stack settings-page"><div><span className="eyebrow">Soukromý odkaz autora</span><h1>Správa komunitní akce</h1><p>StudentHub účet nepotřebujete. Přístup chrání jednorázově vydaný neveřejný odkaz.</p></div>{status === "loading" && <div className="settings-card"><Loader2 className="spin" /><p>Ověřuji odkaz…</p></div>}{status === "error" && <div className="error-state" role="alert">{message}</div>}{status === "deleted" && <div className="success-state"><CheckCircle2 size={32} /><h2>Akce byla odstraněna</h2><Link className="button button-primary" href="/brno/kalendar?view=community">Zpět na komunitní akce</Link></div>}{status === "ready" && item && <form className="settings-card" onSubmit={handleSubmit(save)}><div className="form-grid"><label className="form-span"><span>Název</span><input required minLength={4} maxLength={140} {...register("title")} /></label><label><span>Kategorie</span><select {...register("category")}><option>Kultura</option><option>Sport</option><option>Studium</option><option>Zábava</option><option>Ostatní</option></select></label><label><span>Začátek</span><input type="datetime-local" required {...register("startsAt")} /></label><label><span>Konec</span><input type="datetime-local" {...register("endsAt")} /></label><label><span>Veřejné místo</span><input required {...register("venue")} /></label><label className="form-span"><span>Popis</span><textarea required minLength={20} rows={6} {...register("description")} /></label><label><span>Odkaz</span><input type="url" {...register("eventUrl")} /></label><label><span>Cena v Kč</span><input type="number" disabled={free} {...register("priceAmount")} /></label><label className="checkbox-field"><input type="checkbox" {...register("isFree")} /><span>Akce je zdarma</span></label></div>{message && <div className={message.includes("upravena") ? "success-message" : "error-state"} role="status">{message}</div>}<div className="form-footer"><button className="button button-secondary" type="button" onClick={remove}><Trash2 size={17} />Odstranit akci</button><button className="button button-primary" disabled={isSubmitting}><Save size={17} />{isSubmitting ? "Ukládám…" : "Uložit změny"}</button></div></form>}</div>;
}
