"use client";

import { CheckCircle2, Flag, Loader2, MapPin, Pencil, Trash2, Wrench } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

type HelpItem = { id: string; publicTitle: string; publicAlias?: string; serviceType: string; description: string; location: string; preferredDate: string; moderationStatus?: string; createdAt?: string };
const labels: Record<string, string> = { "windows-linux": "Windows / Linux", cleaning: "Čištění notebooku", "ssd-ram": "SSD / RAM", backup: "Zálohování", "wifi-printer": "Wi‑Fi / tiskárna", "device-choice": "Výběr zařízení", other: "Jiný problém" };

export function HelpRequestsExplorer({ mine = false }: { mine?: boolean }) {
  const [items, setItems] = useState<HelpItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [type, setType] = useState(""); const [location, setLocation] = useState("");
  const load = useCallback(async () => { setLoading(true); const response = await fetch(`/api/service-requests?scope=${mine ? "mine" : "public"}`, { cache: "no-store" }); if (!response.ok) { setError("Žádosti se nepodařilo načíst."); setLoading(false); return; } setItems((await response.json()).items); setLoading(false); }, [mine]);
  useEffect(() => { load(); }, [load]);
  const filtered = useMemo(() => items.filter((item) => (!type || item.serviceType === type) && (!location || item.location.toLocaleLowerCase("cs-CZ").includes(location.toLocaleLowerCase("cs-CZ")))), [items, location, type]);
  async function remove(id: string) { if (!confirm("Opravdu chcete vlastní žádost smazat?")) return; const response = await fetch(`/api/service-requests/${id}`, { method: "DELETE" }); if (!response.ok) return setError("Žádost se nepodařilo smazat."); setNotice("Žádost byla smazána."); await load(); }
  async function edit(item: HelpItem) { const publicTitle = prompt("Veřejný název", item.publicTitle); if (!publicTitle) return; const description = prompt("Popis bez kontaktních údajů", item.description); if (!description) return; const locationValue = prompt("Přibližná lokalita", item.location); if (!locationValue) return; const response = await fetch(`/api/service-requests/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ publicTitle, description, location: locationValue }) }); if (!response.ok) return setError("Změnu se nepodařilo uložit."); setNotice("Změna je uložená a veřejná."); await load(); }
  async function report(id: string) { const response = await fetch("/api/reports", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ targetType: "service_request", targetId: id, reason: "other", detail: "Hlášení z veřejného seznamu", cityId: "brno" }) }); setNotice(response.ok ? "Hlášení jsme přijali." : "Hlášení se nepodařilo odeslat."); }
  return <section className="community-section"><div className="filter-panel community-filters"><label><span>Typ pomoci</span><select value={type} onChange={(event) => setType(event.target.value)}><option value="">Všechny typy</option>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label><span>Lokalita</span><input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Např. Žabovřesky" /></label></div>{notice && <p className="success-message" role="status"><CheckCircle2 size={16} />{notice}</p>}{error && <p className="error-state" role="alert">{error}</p>}{loading ? <div className="loading-inline"><Loader2 className="spin" />Načítám…</div> : filtered.length === 0 ? <div className="empty-state"><Wrench size={28} /><h2>{mine ? "Nemáte žádnou žádost" : "Zatím žádná veřejná žádost"}</h2><p>{mine ? "Novou žádost vytvoříte na stránce technické pomoci." : "Nová bezpečně ověřená žádost se po odeslání zobrazí automaticky."}</p></div> : <div className="community-grid">{filtered.map((item) => <article className="community-card" key={item.id}><div className="result-labels"><span className="tag">{labels[item.serviceType] || item.serviceType}</span>{mine && <span className={`status-pill status-${item.moderationStatus}`}>{item.moderationStatus === "approved" ? "zveřejněno" : item.moderationStatus === "rejected" ? "zamítnuto" : item.moderationStatus === "hidden" ? "skryto" : "kontrola"}</span>}</div><h2>{item.publicTitle}</h2>{item.publicAlias && <small>Vložil/a: {item.publicAlias}</small>}<p>{item.description}</p><span className="community-location"><MapPin size={15} />{item.location}</span><small>Preferovaný termín: {item.preferredDate}</small><div className="card-actions">{mine ? <><button className="button button-secondary" onClick={() => edit(item)}><Pencil size={15} />Upravit</button><button className="button button-secondary" onClick={() => remove(item.id)}><Trash2 size={15} />Smazat</button></> : <button className="text-link" onClick={() => report(item.id)}><Flag size={14} />Nahlásit</button>}</div></article>)}</div>}</section>;
}
