"use client";

import Image from "next/image";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowDown, ArrowUp, ImagePlus, Loader2, ShieldCheck, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { z } from "zod";
import { housingListingSchema } from "@/lib/housing-schemas";
import { housingCategories, housingFeatures, housingLabels, housingLifestylePreferences, housingListingTypes, housingStayLengths } from "@/lib/housing-types";
import { LegalNotice } from "@/components/legal-links";

type Values=z.input<typeof housingListingSchema>;
export function HousingListingForm(){
  const[files,setFiles]=useState<File[]>([]);const[photoError,setPhotoError]=useState("");const[serverError,setServerError]=useState("");const[progress,setProgress]=useState(0);const[done,setDone]=useState<{href:string;message:string;status:string}|null>(null);const previews=useMemo(()=>files.map((file)=>({file,url:URL.createObjectURL(file)})),[files]);useEffect(()=>()=>previews.forEach((value)=>URL.revokeObjectURL(value.url)),[previews]);
  const{register,control,handleSubmit,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(housingListingSchema),defaultValues:{listingType:"offer",category:"private_room",stayLength:"6_12_months",cityId:"brno",utilitiesIncluded:false,furnished:true,features:[],lifestylePreferences:[],company:"",availableFrom:new Date().toISOString().slice(0,10)}});const type=useWatch({control,name:"listingType"});const included=useWatch({control,name:"utilitiesIncluded"});
  function addPhotos(event:React.ChangeEvent<HTMLInputElement>){const next=Array.from(event.target.files||[]);const combined=[...files,...next];if(combined.length>8){setPhotoError("Lze přidat nejvýše osm fotografií.");return;}if(combined.some((file)=>file.size>5*1024*1024)){setPhotoError("Každá fotografie může mít nejvýše 5 MB.");return;}setFiles(combined);setPhotoError("");event.target.value="";}function move(index:number,direction:-1|1){setFiles((current)=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next;});}
  async function submit(values:Values){setServerError("");if(type==="offer"&&files.length===0){setPhotoError("Nabídka musí mít alespoň jednu fotografii.");return;}setProgress(10);const form=new FormData();for(const[key,value]of Object.entries(values)){if(Array.isArray(value))value.forEach((entry)=>form.append(key,String(entry)));else if(value!==undefined&&value!==null)form.append(key,String(value));}files.forEach((file)=>form.append("photos",file));setProgress(35);const response=await fetch("/api/housing/listings",{method:"POST",body:form});setProgress(85);const payload=await response.json().catch(()=>({}));if(!response.ok){setServerError(payload.message||"Inzerát se nepodařilo uložit.");setProgress(0);return;}setProgress(100);setDone({href:payload.href,message:payload.message,status:payload.status});}
  if(done)return <div className="success-state housing-form-success"><ShieldCheck size={42}/><h2>{done.status==="active"?"Inzerát byl zveřejněn":"Inzerát vyžaduje kontrolu"}</h2><p>{done.message}</p>{done.status==="active"&&<a className="button button-primary" href={done.href}>Otevřít inzerát</a>}<a className="button button-secondary" href="/brno/bydleni/moje">Moje inzeráty</a></div>;
  const error=(name:keyof Values)=>errors[name]?.message?.toString();
  return <form className="housing-form" onSubmit={handleSubmit(submit)} noValidate><fieldset><legend>Základní údaje</legend><div className="form-grid"><label><span>Typ inzerátu</span><select {...register("listingType")}>{housingListingTypes.map((value)=><option value={value} key={value}>{housingLabels.type[value]}</option>)}</select></label><label><span>Kategorie</span><select {...register("category")}>{housingCategories.map((value)=><option value={value} key={value}>{housingLabels.category[value]}</option>)}</select></label><label className="form-span"><span>Název</span><input maxLength={120} {...register("title")}/>{error("title")&&<small className="field-error">{error("title")}</small>}</label><label><span>Město</span><input value="Brno" disabled/><input type="hidden" {...register("cityId")}/></label><label><span>Městská část nebo přibližná lokalita</span><input placeholder="např. Královo Pole" maxLength={100} {...register("locality")}/>{error("locality")&&<small className="field-error">{error("locality")}</small>}</label><label><span>Aktuální od</span><input type="date" {...register("availableFrom")}/></label><label><span>Předpokládaná délka</span><select {...register("stayLength")}>{housingStayLengths.map((value)=><option value={value} key={value}>{housingLabels.stay[value]}</option>)}</select></label><label className="form-span"><span>Stručný popis</span><input maxLength={240} {...register("shortDescription")}/>{error("shortDescription")&&<small className="field-error">{error("shortDescription")}</small>}</label><label className="form-span"><span>Podrobný popis</span><textarea rows={8} maxLength={4000} {...register("description")}/>{error("description")&&<small className="field-error">{error("description")}</small>}</label></div></fieldset>
    <fieldset><legend>Cena a podmínky</legend><div className="form-grid"><label><span>{type==="offer"?"Měsíční cena":"Maximální měsíční rozpočet"} v Kč</span><input type="number" min="0" max="200000" {...register("priceMonthly")}/>{error("priceMonthly")&&<small className="field-error">{error("priceMonthly")}</small>}</label><label className="check-row housing-check"><input type="checkbox" {...register("utilitiesIncluded")}/><span>{type==="offer"?"Energie jsou v ceně":"Rozpočet zahrnuje energie"}</span></label>{!included&&<label><span>Energie v Kč / měsíc</span><input type="number" min="0" {...register("utilitiesAmount")}/>{error("utilitiesAmount")&&<small className="field-error">{error("utilitiesAmount")}</small>}</label>}{type==="offer"?<><label><span>Vratná kauce v Kč</span><input type="number" min="0" {...register("depositAmount")}/></label><label><span>Počet volných míst</span><input type="number" min="1" max="20" {...register("availableSpots")}/></label><label><span>Kolik lidí už zde žije</span><input type="number" min="0" max="30" {...register("currentOccupants")}/></label><label><span>Vybavení</span><select {...register("furnished")}><option value="true">Vybavené</option><option value="false">Nevybavené</option></select></label><label className="form-span"><span>Dostupnost MHD</span><input maxLength={160} placeholder="např. 4 minuty na tramvaj" {...register("transitAccess")}/></label></>:<label><span>Počet osob</span><input type="number" min="1" max="10" {...register("wantedPersonCount")}/>{error("wantedPersonCount")&&<small className="field-error">{error("wantedPersonCount")}</small>}</label>}</div></fieldset>
    <fieldset><legend>{type==="offer"?"Vlastnosti bydlení":"Preference domácnosti"}</legend><div className="housing-options">{type==="offer"?housingFeatures.map((value)=><label className="check-row" key={value}><input type="checkbox" value={value} {...register("features")}/><span>{housingLabels.feature[value]}</span></label>):housingLifestylePreferences.map((value)=><label className="check-row" key={value}><input type="checkbox" value={value} {...register("lifestylePreferences")}/><span>{housingLabels.lifestyle[value]}</span></label>)}</div></fieldset>
    {type==="offer"&&<fieldset><legend>Fotografie (1–8)</legend><p className="field-help">JPEG, PNG nebo WebP do 5 MB. Server odstraní metadata včetně případné GPS polohy a uloží optimalizovaný WebP.</p><label className="housing-photo-picker"><ImagePlus size={20}/><span>Vybrat fotografie</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={addPhotos}/></label>{photoError&&<p className="field-error" role="alert">{photoError}</p>}<div className="housing-photo-previews">{previews.map(({file,url},index)=><figure key={`${file.name}-${file.lastModified}-${index}`}><span><Image src={url} alt={`Náhled fotografie ${index+1}`} fill unoptimized/></span><figcaption>{index+1}. {file.name}</figcaption><div><button type="button" aria-label="Posunout fotografii doleva" onClick={()=>move(index,-1)} disabled={index===0}><ArrowUp size={15}/></button><button type="button" aria-label="Posunout fotografii doprava" onClick={()=>move(index,1)} disabled={index===files.length-1}><ArrowDown size={15}/></button><button type="button" aria-label="Odebrat fotografii" onClick={()=>setFiles((current)=>current.filter((_,value)=>value!==index))}><Trash2 size={15}/></button></div></figure>)}</div></fieldset>}
    <label className="hp-field" aria-hidden="true"><span>Firma</span><input tabIndex={-1} autoComplete="off" {...register("company")}/></label><aside className="housing-safety"><strong>Nezveřejňujte kontakt ani přesnou adresu</strong><p>E-mail a telefon zůstanou v účtu. Zájemci vám napíšou přes soukromý chat StudentHubu. Nabídky s kontaktem, externím odkazem nebo požadavkem na platbu předem čekají na kontrolu.</p></aside>{progress>0&&progress<100&&<div className="upload-progress" role="status"><span style={{width:`${progress}%`}}/><p>Nahrávám a bezpečně zpracovávám fotografie… {progress} %</p></div>}{serverError&&<div className="error-state" role="alert">{serverError}</div>}<LegalNotice/><div className="form-footer"><a className="button button-secondary" href="/brno/bydleni">Zrušit</a><button className="button button-primary" disabled={isSubmitting}>{isSubmitting?<><Loader2 className="spin" size={17}/>Ukládám…</>:"Přidat inzerát"}</button></div></form>;
}
