"use client";

import Image from "next/image";
import Link from "next/link";
import { Building2, CalendarDays, Filter, House, MapPin, Plus, RotateCcw, Search, Users } from "lucide-react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { MobileFilterButton, MobileFilterDialog } from "@/components/mobile-filter-toolbar";
import { PageHeading } from "@/components/page-heading";
import { ProfileIdentity } from "@/components/profile-identity";
import { filterHousingListings } from "@/lib/housing-public";
import { housingCategories, housingFeatures, housingLabels, housingStayLengths, housingPriceLabel, type HousingListing } from "@/lib/housing-types";

type Filters={q:string;type:string;category:string;locality:string;minPrice:string;maxPrice:string;utilitiesIncluded:boolean;availableFrom:string;stayLength:string;minSpots:string;furnished:boolean;features:string[];sort:string};
const defaults:Filters={q:"",type:"offer",category:"",locality:"",minPrice:"",maxPrice:"",utilitiesIncluded:false,availableFrom:"",stayLength:"",minSpots:"",furnished:false,features:[],sort:"newest"};
function fromParams(params:URLSearchParams):Filters{return{q:params.get("q")||"",type:params.get("type")||"offer",category:params.get("category")||"",locality:params.get("locality")||"",minPrice:params.get("minPrice")||"",maxPrice:params.get("maxPrice")||"",utilitiesIncluded:params.get("utilitiesIncluded")==="true",availableFrom:params.get("availableFrom")||"",stayLength:params.get("stayLength")||"",minSpots:params.get("minSpots")||"",furnished:params.get("furnished")==="true",features:params.getAll("feature"),sort:params.get("sort")||"newest"};}
function FilterFields({filters,change,toggleFeature}: {filters:Filters;change:<K extends keyof Filters>(key:K,value:Filters[K])=>void;toggleFeature:(value:string)=>void}){return <div className="housing-filter-fields"><label><span>Kategorie</span><select value={filters.category} onChange={(e)=>change("category",e.target.value)}><option value="">Všechny kategorie</option>{housingCategories.map((value)=><option key={value} value={value}>{housingLabels.category[value]}</option>)}</select></label><label><span>Lokalita</span><input value={filters.locality} onChange={(e)=>change("locality",e.target.value)} placeholder="Královo Pole, Bohunice…" /></label><label><span>Cena od</span><input type="number" min="0" value={filters.minPrice} onChange={(e)=>change("minPrice",e.target.value)} /></label><label><span>Cena do</span><input type="number" min="0" value={filters.maxPrice} onChange={(e)=>change("maxPrice",e.target.value)} /></label><label><span>Nejpozději od</span><input type="date" value={filters.availableFrom} onChange={(e)=>change("availableFrom",e.target.value)} /></label><label><span>Délka bydlení</span><select value={filters.stayLength} onChange={(e)=>change("stayLength",e.target.value)}><option value="">Libovolná</option>{housingStayLengths.map((value)=><option value={value} key={value}>{housingLabels.stay[value]}</option>)}</select></label>{filters.type==="offer"&&<><label><span>Nejméně volných míst</span><input type="number" min="1" max="20" value={filters.minSpots} onChange={(e)=>change("minSpots",e.target.value)} /></label><label className="check-row"><input type="checkbox" checked={filters.utilitiesIncluded} onChange={(e)=>change("utilitiesIncluded",e.target.checked)} /><span>Energie zahrnuté</span></label><label className="check-row"><input type="checkbox" checked={filters.furnished} onChange={(e)=>change("furnished",e.target.checked)} /><span>Vybavené</span></label><fieldset className="housing-feature-filter"><legend>Vlastnosti</legend>{housingFeatures.map((value)=><label className="check-row" key={value}><input type="checkbox" checked={filters.features.includes(value)} onChange={()=>toggleFeature(value)} /><span>{housingLabels.feature[value]}</span></label>)}</fieldset></>}</div>}

export function HousingExplorer({initialItems}: {initialItems:HousingListing[]}){
  const params=useSearchParams();const router=useRouter();const pathname=usePathname();const[filters,setFilters]=useState<Filters>(()=>fromParams(params));const[mobileFilters,setMobileFilters]=useState(false);const[items,setItems]=useState(initialItems);const[loadState,setLoadState]=useState<"ready"|"loading"|"error">("ready");
  useEffect(()=>setFilters(fromParams(params)),[params]);
  function sync(next:Filters){const query=new URLSearchParams();for(const key of ["q","type","category","locality","minPrice","maxPrice","availableFrom","stayLength","minSpots","sort"] as const)if(next[key]&&!(key==="sort"&&next[key]==="newest"))query.set(key,next[key]);if(next.utilitiesIncluded)query.set("utilitiesIncluded","true");if(next.furnished)query.set("furnished","true");next.features.forEach((value)=>query.append("feature",value));router.replace(`${pathname}?${query}`,{scroll:false});}
  function change<K extends keyof Filters>(key:K,value:Filters[K]){setFilters((current)=>{const next={...current,[key]:value};sync(next);return next;});}function toggleFeature(value:string){change("features",filters.features.includes(value)?filters.features.filter((item)=>item!==value):[...filters.features,value]);}function reset(){setFilters(defaults);sync(defaults);}async function reload(){setLoadState("loading");const response=await fetch(`/api/housing/listings?${new URLSearchParams(window.location.search).toString()}`,{cache:"no-store"});if(!response.ok){setLoadState("error");return;}const data=await response.json();setItems(data.items);setLoadState("ready");}
  const visible=useMemo(()=>filterHousingListings(items,{q:filters.q,listingType:filters.type,category:filters.category,locality:filters.locality,minPrice:filters.minPrice?Number(filters.minPrice):undefined,maxPrice:filters.maxPrice?Number(filters.maxPrice):undefined,utilitiesIncluded:filters.utilitiesIncluded,availableFrom:filters.availableFrom,stayLength:filters.stayLength,minSpots:filters.minSpots?Number(filters.minSpots):undefined,furnished:filters.furnished,feature:filters.features,sort:filters.sort}),[filters,items]);const active=Object.entries(filters).filter(([key,value])=>key!=="type"&&key!=="sort"&&(Array.isArray(value)?value.length:Boolean(value))).length;
  return <div className="page-stack housing-page"><PageHeading eyebrow="StudentHub Brno" title="Bydlení" description="Nabídky a poptávky studentského bydlení v Brně. Přesná adresa ani kontakty se veřejně nezobrazují." actions={<div className="card-actions"><Link className="button button-secondary" href="/brno/bydleni/moje">Moje inzeráty</Link><Link className="button button-primary" href="/brno/bydleni/novy"><Plus size={18}/>Přidat inzerát</Link></div>}/>
    <aside className="housing-safety" role="note"><strong>Bezpečné hledání bydlení</strong><p>StudentHub není realitní kancelář ani účastník pronájmu. Neposílejte kauci nebo nájem před ověřením nabídky, prohlídkou bydlení a uzavřením smlouvy.</p></aside>
    <div className="housing-tabs" role="tablist" aria-label="Typ inzerátu"><button role="tab" aria-selected={filters.type==="offer"} className={filters.type==="offer"?"active":""} onClick={()=>change("type","offer")}><House size={18}/>Nabízím bydlení</button><button role="tab" aria-selected={filters.type==="wanted"} className={filters.type==="wanted"?"active":""} onClick={()=>change("type","wanted")}><Search size={18}/>Hledám bydlení</button></div>
    <div className="housing-layout"><aside className="housing-filters-desktop"><h2><Filter size={17}/>Filtry</h2><FilterFields filters={filters} change={change} toggleFeature={toggleFeature}/><button className="button button-secondary" onClick={reset}><RotateCcw size={16}/>Vymazat filtry</button></aside><section className="housing-results" aria-live="polite"><div className="housing-toolbar"><label className="housing-search"><Search size={18}/><span className="sr-only">Hledat</span><input value={filters.q} onChange={(e)=>change("q",e.target.value)} placeholder="Hledat podle názvu nebo lokality…"/></label><MobileFilterButton className="housing-mobile-filter" open={mobileFilters} activeCount={active} onOpen={()=>setMobileFilters(true)} controlsId="housing-mobile-filters"/><label><span>Řazení</span><select value={filters.sort} onChange={(e)=>change("sort",e.target.value)}><option value="newest">Nejnovější</option><option value="price_asc">Nejnižší cena</option><option value="price_desc">Nejvyšší cena</option><option value="move_in">Nejbližší nastěhování</option></select></label></div><div className="housing-result-meta"><strong>{visible.length} {visible.length===1?"výsledek":"výsledků"}</strong><span>Aktualizováno právě teď</span>{active>0&&<button onClick={reset}>Vymazat filtry</button>}</div>
      {loadState==="loading"?<div className="housing-grid" aria-label="Načítání"><div className="housing-skeleton"/><div className="housing-skeleton"/></div>:loadState==="error"?<div className="error-state"><p>Inzeráty se nepodařilo načíst.</p><button className="button button-secondary" onClick={reload}>Zkusit znovu</button></div>:visible.length===0?<div className="empty-state housing-empty"><House size={38}/><h2>{items.length?"Žádný inzerát neodpovídá filtrům":"Zatím tu nejsou žádné aktivní inzeráty"}</h2><p>{items.length?"Upravte nebo vymažte aktivní filtry.":"Nevkládáme falešné nabídky. První skutečný inzerát může přidat přihlášený student."}</p>{items.length?<button className="button button-secondary" onClick={reset}>Vymazat filtry</button>:<Link className="button button-primary" href="/brno/bydleni/novy">Přidat první inzerát</Link>}</div>:<div className="housing-grid">{visible.map((item)=><article className="housing-card" key={item.id}><Link href={`/brno/bydleni/${item.id}`} className="housing-card-link">{item.photos[0]?<span className="housing-card-photo"><Image src={item.photos[0].url} alt={`Fotografie: ${item.title}`} fill sizes="(max-width:767px) 124px, 360px" unoptimized/></span>:<span className="housing-card-photo housing-placeholder"><Building2 size={34}/></span>}<span className="housing-card-body"><span className="housing-card-tags"><b>{housingLabels.type[item.listingType]}</b><i>{housingLabels.category[item.category]}</i></span><h2>{item.title}</h2><strong>{housingPriceLabel(item)}</strong><span><MapPin size={14}/>{item.locality}</span><span><CalendarDays size={14}/>Od {new Intl.DateTimeFormat("cs-CZ").format(new Date(item.availableFrom))} · {housingLabels.stay[item.stayLength]}</span>{item.availableSpots&&<span><Users size={14}/>{item.availableSpots} {item.availableSpots===1?"volné místo":"volná místa"}</span>}<ProfileIdentity author={item.author} compact/><small>Zveřejněno {new Intl.DateTimeFormat("cs-CZ",{dateStyle:"medium"}).format(new Date(item.publishedAt||item.createdAt))}</small></span></Link></article>)}</div>}</section></div>
    <MobileFilterDialog open={mobileFilters} activeCount={active} onClose={()=>setMobileFilters(false)} onReset={reset} controlsId="housing-mobile-filters" applyLabel={`Zobrazit ${visible.length} výsledků`} bodyClassName="housing-filter-mobile"><FilterFields filters={filters} change={change} toggleFeature={toggleFeature}/></MobileFilterDialog>
  </div>;
}
