"use client";

import Image from "next/image";
import Link from "next/link";
import { CalendarDays, Check, Flag, House, MapPin, MessageCircle, ShieldAlert, TrainFront, UserRound, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { ChatStartButton } from "@/components/chat-start-button";
import { ProfileIdentity } from "@/components/profile-identity";
import { housingLabels, housingPriceLabel, housingReportReasons, type HousingListing } from "@/lib/housing-types";

const reportLabels={fake:"Falešná nabídka",fraud:"Podvod",outdated:"Neaktuální obsah",discrimination:"Diskriminační obsah",public_contact:"Zakázané kontaktní údaje",inappropriate_photo:"Nevhodné fotografie",harassment:"Obtěžování",other:"Jiný problém"} as const;
export function HousingDetail({item}: {item:HousingListing}){
  const[photo,setPhoto]=useState(0);const[viewer,setViewer]=useState<{complete:boolean}|null|undefined>();const[reason,setReason]=useState<(typeof housingReportReasons)[number]>("fraud");const[detail,setDetail]=useState("");const[message,setMessage]=useState("");const[reporting,setReporting]=useState(false);
  useEffect(()=>{fetch("/api/auth/me",{cache:"no-store"}).then((response)=>response.json()).then((data)=>setViewer(data.profile?{complete:Boolean(data.profile.complete)}:null)).catch(()=>setViewer(null));},[]);
  async function report(event:React.FormEvent){event.preventDefault();setReporting(true);setMessage("");const response=await fetch(`/api/housing/listings/${item.id}/report`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reason,detail,company:""})});const payload=await response.json().catch(()=>({}));setMessage(payload.message||"Hlášení se nepodařilo uložit.");if(response.ok)setDetail("");setReporting(false);}
  return <div className="page-stack housing-detail-page"><nav className="breadcrumbs" aria-label="Drobečková navigace"><Link href="/brno/bydleni">Bydlení</Link><span>/</span><span>{item.title}</span></nav><div className="housing-detail-layout"><section className="housing-gallery" aria-label="Fotografie bydlení">{item.photos.length?<><figure><Image src={item.photos[photo].url} alt={`${item.title} – fotografie ${photo+1}`} fill sizes="(max-width:767px) 100vw, 760px" unoptimized/></figure>{item.photos.length>1&&<div className="housing-thumbnails">{item.photos.map((image,index)=><button type="button" aria-label={`Zobrazit fotografii ${index+1}`} aria-pressed={photo===index} onClick={()=>setPhoto(index)} key={image.id}><Image src={image.url} alt="" fill sizes="84px" unoptimized/></button>)}</div>}</>:<div className="housing-detail-placeholder"><House size={48}/><span>Inzerát bez fotografie</span></div>}</section><article className="housing-detail-card"><div className="housing-card-tags"><b>{housingLabels.type[item.listingType]}</b><i>{housingLabels.category[item.category]}</i></div><h1>{item.title}</h1><strong className="housing-detail-price">{housingPriceLabel(item)}</strong><p>{item.shortDescription}</p><dl className="housing-facts"><div><MapPin/><dt>Lokalita</dt><dd>{item.locality}</dd></div><div><CalendarDays/><dt>Od kdy</dt><dd>{new Intl.DateTimeFormat("cs-CZ",{dateStyle:"long"}).format(new Date(item.availableFrom))} · {housingLabels.stay[item.stayLength]}</dd></div>{item.availableSpots&&<div><Users/><dt>Volná místa</dt><dd>{item.availableSpots}{item.currentOccupants!=null?` · nyní ${item.currentOccupants} obyvatel`:""}</dd></div>}{item.wantedPersonCount&&<div><Users/><dt>Počet osob</dt><dd>{item.wantedPersonCount}</dd></div>}{item.transitAccess&&<div><TrainFront/><dt>MHD</dt><dd>{item.transitAccess}</dd></div>}</dl><ProfileIdentity author={item.author}/><div className="housing-detail-actions">{item.owned?<Link className="button button-primary" href="/brno/bydleni/moje">Spravovat inzerát</Link>:viewer===null?<Link className="button button-primary" href={`/ucet/prihlaseni?next=${encodeURIComponent(`/brno/bydleni/${item.id}`)}`}><MessageCircle size={17}/>Přihlásit se a napsat</Link>:viewer&&!viewer.complete?<Link className="button button-primary" href="/brno/nastaveni#profil">Dokončit profil</Link>:<ChatStartButton contextType="housing_listing" contextId={item.id} label="Napsat autorovi"/>}{item.author.username&&<Link className="button button-secondary" href={`/brno/profil/${item.author.username}`}><UserRound size={17}/>Zobrazit profil</Link>}</div><small>Platné do {new Intl.DateTimeFormat("cs-CZ",{dateStyle:"medium"}).format(new Date(item.expiresAt))}</small></article></div>
    <section className="housing-description"><h2>Podrobnosti</h2><p>{item.description}</p>{item.features.length>0&&<div className="housing-feature-list">{item.features.map((value)=><span key={value}><Check size={15}/>{housingLabels.feature[value]}</span>)}</div>}{item.lifestylePreferences.length>0&&<div className="housing-feature-list">{item.lifestylePreferences.map((value)=><span key={value}>{housingLabels.lifestyle[value as keyof typeof housingLabels.lifestyle]}</span>)}</div>}{item.depositAmount!=null&&<p><strong>Vratná kauce:</strong> {item.depositAmount.toLocaleString("cs-CZ")} Kč</p>}<p><strong>Vybavení:</strong> {item.furnished==null?"Neuvedeno":item.furnished?"Vybavené":"Nevybavené"}</p></section>
    {!item.owned&&<form className="housing-report" onSubmit={report}><div><Flag size={20}/><h2>Nahlásit inzerát</h2><p>Hlášení je neveřejné a předáme ho pouze moderátorům.</p></div><label><span>Důvod</span><select value={reason} onChange={(e)=>setReason(e.target.value as typeof reason)}>{housingReportReasons.map((value)=><option value={value} key={value}>{reportLabels[value]}</option>)}</select></label><label><span>Upřesnění</span><textarea rows={3} maxLength={1200} value={detail} onChange={(e)=>setDetail(e.target.value)}/></label><button className="button button-secondary" disabled={reporting}><ShieldAlert size={17}/>{reporting?"Odesílám…":"Odeslat hlášení"}</button>{message&&<p role="status">{message}</p>}</form>}
    <aside className="housing-safety"><strong>StudentHub negarantuje nabídku</strong><p>Nejsme pronajímatel ani realitní zprostředkovatel a nepřijímáme kauce nebo nájem. Před platbou si ověřte totožnost, bydlení osobně prohlédněte a uzavřete písemnou smlouvu.</p></aside>
  </div>;
}
