"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { BriefcaseBusiness, CheckCircle2, ChevronDown, MapPin, Search, Send, X } from "lucide-react";
import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import type { Job } from "@/lib/types";
import { jobSubmissionSchema, type JobSubmissionInput } from "@/lib/schemas";
import { useStudentPreference } from "@/lib/client-preferences";
import { useModalDialog } from "@/lib/use-modal-dialog";

function JobProposal({ onClose }: { onClose: () => void }) {
  const [success, setSuccess] = useState(false);
  const [serverError, setServerError] = useState("");
  const dialogRef = useModalDialog(true, onClose);
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<z.input<typeof jobSubmissionSchema>, unknown, JobSubmissionInput>({ resolver: zodResolver(jobSubmissionSchema), defaultValues: { reward: 160, consent: false, company: "" } });
  async function submit(data: JobSubmissionInput) {
    setServerError("");
    const response = await fetch("/api/jobs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) });
    const result = await response.json();
    if (!response.ok) return setServerError(result.message || "Návrh se nepodařilo uložit.");
    setSuccess(true);
  }
  return <div ref={dialogRef} tabIndex={-1} className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="job-dialog-title" data-modal-layer><div className="modal-card"><div className="modal-head"><div><span className="eyebrow">Pro firmy a týmy</span><h2 id="job-dialog-title">Navrhnout brigádu</h2></div><button className="icon-button" data-autofocus onClick={onClose} aria-label="Zavřít formulář"><X size={19} /></button></div>{success ? <div className="success-state"><CheckCircle2 size={32} /><h3>Návrh je uložený</h3><p>Inzerát se zveřejní až po kontrole administrátorem.</p><button className="button button-primary" onClick={onClose}>Hotovo</button></div> : <form className="form-grid" onSubmit={handleSubmit(submit)} noValidate><label><span>Firma *</span><input {...register("companyName")} />{errors.companyName && <small className="field-error">Alespoň 2 znaky.</small>}</label><label><span>Název pozice *</span><input {...register("title")} />{errors.title && <small className="field-error">Alespoň 4 znaky.</small>}</label><label><span>Kontaktní e-mail *</span><input type="email" {...register("contactEmail")} />{errors.contactEmail && <small className="field-error">Zadejte platný e-mail.</small>}</label><label><span>Lokalita *</span><input {...register("location")} />{errors.location && <small className="field-error">Doplňte lokalitu.</small>}</label><label><span>Odměna v Kč/h *</span><input type="number" {...register("reward")} />{errors.reward && <small className="field-error">Minimálně 100 Kč.</small>}</label><label><span>Časová náročnost *</span><input {...register("workload")} placeholder="Např. 10 h týdně" />{errors.workload && <small className="field-error">Doplňte rozsah.</small>}</label><label className="form-span"><span>Popis práce *</span><textarea rows={4} {...register("description")} />{errors.description && <small className="field-error">Alespoň 30 znaků.</small>}</label><label className="honeypot" aria-hidden="true"><span>Company</span><input tabIndex={-1} autoComplete="off" aria-hidden="true" {...register("company")} /></label><label className="checkbox-field form-span"><input type="checkbox" {...register("consent")} /><span>Souhlasím se zpracováním údajů pro vyřízení návrhu. *</span></label>{errors.consent && <small className="field-error form-span">Potvrďte souhlas.</small>}{serverError && <p className="field-error form-span">{serverError}</p>}<button className="button button-primary form-span" disabled={isSubmitting}><Send size={17} />{isSubmitting ? "Ukládám…" : "Odeslat ke schválení"}</button></form>}</div></div>;
}

export function JobExplorer({ items }: { items: Job[] }) {
  const [query, setQuery] = useState("");
  const [field, setField] = useState("Všechny");
  const [type, setType] = useState("Všechny");
  const [minReward, setMinReward] = useState(100);
  const [showProposal, setShowProposal] = useState(false);
  const preference = useStudentPreference();
  const filtered = useMemo(() => items.filter((job) => job.status === "approved" && (!preference.universityId || !job.universityIds?.length || job.universityIds.includes(preference.universityId)) && (!preference.facultyId || !job.facultyIds?.length || job.facultyIds.includes(preference.facultyId)) && (field === "Všechny" || job.field === field) && (type === "Všechny" || job.type === type) && job.reward >= minReward && `${job.title} ${job.company} ${job.location}`.toLowerCase().includes(query.toLowerCase())), [items, field, type, minReward, query, preference]);
  return <><section className="filter-panel job-filters"><label className="search-field"><span>Hledat brigádu</span><div><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Pozice, firma, lokalita…" /></div></label><label><span>Obor</span><div className="select-wrap"><select value={field} onChange={(event) => setField(event.target.value)}><option>Všechny</option>{[...new Set(items.map((job) => job.field))].map((value) => <option key={value}>{value}</option>)}</select><ChevronDown size={16} /></div></label><label><span>Typ práce</span><select value={type} onChange={(event) => setType(event.target.value)}><option>Všechny</option>{[...new Set(items.map((job) => job.type))].map((value) => <option key={value}>{value}</option>)}</select></label><label><span>Min. odměna: {minReward} Kč/h</span><input type="range" min="100" max="250" step="10" value={minReward} onChange={(event) => setMinReward(Number(event.target.value))} /></label></section><div className="result-toolbar"><div className="result-count"><strong>{filtered.length}</strong> schválených brigád</div><button className="button button-secondary" onClick={() => setShowProposal(true)}>Navrhnout brigádu</button></div><section className="job-list" aria-live="polite">{filtered.length === 0 ? <div className="empty-state"><BriefcaseBusiness size={28} /><h2>Zatím nemáme ověřené brigády</h2><p>Firma může poslat nabídku ke schválení. Další inzeráty najdete také na <a href="https://www.fajn-brigady.cz/brigady/brno/" target="_blank" rel="noopener noreferrer">Fajn-brigady.cz</a>.</p></div> : filtered.map((job) => <article className={`result-card job-card ${job.featured ? "featured" : ""}`} id={job.id} key={job.id}><div className="job-heading"><span className="job-monogram">{job.company.slice(0, 2).toUpperCase()}</span><div>{job.featured && <span className="sponsored">PLACENĚ ZVÝRAZNĚNO</span>}<h2>{job.title}</h2><p>{job.company}</p></div></div><p>{job.description}</p><dl className="job-meta"><div><dt>Odměna</dt><dd>{job.reward} Kč/h</dd></div><div><dt>Rozsah</dt><dd>{job.workload}</dd></div><div><dt>Typ</dt><dd>{job.type}</dd></div><div><dt>Lokalita</dt><dd><MapPin size={14} />{job.location}</dd></div></dl><a className="button button-primary" href={job.applyUrl || `mailto:${job.contact}?subject=${encodeURIComponent(`Reakce na: ${job.title}`)}`} target={job.applyUrl ? "_blank" : undefined} rel={job.applyUrl ? "noopener noreferrer" : undefined}>Odpovědět na nabídku</a>{job.sourceUrl && <small className="source-note">Zdroj: <a href={job.sourceUrl} target="_blank" rel="noopener noreferrer">veřejný inzerát</a></small>}</article>)}</section>{showProposal && <JobProposal onClose={() => setShowProposal(false)} />}</>;
}
