"use client";

import Image from "next/image";
import Link from "next/link";
import { BookOpenText, CalendarClock, Flag, GraduationCap, Heart, MapPin, PackageCheck, Share2, ShieldAlert, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { useAcademicCatalog } from "@/components/academic-catalog-provider";
import { ChatStartButton } from "@/components/chat-start-button";
import { ProfileIdentity } from "@/components/profile-identity";
import { marketplaceLabels, marketplacePriceLabel, type MarketplaceListing } from "@/lib/marketplace-types";

const favoritesKey = "studenthub-marketplace-favorites-v1";

export function MarketplaceDetail({ item, citySlug }: { item: MarketplaceListing; citySlug: string; emailReady: boolean }) {
  const catalog = useAcademicCatalog(); const [favorite, setFavorite] = useState(false); const [viewer, setViewer] = useState<{ complete: boolean } | null | undefined>(undefined); const [notice, setNotice] = useState(""); const [reportReason, setReportReason] = useState("copyright"); const [reportDetail, setReportDetail] = useState(""); const [reportState, setReportState] = useState("");
  useEffect(() => { try { setFavorite((JSON.parse(localStorage.getItem(favoritesKey) || "[]") as string[]).includes(item.id)); } catch {} }, [item.id]);
  useEffect(() => { fetch("/api/auth/me", { cache: "no-store" }).then((response) => response.json()).then((data) => setViewer(data.profile ? { complete: Boolean(data.profile.complete) } : null)).catch(() => setViewer(null)); }, []);
  function toggleFavorite() { setFavorite((current) => { let ids: string[] = []; try { ids = JSON.parse(localStorage.getItem(favoritesKey) || "[]"); } catch {} const next = current ? ids.filter((id) => id !== item.id) : [...new Set([...ids, item.id])]; localStorage.setItem(favoritesKey, JSON.stringify(next)); return !current; }); }
  async function share() { const url = window.location.href; if (navigator.share) await navigator.share({ title: item.title, text: item.shortDescription, url }).catch(() => null); else { await navigator.clipboard.writeText(url); setNotice("Odkaz byl zkopírován."); } }
  async function report(event: React.FormEvent) { event.preventDefault(); setReportState(""); const response = await fetch(`/api/marketplace/listings/${item.id}/report`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ reason: reportReason, detail: reportDetail, company: "" }) }); const payload = await response.json().catch(() => ({})); setReportState(payload.message || "Hlášení se nepodařilo odeslat."); if (response.ok) setReportDetail(""); }
  const university = catalog.universities.find((value) => value.id === item.universityId); const faculty = catalog.faculties.find((value) => value.id === item.facultyId);
  return <div className="page-stack marketplace-detail-page"><nav className="breadcrumbs" aria-label="Drobečková navigace"><Link href={`/${citySlug}/burza`}>Studentská burza</Link><span>/</span><span>{item.title}</span></nav><div className="marketplace-detail-layout"><section className="marketplace-gallery" aria-label="Fotografie inzerátu">{item.photos.length ? item.photos.map((photo, index) => <figure key={photo.id}><Image src={photo.url} alt={`${item.title} – fotografie ${index + 1}`} fill sizes="(max-width: 767px) 100vw, 720px" unoptimized /></figure>) : <div className="marketplace-detail-placeholder"><BookOpenText size={46} /><span>Bez fotografie</span></div>}</section><article className="marketplace-detail-card"><div className="marketplace-badges"><b>{marketplaceLabels.listingType[item.listingType]}</b><i data-status={item.status}>{marketplaceLabels.status[item.status]}</i></div><h1>{item.title}</h1><strong className="marketplace-detail-price">{marketplacePriceLabel(item)}</strong><p className="marketplace-lead">{item.shortDescription}</p><div className="marketplace-detail-actions"><button className={favorite ? "button button-secondary active" : "button button-secondary"} aria-pressed={favorite} onClick={toggleFavorite}><Heart size={17} fill={favorite ? "currentColor" : "none"} />{favorite ? "Uloženo" : "Uložit"}</button><button className="button button-secondary" onClick={share}><Share2 size={17} />Sdílet</button>{item.chatAvailable && <ChatStartButton contextType="marketplace_listing" contextId={item.id} label="Napsat prodejci" />}</div>{notice && <p className="form-message" role="status">{notice}</p>}<dl className="marketplace-facts"><div><GraduationCap /><dt>Škola</dt><dd>{faculty ? `${university?.shortName} · ${faculty.shortName}` : university?.shortName || "Celé Brno"}</dd></div>{item.subjectName && <div><BookOpenText /><dt>Předmět</dt><dd>{item.subjectName}{item.subjectCode ? ` (${item.subjectCode})` : ""}</dd></div>}{item.teacherName && <div><UserRound /><dt>Vyučující</dt><dd>{item.teacherName}</dd></div>}{item.recommendedYear && <div><CalendarClock /><dt>Ročník</dt><dd>{item.recommendedYear}. ročník · {marketplaceLabels.semester[item.semester]}</dd></div>}<div><PackageCheck /><dt>Podoba</dt><dd>{marketplaceLabels.format[item.materialFormat]}{item.itemCondition ? ` · ${marketplaceLabels.condition[item.itemCondition]}` : ""}</dd></div><div><MapPin /><dt>Předání</dt><dd>{marketplaceLabels.handoff[item.handoffMethod]}{item.handoffLocation ? ` · ${item.handoffLocation}` : ""}</dd></div></dl><ProfileIdentity author={item.author} /><small>Zveřejněno {new Intl.DateTimeFormat("cs-CZ", { dateStyle: "medium", timeZone: "Europe/Prague" }).format(new Date(item.publishedAt))}</small></article></div>
    <section className="marketplace-description"><h2>Popis</h2><p>{item.description}</p>{item.studyProgram && <p><strong>Studijní program:</strong> {item.studyProgram}</p>}{item.academicYear && <p><strong>Akademický rok:</strong> {item.academicYear}</p>}</section>
    <div className="marketplace-contact-report"><section className="form-card marketplace-chat-contact"><div className="section-head"><div><UserRound size={20} /><h2>Kontaktovat prodávajícího</h2></div></div>{item.owned ? <p>Tohle je váš vlastní inzerát.</p> : item.chatAvailable ? <><p>Prodávajícímu napište soukromě přes StudentHub. E-mail ani telefon se nezveřejní.</p>{viewer === null ? <Link className="button button-primary" href={`/ucet/prihlaseni?next=${encodeURIComponent(`/${citySlug}/burza/${item.id}`)}`}>Přihlásit se</Link> : viewer && !viewer.complete ? <Link className="button button-primary" href="/nastaveni#profil">Dokončit profil</Link> : <ChatStartButton contextType="marketplace_listing" contextId={item.id} label="Napsat prodejci" />}</> : <p>Tento starší inzerát nemá profil pro soukromý chat. E-mailový relay zůstává bezpečně vypnutý jako nouzový fallback.</p>}</section><form className="form-card marketplace-report-form" onSubmit={report}><div className="section-head"><div><Flag size={20} /><h2>Nahlásit inzerát</h2></div></div><p>Nahlaste podvod, nelegální kopii, porušení autorských práv nebo akademické poctivosti.</p><label><span>Důvod</span><select value={reportReason} onChange={(event) => setReportReason(event.target.value)}><option value="copyright">Autorská práva</option><option value="academic_integrity">Akademická poctivost</option><option value="fraud">Podvod</option><option value="illegal">Nelegální obsah</option><option value="sold">Už není dostupné</option><option value="privacy">Soukromí</option><option value="spam">Spam</option><option value="other">Jiné</option></select></label><label><span>Upřesnění</span><textarea maxLength={1000} rows={4} value={reportDetail} onChange={(event) => setReportDetail(event.target.value)} /></label><button className="button button-secondary"><ShieldAlert size={17} />Odeslat hlášení</button>{reportState && <p role="status" className="form-message">{reportState}</p>}</form></div>
    <aside className="marketplace-disclaimer"><strong>StudentHub pouze zprostředkovává kontakt</strong><p>Nezpracovává platby, negarantuje pravost ani předání a není stranou obchodu. Neposílejte zálohu neověřenému člověku. Digitální soubory se přes StudentHub nenahrávají.</p></aside>
  </div>;
}
