"use client";

import Image from "next/image";
import Link from "next/link";
import { zodResolver } from "@hookform/resolvers/zod";
import { AlertTriangle, CheckCircle2, ImagePlus, Loader2, ShieldCheck, Trash2 } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { useAcademicCatalog } from "@/components/academic-catalog-provider";
import type { City } from "@/lib/cities";
import { useStudentPreference } from "@/lib/client-preferences";
import { marketplaceCategories, marketplaceConditions, marketplaceFormats, marketplaceLabels, marketplaceListingTypes } from "@/lib/marketplace-types";
import { marketplaceListingSchema, type MarketplaceListingFormInput, type MarketplaceListingInput } from "@/lib/schemas";

function uploadListing(form: FormData, onProgress: (value: number) => void) {
  return new Promise<{ ok: boolean; status: number; payload: Record<string, unknown> }>((resolve) => { const xhr = new XMLHttpRequest(); xhr.open("POST", "/api/marketplace/listings"); xhr.upload.addEventListener("progress", (event) => { if (event.lengthComputable) onProgress(Math.round(event.loaded / event.total * 100)); }); xhr.addEventListener("load", () => { let payload: Record<string, unknown> = {}; try { payload = JSON.parse(xhr.responseText); } catch {} resolve({ ok: xhr.status >= 200 && xhr.status < 300, status: xhr.status, payload }); }); xhr.addEventListener("error", () => resolve({ ok: false, status: 0, payload: { message: "Spojení se serverem selhalo." } })); xhr.send(form); });
}

export function MarketplaceListingForm({ city }: { city: City }) {
  const catalog = useAcademicCatalog(); const preference = useStudentPreference(catalog); const [photos, setPhotos] = useState<File[]>([]); const [photoError, setPhotoError] = useState(""); const [serverError, setServerError] = useState(""); const [progress, setProgress] = useState(0); const [success, setSuccess] = useState<{ message: string; href?: string } | null>(null); const initialized = useRef(false);
  const { register, handleSubmit, setValue, reset, getValues, control, formState: { errors, isSubmitting } } = useForm<MarketplaceListingFormInput, unknown, MarketplaceListingInput>({ resolver: zodResolver(marketplaceListingSchema), defaultValues: { cityId: city.id, listingType: "offer", category: "textbook", title: "", shortDescription: "", description: "", priceMode: "fixed", priceScope: "item", universityId: "", facultyId: "", studyProgram: "", subjectName: "", subjectCode: "", teacherName: "", semester: "not_applicable", academicYear: "2026/2027", materialFormat: "printed", itemCondition: "used", handoffMethod: "in_person", handoffLocation: "", copyrightConfirmed: false, ownNotesConfirmed: false, company: "" } });
  const universityId = useWatch({ control, name: "universityId" }); const category = useWatch({ control, name: "category" }); const format = useWatch({ control, name: "materialFormat" }); const itemCondition = useWatch({ control, name: "itemCondition" }); const priceMode = useWatch({ control, name: "priceMode" }); const listingType = useWatch({ control, name: "listingType" });
  useEffect(() => {
    if (initialized.current || !preference.completed) return;
    initialized.current = true;
    reset({ ...getValues(), universityId: preference.universityId || "", facultyId: preference.facultyId || "", ...(preference.studyYear ? { recommendedYear: preference.studyYear } : {}) });
  }, [getValues, preference, reset]);
  useEffect(() => { if (format === "digital" && itemCondition) setValue("itemCondition", ""); else if (format !== "digital" && !itemCondition) setValue("itemCondition", "used"); }, [format, itemCondition, setValue]);
  const previews = useMemo(() => photos.map((file) => ({ file, url: URL.createObjectURL(file) })), [photos]);
  useEffect(() => () => previews.forEach((item) => URL.revokeObjectURL(item.url)), [previews]);
  const universityRegistration = register("universityId"); const facultyOptions = catalog.faculties.filter((faculty) => faculty.universityId === universityId && faculty.active);
  function choosePhotos(list: FileList | null) { setPhotoError(""); const next = [...photos, ...Array.from(list || [])]; if (next.length > 3) { setPhotoError("Lze přidat nejvýše tři fotografie."); return; } if (next.some((file) => file.size > 5 * 1024 * 1024 || !["image/jpeg", "image/png", "image/webp"].includes(file.type))) { setPhotoError("Fotografie musí být JPEG, PNG nebo WebP do 5 MB. SVG, PDF a dokumenty nejsou povoleny."); return; } setPhotos(next); }
  async function submit(values: MarketplaceListingInput) { setServerError(""); setProgress(1); sessionStorage.setItem("studenthub-marketplace-draft", JSON.stringify(values)); const form = new FormData(); Object.entries(values).forEach(([key, value]) => { if (value !== undefined) form.set(key, String(value)); }); photos.forEach((photo) => form.append("photos", photo)); const result = await uploadListing(form, setProgress); if (!result.ok) { const issues = result.payload.issues && typeof result.payload.issues === "object" ? Object.values(result.payload.issues as Record<string, string[]>).flat().join(" ") : ""; setServerError(String(result.payload.message || issues || "Inzerát se nepodařilo uložit.")); setProgress(0); return; } sessionStorage.removeItem("studenthub-marketplace-draft"); setProgress(100); setSuccess({ message: String(result.payload.message), href: typeof result.payload.href === "string" ? result.payload.href : undefined }); reset(); setPhotos([]); }
  const issueMessages = Object.values(errors).map((issue) => issue?.message).filter(Boolean) as string[];
  if (success) return <section className="marketplace-form-success success-state" role="status"><CheckCircle2 size={38} /><h2>Inzerát je zveřejněný</h2><p>{success.message}</p>{success.href && <Link className="button button-primary" href={success.href}>Zobrazit inzerát</Link>}<Link className="button button-secondary" href={`/${city.slug}/burza`}>Zpět do burzy</Link></section>;
  return <form className="marketplace-form" onSubmit={handleSubmit(submit)} noValidate>
    {issueMessages.length > 0 && <div className="form-error-summary" role="alert"><AlertTriangle size={18} /><div><strong>Zkontrolujte formulář</strong><ul>{[...new Set(issueMessages)].map((message) => <li key={message}>{message}</li>)}</ul></div></div>}
    <fieldset><legend>Co chcete zveřejnit</legend><div className="form-grid"><label><span>Typ inzerátu *</span><select {...register("listingType")}>{marketplaceListingTypes.map((value) => <option value={value} key={value}>{marketplaceLabels.listingType[value]}</option>)}</select></label><label><span>Kategorie *</span><select {...register("category")}>{marketplaceCategories.map((value) => <option value={value} key={value}>{marketplaceLabels.category[value]}</option>)}</select></label><label className="form-span"><span>Název *</span><input maxLength={140} {...register("title")} placeholder="Např. Lineární algebra – učebnice" /></label><label className="form-span"><span>Krátký popis *</span><input maxLength={240} {...register("shortDescription")} placeholder="Jedna věta viditelná na kartě" /></label><label className="form-span"><span>Úplný popis *</span><textarea rows={7} maxLength={3000} {...register("description")} placeholder="Stav, obsah, vydání a vše důležité pro zájemce. Nevkládejte kontaktní údaje." /></label></div></fieldset>
    <fieldset><legend>Cena</legend><div className="form-grid"><label><span>Způsob ceny *</span><select {...register("priceMode")}><option value="fixed">Pevná cena</option><option value="free">Zdarma</option>{listingType === "wanted" && <option value="negotiable">Dohodou</option>}</select></label><label><span>Cena v Kč</span><input type="number" min="0" step="1" disabled={priceMode !== "fixed"} {...register("priceAmount", { setValueAs: (value) => value === "" ? undefined : Number(value) })} /></label><label><span>Cena platí *</span><select {...register("priceScope")}><option value="item">Za jeden kus</option><option value="bundle">Za celý balíček</option></select></label></div><p className="field-help">StudentHub nepřijímá platby, nedrží rezervace peněz a nepočítá provizi.</p></fieldset>
    <fieldset><legend>Škola a předmět</legend><div className="form-grid"><label><span>Univerzita</span><select {...universityRegistration} onChange={(event) => { universityRegistration.onChange(event); setValue("facultyId", ""); }}><option value="">Celé Brno / neurčeno</option>{catalog.universities.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Fakulta</span><select disabled={!universityId} {...register("facultyId")}><option value="">Celá univerzita / neurčeno</option>{facultyOptions.map((faculty) => <option value={faculty.id} key={faculty.id}>{faculty.name}</option>)}</select></label><label><span>Studijní program nebo obor</span><input maxLength={140} {...register("studyProgram")} /></label><label><span>Předmět</span><input maxLength={140} {...register("subjectName")} /></label><label><span>Kód předmětu</span><input maxLength={40} {...register("subjectCode")} /></label><label><span>Vyučující (nepovinné)</span><input maxLength={120} {...register("teacherName")} /><small>Pouze orientační údaj, nevytváří profil ani hodnocení osoby.</small></label><label><span>Doporučený ročník</span><select {...register("recommendedYear", { setValueAs: (value) => value === "" ? undefined : Number(value) })}><option value="">Neurčeno</option>{[1,2,3,4,5,6].map((year) => <option value={year} key={year}>{year}. ročník</option>)}</select></label><label><span>Semestr</span><select {...register("semester")}><option value="not_applicable">Neurčeno</option><option value="winter">Zimní</option><option value="summer">Letní</option><option value="both">Oba semestry</option></select></label><label><span>Akademický rok</span><input placeholder="2026/2027" {...register("academicYear")} /></label></div></fieldset>
    <fieldset><legend>Podoba a předání</legend><div className="form-grid"><label><span>Formát *</span><select {...register("materialFormat")}>{marketplaceFormats.map((value) => <option value={value} key={value}>{marketplaceLabels.format[value]}</option>)}</select></label>{format !== "digital" && <label><span>Stav předmětu *</span><select {...register("itemCondition")}>{marketplaceConditions.map((value) => <option value={value} key={value}>{marketplaceLabels.condition[value]}</option>)}</select></label>}<label><span>Způsob předání *</span><select {...register("handoffMethod")}><option value="in_person">Osobní předání</option><option value="shipping">Zaslání</option><option value="digital">Digitální předání</option><option value="agreement">Dohodou</option></select></label><label><span>Přibližné místo předání</span><input maxLength={120} {...register("handoffLocation")} placeholder="Např. kampus Bohunice" /></label></div></fieldset>
    <fieldset><legend>Fotografie</legend><p>Nahrajte nejvýše 3 vlastní fotografie nebo obrazové náhledy. Digitální soubor, PDF ani dokument se do StudentHubu nenahrává.</p><label className="marketplace-photo-picker"><ImagePlus size={22} /><span>Přidat fotografie</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => { choosePhotos(event.target.files); event.target.value = ""; }} /></label>{photoError && <p className="field-error" role="alert">{photoError}</p>}<div className="marketplace-photo-previews">{previews.map(({ file, url }, index) => <figure key={`${file.name}-${file.lastModified}`}><span><Image src={url} alt={`Náhled fotografie ${index + 1}`} fill unoptimized /></span><figcaption>{file.name}</figcaption><button type="button" aria-label={`Odebrat fotografii ${index + 1}`} onClick={() => setPhotos((current) => current.filter((_, position) => position !== index))}><Trash2 size={16} /></button></figure>)}</div></fieldset>
    <fieldset><legend>Pravidla</legend><label className="honeypot" aria-hidden="true"><span>Firma</span><input tabIndex={-1} autoComplete="off" aria-hidden="true" {...register("company")} /></label><div className="marketplace-rules"><ShieldCheck size={22} /><div><strong>Autorská práva a akademická poctivost</strong><p>Zakázané jsou nelegální kopie, skeny knih, PDF a e-knihy bez oprávnění, materiály vyučujících bez svolení, nahrávky přednášek, zadání a odpovědi ke zkouškám, řešení právě hodnocených úkolů a materiály určené k podvádění.</p></div></div><label className="checkbox-field"><input type="checkbox" {...register("copyrightConfirmed")} /><span>Potvrzuji, že mám právo věc nebo materiál nabízet a neporušuji autorská práva ani pravidla akademické poctivosti. *</span></label>{category === "own_notes" && <label className="checkbox-field"><input type="checkbox" {...register("ownNotesConfirmed")} /><span>Jsem autorem poznámek a neobsahují neoprávněně převzatý chráněný obsah. *</span></label>}<p className="field-help">Veřejná přezdívka a neveřejný kontaktní e-mail se bezpečně převezmou z přihlášeného profilu.</p></fieldset>
    {serverError && <div className="error-state" role="alert">{serverError}</div>}{progress > 0 && isSubmitting && <div className="upload-progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><span style={{ width: `${progress}%` }} /><small>Nahrávání a bezpečnostní kontrola {progress} %</small></div>}
    <div className="form-footer"><Link className="button button-secondary" href={`/${city.slug}/burza`}>Zrušit</Link><button className="button button-primary" disabled={isSubmitting || Boolean(photoError)}>{isSubmitting ? <><Loader2 className="spin" size={17} />Odesílám…</> : "Zveřejnit inzerát"}</button></div>
  </form>;
}
