"use client";

import Image from "next/image";
import Link from "next/link";
import { BookOpenText, CalendarClock, Flag, GraduationCap, Heart, Mail, MapPin, PackageCheck, Share2, ShieldAlert, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { useAcademicCatalog } from "@/components/academic-catalog-provider";
import { ProfileIdentity } from "@/components/profile-identity";
import { marketplaceLabels, marketplacePriceLabel, type MarketplaceListing } from "@/lib/marketplace-types";

const favoritesKey = "studenthub-marketplace-favorites-v1";

export function MarketplaceDetail({ item, citySlug, emailReady }: { item: MarketplaceListing; citySlug: string; emailReady: boolean }) {
  const catalog = useAcademicCatalog(); const [favorite, setFavorite] = useState(false); const [viewer, setViewer] = useState<{ complete: boolean } | null | undefined>(undefined); const [contactMessage, setContactMessage] = useState(""); const [contactConsent, setContactConsent] = useState(false); const [contactState, setContactState] = useState(""); const [contactPending, setContactPending] = useState(false); const [reportReason, setReportReason] = useState("copyright"); const [reportDetail, setReportDetail] = useState(""); const [reportState, setReportState] = useState("");
  useEffect(() => { try { setFavorite((JSON.parse(localStorage.getItem(favoritesKey) || "[]") as string[]).includes(item.id)); } catch {} }, [item.id]);
  useEffect(() => { fetch("/api/auth/me", { cache: "no-store" }).then((response) => response.json()).then((data) => setViewer(data.profile ? { complete: Boolean(data.profile.complete) } : null)).catch(() => setViewer(null)); }, []);
  useEffect(() => { const saved = sessionStorage.getItem(`studenthub-marketplace-contact-${item.id}`); if (saved) setContactMessage(saved); }, [item.id]);
  useEffect(() => { if (contactMessage) sessionStorage.setItem(`studenthub-marketplace-contact-${item.id}`, contactMessage); }, [contactMessage, item.id]);
  function toggleFavorite() { setFavorite((current) => { let ids: string[] = []; try { ids = JSON.parse(localStorage.getItem(favoritesKey) || "[]"); } catch {} const next = current ? ids.filter((id) => id !== item.id) : [...new Set([...ids, item.id])]; localStorage.setItem(favoritesKey, JSON.stringify(next)); return !current; }); }
  async function share() { const url = window.location.href; if (navigator.share) await navigator.share({ title: item.title, text: item.shortDescription, url }).catch(() => null); else { await navigator.clipboard.writeText(url); setContactState("Odkaz byl zkopírován."); } }
  async function contact(event: React.FormEvent) { event.preventDefault(); setContactPending(true); setContactState(""); const response = await fetch(`/api/marketplace/listings/${item.id}/contact`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ message: contactMessage, consent: contactConsent, company: "" }) }); const payload = await response.json().catch(() => ({})); setContactState(payload.message || "Zprávu se nepodařilo odeslat."); if (response.ok) { sessionStorage.removeItem(`studenthub-marketplace-contact-${item.id}`); setContactMessage(""); setContactConsent(false); } setContactPending(false); }
  async function report(event: React.FormEvent) { event.preventDefault(); setReportState(""); const response = await fetch(`/api/marketplace/listings/${item.id}/report`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ reason: reportReason, detail: reportDetail, company: "" }) }); const payload = await response.json().catch(() => ({})); setReportState(payload.message || "Hlášení se nepodařilo odeslat."); if (response.ok) setReportDetail(""); }
  const university = catalog.universities.find((value) => value.id === item.universityId); const faculty = catalog.faculties.find((value) => value.id === item.facultyId);
  return <div className="page-stack marketplace-detail-page"><nav className="breadcrumbs" aria-label="Drobečková navigace"><Link href={`/${citySlug}/burza`}>Studentská burza</Link><span>/</span><span>{item.title}</span></nav><div className="marketplace-detail-layout"><section className="marketplace-gallery" aria-label="Fotografie inzerátu">{item.photos.length ? item.photos.map((photo, index) => <figure key={photo.id}><Image src={photo.url} alt={`${item.title} – fotografie ${index + 1}`} fill sizes="(max-width: 767px) 100vw, 720px" unoptimized /></figure>) : <div className="marketplace-detail-placeholder"><BookOpenText size={46} /><span>Bez fotografie</span></div>}</section><article className="marketplace-detail-card"><div className="marketplace-badges"><b>{marketplaceLabels.listingType[item.listingType]}</b><i data-status={item.status}>{marketplaceLabels.status[item.status]}</i></div><h1>{item.title}</h1><strong className="marketplace-detail-price">{marketplacePriceLabel(item)}</strong><p className="marketplace-lead">{item.shortDescription}</p><div className="marketplace-detail-actions"><button className={favorite ? "button button-secondary active" : "button button-secondary"} aria-pressed={favorite} onClick={toggleFavorite}><Heart size={17} fill={favorite ? "currentColor" : "none"} />{favorite ? "Uloženo" : "Uložit"}</button><button className="button button-secondary" onClick={share}><Share2 size={17} />Sdílet</button></div><dl className="marketplace-facts"><div><GraduationCap /><dt>Škola</dt><dd>{faculty ? `${university?.shortName} · ${faculty.shortName}` : university?.shortName || "Celé Brno"}</dd></div>{item.subjectName && <div><BookOpenText /><dt>Předmět</dt><dd>{item.subjectName}{item.subjectCode ? ` (${item.subjectCode})` : ""}</dd></div>}{item.teacherName && <div><UserRound /><dt>Vyučující</dt><dd>{item.teacherName}</dd></div>}{item.recommendedYear && <div><CalendarClock /><dt>Ročník</dt><dd>{item.recommendedYear}. ročník · {marketplaceLabels.semester[item.semester]}</dd></div>}<div><PackageCheck /><dt>Podoba</dt><dd>{marketplaceLabels.format[item.materialFormat]}{item.itemCondition ? ` · ${marketplaceLabels.condition[item.itemCondition]}` : ""}</dd></div><div><MapPin /><dt>Předání</dt><dd>{marketplaceLabels.handoff[item.handoffMethod]}{item.handoffLocation ? ` · ${item.handoffLocation}` : ""}</dd></div></dl><ProfileIdentity author={item.author} /><small>Zveřejněno {new Intl.DateTimeFormat("cs-CZ", { dateStyle: "medium", timeZone: "Europe/Prague" }).format(new Date(item.publishedAt))}</small></article></div>
    <section className="marketplace-description"><h2>Popis</h2><p>{item.description}</p>{item.studyProgram && <p><strong>Studijní program:</strong> {item.studyProgram}</p>}{item.academicYear && <p><strong>Akademický rok:</strong> {item.academicYear}</p>}</section>
    <div className="marketplace-contact-report"><form className="form-card" onSubmit={contact}><div className="section-head"><div><Mail size={20} /><h2>Kontaktovat prodávajícího</h2></div></div><p>E-mail prodávajícího zůstává neveřejný. StudentHub mu bezpečně přepošle vaši zprávu.</p>{!emailReady && <div className="warning-state" role="status">Kontaktování je dočasně vypnuté, protože produkční e-mailová brána ještě není nastavena.</div>}{viewer === null ? <div className="auth-action-note"><p>Pro kontaktování se přihlaste; e-mail se bezpečně použije z vašeho účtu.</p><Link className="button button-primary" href={`/ucet/prihlaseni?next=${encodeURIComponent(`/${citySlug}/burza/${item.id}`)}`}>Přihlásit se</Link></div> : viewer && !viewer.complete ? <div className="auth-action-note"><p>Před kontaktováním dokončete veřejný profil.</p><Link className="button button-primary" href="/nastaveni#profil">Doplnit profil</Link></div> : null}<label><span>Zpráva</span><textarea required minLength={20} maxLength={2000} rows={6} disabled={!viewer?.complete} value={contactMessage} onChange={(event) => setContactMessage(event.target.value)} /></label><label className="checkbox-field"><input type="checkbox" disabled={!viewer?.complete} checked={contactConsent} onChange={(event) => setContactConsent(event.target.checked)} required /><span>Souhlasím s předáním zprávy a své ověřené e-mailové adresy prodávajícímu.</span></label><button className="button button-primary" disabled={!viewer?.complete || !emailReady || contactPending || item.status !== "active"}>{contactPending ? "Odesílám…" : !emailReady ? "Kontaktování je vypnuté" : item.status === "active" ? "Kontaktovat prodávajícího" : "Inzerát není aktivní"}</button>{contactState && <p role="status" className="form-message">{contactState}</p>}</form><form className="form-card marketplace-report-form" onSubmit={report}><div className="section-head"><div><Flag size={20} /><h2>Nahlásit inzerát</h2></div></div><p>Nahlaste podvod, nelegální kopii, porušení autorských práv nebo akademické poctivosti.</p><label><span>Důvod</span><select value={reportReason} onChange={(event) => setReportReason(event.target.value)}><option value="copyright">Autorská práva</option><option value="academic_integrity">Akademická poctivost</option><option value="fraud">Podvod</option><option value="illegal">Nelegální obsah</option><option value="sold">Už není dostupné</option><option value="privacy">Soukromí</option><option value="spam">Spam</option><option value="other">Jiné</option></select></label><label><span>Upřesnění</span><textarea maxLength={1000} rows={4} value={reportDetail} onChange={(event) => setReportDetail(event.target.value)} /></label><button className="button button-secondary"><ShieldAlert size={17} />Odeslat hlášení</button>{reportState && <p role="status" className="form-message">{reportState}</p>}</form></div>
    <aside className="marketplace-disclaimer"><strong>StudentHub pouze zprostředkovává kontakt</strong><p>Nezpracovává platby, negarantuje pravost ani předání a není stranou obchodu. Neposílejte zálohu neověřenému člověku. Digitální soubory se přes StudentHub nenahrávají.</p></aside>
  </div>;
}
