"use client";

import Link from "next/link";
import { RotateCcw, ShieldBan, UserRound } from "lucide-react";

type Row = Record<string, unknown>;

export function ProfileAdminPanel({ profiles, reports, history, onApi }: { profiles: Row[]; reports: Row[]; history: Row[]; onApi: (url: string, options?: RequestInit) => Promise<boolean> }) {
  async function action(profileId: string, value: "suspend" | "restore" | "dismiss_report", reportId?: string) { const reason = prompt(value === "suspend" ? "Důvod pozastavení účtu" : value === "restore" ? "Důvod obnovení účtu" : "Poznámka k uzavření hlášení"); if (!reason?.trim()) return; await onApi("/api/admin/profiles", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ profileId, action: value, reason, reportId }) }); }
  const active = profiles.filter((row) => row.account_status === "active").length; const suspended = profiles.filter((row) => row.account_status === "suspended").length; const newReports = reports.filter((row) => row.status === "new");
  const now = new Date(); const today = new Date(now); today.setHours(0, 0, 0, 0); const lastWeek = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const registeredToday = profiles.filter((row) => row.created_at && new Date(String(row.created_at)) >= today).length; const registeredLastWeek = profiles.filter((row) => row.created_at && new Date(String(row.created_at)) >= lastWeek).length;
  return <section className="admin-panel profile-admin-panel"><div className="admin-section-head"><div><h2>Uživatelské profily</h2><p>{profiles.length} profilů · {active} aktivních · {suspended} pozastavených · {newReports.length} nových hlášení. E-maily ani hesla se v tomto přehledu nenačítají.</p></div><Link className="button button-secondary" href="/profily" target="_blank">Veřejný adresář</Link></div><div className="admin-stat-grid" aria-label="Statistiky uživatelských účtů"><article><span>Nové dnes</span><strong>{registeredToday}</strong></article><article><span>Nové za 7 dní</span><strong>{registeredLastWeek}</strong></article><article><span>Aktivní účty</span><strong>{active}</strong></article><article><span>Pozastavené</span><strong>{suspended}</strong></article></div><div className="approval-list">{profiles.length ? profiles.map((profile) => { const profileReports = newReports.filter((report) => report.reported_id === profile.id); return <article key={String(profile.id)}><div><span className={`status-pill status-${String(profile.account_status)}`}>{String(profile.account_status)}</span><h3><UserRound size={16} /> {String(profile.display_name || "Student")}{profile.username ? ` · @${String(profile.username)}` : " · nedokončený"}</h3><p>{String(profile.university_id || "bez školy")}{profile.faculty_id ? ` · ${String(profile.faculty_id)}` : ""} · {String(profile.content_count || 0)} položek obsahu</p>{profileReports.map((report) => <div className="warning-state" key={String(report.id)}><strong>{String(report.reason)}</strong><p>{String(report.detail || "Bez doplnění")}</p><button className="button button-secondary" onClick={() => action(String(profile.id), "dismiss_report", String(report.id))}>Uzavřít hlášení</button></div>)}</div><div>{profile.account_status === "suspended" ? <button className="button button-secondary" onClick={() => action(String(profile.id), "restore")}><RotateCcw size={15} /> Obnovit</button> : <button className="button button-secondary" onClick={() => action(String(profile.id), "suspend")}><ShieldBan size={15} /> Pozastavit</button>}{Boolean(profile.username) && <Link className="button button-secondary" href={`/profil/${String(profile.username)}`} target="_blank">Profil</Link>}</div></article>; }) : <p className="muted">Zatím žádný profil.</p>}</div><details className="admin-audit-log"><summary>Audit zásahů ({history.length})</summary>{history.map((row) => <p key={String(row.id)}>{String(row.created_at)} · {String(row.action)} · {String(row.reason)}</p>)}</details></section>;
}
