import Image from "next/image";
import Link from "next/link";
import { BadgeCheck,BookOpenText,CalendarDays,GraduationCap,MapPin,MessageCircle,ShoppingBag,Users } from "lucide-react";
import { ProfileModerationActions } from "@/components/profile-moderation-actions";
import { faculties,universities } from "@/lib/universities";

type Profile={username:string;displayName:string;avatarUrl?:string;bio?:string;universityId?:string;facultyId?:string;studyProgram?:string;studyYear?:number;interests:string[];createdAt:string;verifiedEmail:boolean};
type Content={posts:Array<{id:string;body:string;category:string;created_at:string}>;buddy:Array<{id:string;activity_type:string;approximate_location:string;starts_at:string;description:string}>;listings:Array<{id:string;city_id:string;title:string;price_mode:string;price_amount:number|null;status:string;published_at:string}>;events:Array<{id:string;title:string;starts_at:string;venue:string;status:string}>};
export function PublicProfileView({profile,content,own=false}:{profile:Profile;content:Content;own?:boolean}){const university=universities.find((item)=>item.id===profile.universityId);const faculty=faculties.find((item)=>item.id===profile.facultyId);return <div className="page-stack public-profile-page"><section className="public-profile-hero"><span className="profile-avatar profile-avatar-large">{profile.avatarUrl?<Image src={profile.avatarUrl} alt={`Profilová fotografie ${profile.displayName}`} width={96} height={96} unoptimized/>:profile.displayName.slice(0,2).toUpperCase()}</span><div><span className="eyebrow">@{profile.username}</span><h1>{profile.displayName}</h1><p className="verified-email-label"><BadgeCheck size={16}/>Ověřený e-mail</p>{profile.bio&&<p>{profile.bio}</p>}<dl className="profile-public-facts">{university&&<div><GraduationCap/><dt>Škola</dt><dd>{faculty?`${university.shortName} · ${faculty.shortName}`:university.shortName}</dd></div>}{profile.studyProgram&&<div><BookOpenText/><dt>Program</dt><dd>{profile.studyProgram}</dd></div>}{profile.studyYear&&<div><CalendarDays/><dt>Ročník</dt><dd>{profile.studyYear}. ročník</dd></div>}</dl>{profile.interests.length>0&&<div className="profile-interests">{profile.interests.map((item)=><span className="tag" key={item}>{item}</span>)}</div>}<small>Profil od {new Intl.DateTimeFormat("cs-CZ",{dateStyle:"medium"}).format(new Date(profile.createdAt))}</small></div>{own?<Link className="button button-secondary" href="/nastaveni">Upravit profil</Link>:<ProfileModerationActions username={profile.username}/>}</section><section className="profile-public-content"><h2>Veřejné příspěvky</h2>{!content.posts.length&&!content.buddy.length&&!content.listings.length&&!content.events.length?<div className="empty-state"><Users/><h3>Zatím bez aktivního veřejného obsahu</h3></div>:<div className="profile-content-grid">{content.posts.map((item)=><Link href={`/komunita?post=${item.id}`} className="profile-content-card" key={`post-${item.id}`}><MessageCircle/><span><strong>{item.category}</strong><p>{item.body}</p></span></Link>)}{content.buddy.map((item)=><Link href="/partak" className="profile-content-card" key={`buddy-${item.id}`}><Users/><span><strong>{item.activity_type} · {item.approximate_location}</strong><p>{item.description}</p></span></Link>)}{content.listings.map((item)=><Link href={`/${item.city_id}/burza/${item.id}`} className="profile-content-card" key={`listing-${item.id}`}><ShoppingBag/><span><strong>{item.title}</strong><p>{item.status}</p></span></Link>)}{content.events.map((item)=><Link href="/brno/kalendar?view=community" className="profile-content-card" key={`event-${item.id}`}><MapPin/><span><strong>{item.title}</strong><p>{item.venue}</p></span></Link>)}</div>}</section></div>;}
