"use client";

import { CheckCircle2, Globe2 as Chrome, KeyRound, LogIn, MailPlus } from "lucide-react";
import { useEffect, useState } from "react";

type Mode="login"|"signup"|"recover";

export function UserLoginForm({next="/nastaveni",description="Pro tuto akci je potřeba účet s ověřeným e-mailem.",compact=false}:{next?:string;description?:string;compact?:boolean}){
  const [mode,setMode]=useState<Mode>("login"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [pending,setPending]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [googleEnabled,setGoogleEnabled]=useState(false);
  useEffect(()=>{ fetch("/api/profile",{cache:"no-store"}).then((response)=>response.json()).then((value)=>setGoogleEnabled(Boolean(value.googleEnabled))).catch(()=>undefined); },[]);
  async function submit(event:React.FormEvent){ event.preventDefault(); setPending(true); setError(""); setMessage(""); const endpoint=mode==="signup"?"/api/auth/signup":mode==="recover"?"/api/auth/recover":"/api/auth/password"; const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,...(mode==="recover"?{}:{password}),next})}); const result=await response.json().catch(()=>({})); setPending(false); if(!response.ok)return setError(result.message||"Akci se nepodařilo dokončit."); if(mode==="login")return window.location.assign(result.next||next); setMessage(result.message); }
  async function google(){ setPending(true); setError(""); const response=await fetch("/api/auth/google",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({next})}); const result=await response.json().catch(()=>({})); setPending(false); if(!response.ok||!result.url)return setError(result.message||"Google přihlášení se nepodařilo spustit."); window.location.assign(result.url); }
  if(message)return <div className="success-state"><CheckCircle2 size={32}/><h2>{mode==="recover"?"Zkontrolujte e-mail":"Potvrďte registraci"}</h2><p>{message}</p><button className="button button-secondary" onClick={()=>{setMessage("");setMode("login");}}>Zpět k přihlášení</button></div>;
  return <form className={`form-card auth-card${compact?" auth-card-compact":""}`} onSubmit={submit} noValidate><h2>{mode==="signup"?"Vytvořit účet e-mailem":mode==="recover"?"Obnovit heslo":"Přihlásit se e-mailem"}</h2><p>{description} Heslo spravuje výhradně Supabase Auth.</p><button type="button" className="button button-google" onClick={google} disabled={pending||!googleEnabled}><Chrome size={17}/>Pokračovat přes Google</button>{!googleEnabled&&<small className="auth-provider-note">Google přihlášení zatím není nakonfigurované a produkčně ověřené.</small>}<div className="auth-mode-switch" role="group" aria-label="Způsob přihlášení"><button type="button" className={mode==="signup"?"active":""} onClick={()=>{setMode("signup");setError("");}}><MailPlus size={15}/>Vytvořit účet e-mailem</button><button type="button" className={mode==="login"?"active":""} onClick={()=>{setMode("login");setError("");}}><LogIn size={15}/>Přihlásit se e-mailem</button></div><label><span>E-mail</span><input type="email" required autoComplete="email" value={email} onChange={(event)=>setEmail(event.target.value)}/></label>{mode!=="recover"&&<label><span>Heslo</span><input type="password" required minLength={mode==="signup"?10:1} maxLength={128} autoComplete={mode==="signup"?"new-password":"current-password"} value={password} onChange={(event)=>setPassword(event.target.value)}/>{mode==="signup"&&<small>Nejméně 10 znaků, alespoň jedno písmeno a číslo.</small>}</label>}{error&&<p className="field-error" role="alert">{error}</p>}<button className="button button-primary" disabled={pending}>{mode==="signup"?<MailPlus size={17}/>:mode==="recover"?<KeyRound size={17}/>:<LogIn size={17}/>} {pending?"Pracuji…":mode==="signup"?"Vytvořit účet e-mailem":mode==="recover"?"Poslat obnovovací odkaz":"Přihlásit se e-mailem"}</button><button type="button" className="text-link" onClick={()=>{setMode(mode==="recover"?"login":"recover");setError("");}}> {mode==="recover"?"Zpět k přihlášení":"Zapomenuté heslo?"}</button></form>;
}
