import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Search,Users } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { createServiceClient,isSupabaseConfigured } from "@/lib/supabase-server";
import { publicProfileFromRow } from "@/lib/profile-server";
export const metadata:Metadata={title:"Studentské profily",description:"Veřejné profily studentů a jejich aktivní komunitní obsah.",alternates:{canonical:"/profily"}};
export default async function ProfilesPage({searchParams}:{searchParams:Promise<{q?:string}>}){const q=(await searchParams).q?.trim().slice(0,80)||"";let items:NonNullable<Awaited<ReturnType<typeof publicProfileFromRow>>>[]=[];if(isSupabaseConfigured()){let query=createServiceClient().from("profiles").select("*").eq("account_status","active").eq("profile_visibility","public").not("username","is",null).order("created_at",{ascending:false}).limit(40);if(q){const clean=q.replace(/[%_,()]/g,"");query=query.or(`username.ilike.%${clean}%,display_name.ilike.%${clean}%`);}const {data}=await query;items=(await Promise.all((data||[]).map(publicProfileFromRow))).filter((item):item is NonNullable<Awaited<ReturnType<typeof publicProfileFromRow>>>=>Boolean(item));}return <div className="page-stack profiles-directory"><PageHeading eyebrow="Dobrovolné veřejné profily" title="Studentské profily" description="Vyhledejte autora příspěvku nebo nabídky. E-maily a interní údaje se nikdy nezobrazují."/><form className="profile-search"><Search/><label className="sr-only" htmlFor="profile-search">Hledat profil</label><input id="profile-search" name="q" defaultValue={q} placeholder="Přezdívka nebo @uživatelské-jméno"/><button className="button button-primary">Hledat</button></form>{items.length?<div className="profiles-grid">{items.map((profile)=><Link className="profile-directory-card" href={`/profil/${profile.username}`} key={profile.username}><span className="profile-avatar">{profile.avatarUrl?<Image src={profile.avatarUrl} alt="" width={52} height={52} unoptimized/>:profile.displayName.slice(0,2).toUpperCase()}</span><span><strong>{profile.displayName}</strong><small>@{profile.username}</small>{profile.bio&&<p>{profile.bio}</p>}</span></Link>)}</div>:<div className="empty-state"><Users/><h2>Žádný odpovídající veřejný profil</h2><p>Soukromé a nedokončené profily se ve vyhledávání nezobrazují.</p></div>}</div>;}
