import { NextResponse } from "next/server";
import { jobSubmissionSchema } from "@/lib/schemas";
import { createServiceClient } from "@/lib/supabase-server";
import { getCurrentAccount } from "@/lib/user-auth";

type Context={params:Promise<{id:string}>};
async function owned(id:string){const account=await getCurrentAccount();if(!account)return null;const{data}=await createServiceClient().from("submissions").select("*").eq("id",id).eq("type","job").eq("author_id",account.id).maybeSingle();return data?{account,row:data}:null}
export async function GET(_request:Request,context:Context){const result=await owned((await context.params).id);return result?NextResponse.json({item:{id:result.row.id,status:result.row.status,content:result.row.content,moderationNote:result.row.moderation_note||null}},{headers:{"Cache-Control":"private, no-store"}}):NextResponse.json({message:"Návrh nebyl nalezen."},{status:404})}
export async function PATCH(request:Request,context:Context){const result=await owned((await context.params).id);if(!result)return NextResponse.json({message:"Návrh nebyl nalezen."},{status:404});if(!result.account.complete||result.account.accountStatus!=="active")return NextResponse.json({message:"Profil není připravený k úpravám."},{status:403});const input=await request.json().catch(()=>null);if(input?.action==="withdraw"){if(!["pending","rejected"].includes(String(result.row.status)))return NextResponse.json({message:"Tento návrh už nelze stáhnout."},{status:409});await createServiceClient().from("submissions").update({status:"archived"}).eq("id",result.row.id).eq("author_id",result.account.id);return NextResponse.json({message:"Návrh byl stažen."})}if(!["pending","rejected","approved"].includes(String(result.row.status)))return NextResponse.json({message:"Tento návrh už nelze upravit."},{status:409});const parsed=jobSubmissionSchema.safeParse(input);if(!parsed.success)return NextResponse.json({message:"Zkontrolujte vyplněné údaje.",issues:parsed.error.flatten().fieldErrors},{status:422});const value=parsed.data;const content={companyName:value.companyName,title:value.title,contactEmail:value.contactEmail,location:value.location,reward:value.reward,workload:value.workload,description:value.description};const{error}=await createServiceClient().from("submissions").update({content,submitter_contact:value.contactEmail,consent_at:new Date().toISOString(),status:"pending",moderation_note:null,moderated_by:null,moderated_at:null}).eq("id",result.row.id).eq("author_id",result.account.id);if(error)return NextResponse.json({message:"Návrh se nepodařilo upravit."},{status:422});return NextResponse.json({message:"Úpravy byly odeslány ke kontrole.",status:"pending"})}
export async function DELETE(_request:Request,context:Context){const result=await owned((await context.params).id);if(!result)return NextResponse.json({message:"Návrh nebyl nalezen."},{status:404});if(result.row.status==="deleted")return NextResponse.json({message:"Návrh nebyl nalezen."},{status:404});await createServiceClient().from("submissions").update({status:"deleted",submitter_contact:null}).eq("id",result.row.id).eq("author_id",result.account.id);return new NextResponse(null,{status:204})}
