import type { AcademicCatalog, Faculty, University } from "@/lib/types";

const verifiedAt = "2026-09-28T00:00:00.000Z";

export const universities: University[] = [
  { id: "muni", slug: "muni", name: "Masarykova univerzita", shortName: "MUNI", color: "#2856a4", officialUrl: "https://www.muni.cz/", active: true, lastVerifiedAt: verifiedAt, cityIds: ["brno"] },
  { id: "vut", slug: "vut", name: "Vysoké učení technické v Brně", shortName: "VUT", color: "#4f46e5", officialUrl: "https://www.vut.cz/", active: true, lastVerifiedAt: verifiedAt, cityIds: ["brno"] },
  { id: "mendelu", slug: "mendelu", name: "Mendelova univerzita v Brně", shortName: "MENDELU", color: "#475569", officialUrl: "https://mendelu.cz/", active: true, lastVerifiedAt: verifiedAt, cityIds: ["brno"] },
  { id: "vetuni", slug: "vetuni", name: "Veterinární univerzita Brno", shortName: "VETUNI", color: "#7b4e2d", officialUrl: "https://www.vetuni.cz/", active: true, lastVerifiedAt: verifiedAt, cityIds: ["brno"] },
  { id: "jamu", slug: "jamu", name: "Janáčkova akademie múzických umění", shortName: "JAMU", color: "#7c3a68", officialUrl: "https://www.jamu.cz/", active: true, lastVerifiedAt: verifiedAt, cityIds: ["brno"] },
  { id: "upol", slug: "upol", name: "Univerzita Palackého v Olomouci", shortName: "UP", color: "#1f4e79", officialUrl: "https://www.upol.cz/", active: true, lastVerifiedAt: verifiedAt, cityIds: ["olomouc"] },
  { id: "cuni", slug: "cuni", name: "Univerzita Karlova", shortName: "UK", color: "#a51c30", officialUrl: "https://cuni.cz/", active: true, lastVerifiedAt: verifiedAt, cityIds: ["praha"] },
  { id: "cvut", slug: "cvut", name: "České vysoké učení technické v Praze", shortName: "ČVUT", color: "#0065bd", officialUrl: "https://www.cvut.cz/", active: true, lastVerifiedAt: verifiedAt, cityIds: ["praha"] },
  { id: "vse", slug: "vse", name: "Vysoká škola ekonomická v Praze", shortName: "VŠE", color: "#008fbe", officialUrl: "https://www.vse.cz/", active: true, lastVerifiedAt: verifiedAt, cityIds: ["praha"] },
  { id: "czu", slug: "czu", name: "Česká zemědělská univerzita v Praze", shortName: "ČZU", color: "#3b7d23", officialUrl: "https://www.czu.cz/", active: true, lastVerifiedAt: verifiedAt, cityIds: ["praha"] },
  { id: "vscht", slug: "vscht", name: "Vysoká škola chemicko-technologická v Praze", shortName: "VŠCHT", color: "#1f4e79", officialUrl: "https://www.vscht.cz/", active: true, lastVerifiedAt: verifiedAt, cityIds: ["praha"] },
];

const faculty = (id: string, universityId: string, name: string, shortName: string, officialUrl: string): Faculty => ({ id, slug: id, universityId, name, shortName, officialUrl, active: true, lastVerifiedAt: verifiedAt });
export const faculties: Faculty[] = [
  faculty("muni-fi", "muni", "Fakulta informatiky", "FI", "https://www.fi.muni.cz/"), faculty("muni-prf", "muni", "Přírodovědecká fakulta", "PřF", "https://www.sci.muni.cz/"), faculty("muni-ff", "muni", "Filozofická fakulta", "FF", "https://www.phil.muni.cz/"), faculty("muni-fss", "muni", "Fakulta sociálních studií", "FSS", "https://www.fss.muni.cz/"), faculty("muni-esf", "muni", "Ekonomicko-správní fakulta", "ESF", "https://www.econ.muni.cz/"), faculty("muni-lf", "muni", "Lékařská fakulta", "LF", "https://www.med.muni.cz/"), faculty("muni-prav", "muni", "Právnická fakulta", "PrF", "https://www.law.muni.cz/"), faculty("muni-pedf", "muni", "Pedagogická fakulta", "PdF", "https://www.ped.muni.cz/"), faculty("muni-fsps", "muni", "Fakulta sportovních studií", "FSpS", "https://www.fsps.muni.cz/"), faculty("muni-faf", "muni", "Farmaceutická fakulta", "FaF", "https://www.pharm.muni.cz/"),
  faculty("vut-fekt", "vut", "Fakulta elektrotechniky a komunikačních technologií", "FEKT", "https://www.fekt.vut.cz/"), faculty("vut-fit", "vut", "Fakulta informačních technologií", "FIT", "https://www.fit.vut.cz/"), faculty("vut-fast", "vut", "Fakulta stavební", "FAST", "https://www.fce.vut.cz/"), faculty("vut-fsi", "vut", "Fakulta strojního inženýrství", "FSI", "https://www.fme.vutbr.cz/"), faculty("vut-fa", "vut", "Fakulta architektury", "FA", "https://www.fa.vut.cz/"), faculty("vut-fch", "vut", "Fakulta chemická", "FCH", "https://www.fch.vut.cz/"), faculty("vut-fp", "vut", "Fakulta podnikatelská", "FP", "https://www.fp.vut.cz/"), faculty("vut-favu", "vut", "Fakulta výtvarných umění", "FaVU", "https://www.favu.vut.cz/"),
  faculty("mendelu-af", "mendelu", "Agronomická fakulta", "AF", "https://af.mendelu.cz/"), faculty("mendelu-ldf", "mendelu", "Lesnická a dřevařská fakulta", "LDF", "https://ldf.mendelu.cz/"), faculty("mendelu-pef", "mendelu", "Provozně ekonomická fakulta", "PEF", "https://pef.mendelu.cz/"), faculty("mendelu-zf", "mendelu", "Zahradnická fakulta", "ZF", "https://zf.mendelu.cz/"), faculty("mendelu-frrms", "mendelu", "Fakulta regionálního rozvoje a mezinárodních studií", "FRRMS", "https://frrms.mendelu.cz/"),
  faculty("vetuni-fvl", "vetuni", "Fakulta veterinárního lékařství", "FVL", "https://fvl.vetuni.cz/"), faculty("vetuni-fvhe", "vetuni", "Fakulta veterinární hygieny a ekologie", "FVHE", "https://fvhe.vetuni.cz/"),
  faculty("jamu-hf", "jamu", "Hudební fakulta", "HF", "https://hf.jamu.cz/"), faculty("jamu-df", "jamu", "Divadelní fakulta", "DF", "https://df.jamu.cz/"),
  faculty("upol-cmtf", "upol", "Cyrilometodějská teologická fakulta", "CMTF", "https://www.cmtf.upol.cz/"), faculty("upol-lf", "upol", "Lékařská fakulta", "LF", "https://www.lf.upol.cz/"), faculty("upol-ff", "upol", "Filozofická fakulta", "FF", "https://www.ff.upol.cz/"), faculty("upol-prf", "upol", "Přírodovědecká fakulta", "PřF", "https://www.prf.upol.cz/"), faculty("upol-pdf", "upol", "Pedagogická fakulta", "PdF", "https://www.pdf.upol.cz/"), faculty("upol-ftk", "upol", "Fakulta tělesné kultury", "FTK", "https://ftk.upol.cz/"), faculty("upol-pf", "upol", "Právnická fakulta", "PF", "https://www.pf.upol.cz/"), faculty("upol-fzv", "upol", "Fakulta zdravotnických věd", "FZV", "https://www.fzv.upol.cz/"),
  faculty("cuni-ktf", "cuni", "Katolická teologická fakulta", "KTF", "https://ktf.cuni.cz/"), faculty("cuni-etf", "cuni", "Evangelická teologická fakulta", "ETF", "https://web.etf.cuni.cz/"), faculty("cuni-htf", "cuni", "Husitská teologická fakulta", "HTF", "https://htf.cuni.cz/"), faculty("cuni-prf", "cuni", "Právnická fakulta", "PrF", "https://www.prf.cuni.cz/"),
  faculty("cuni-lf1", "cuni", "1. lékařská fakulta", "1. LF", "https://www.lf1.cuni.cz/"), faculty("cuni-lf2", "cuni", "2. lékařská fakulta", "2. LF", "https://www.lf2.cuni.cz/"), faculty("cuni-lf3", "cuni", "3. lékařská fakulta", "3. LF", "https://www.lf3.cuni.cz/"), faculty("cuni-ff", "cuni", "Filozofická fakulta", "FF", "https://www.ff.cuni.cz/"), faculty("cuni-prirod", "cuni", "Přírodovědecká fakulta", "PřF", "https://natur.cuni.cz/"), faculty("cuni-mff", "cuni", "Matematicko-fyzikální fakulta", "MFF", "https://www.mff.cuni.cz/"), faculty("cuni-pedf", "cuni", "Pedagogická fakulta", "PedF", "https://pedf.cuni.cz/"), faculty("cuni-fsv", "cuni", "Fakulta sociálních věd", "FSV", "https://fsv.cuni.cz/"), faculty("cuni-fhs", "cuni", "Fakulta humanitních studií", "FHS", "https://fhs.cuni.cz/"), faculty("cuni-ftvs", "cuni", "Fakulta tělesné výchovy a sportu", "FTVS", "https://ftvs.cuni.cz/"),
  faculty("cvut-fsv", "cvut", "Fakulta stavební", "FSv", "https://www.fsv.cvut.cz/"), faculty("cvut-fs", "cvut", "Fakulta strojní", "FS", "https://fs.cvut.cz/"), faculty("cvut-fel", "cvut", "Fakulta elektrotechnická", "FEL", "https://fel.cvut.cz/"), faculty("cvut-fjfi", "cvut", "Fakulta jaderná a fyzikálně inženýrská", "FJFI", "https://fjfi.cvut.cz/"), faculty("cvut-fa", "cvut", "Fakulta architektury", "FA", "https://www.fa.cvut.cz/"), faculty("cvut-fd", "cvut", "Fakulta dopravní", "FD", "https://www.fd.cvut.cz/"), faculty("cvut-fbmi", "cvut", "Fakulta biomedicínského inženýrství", "FBMI", "https://www.fbmi.cvut.cz/"), faculty("cvut-fit", "cvut", "Fakulta informačních technologií", "FIT", "https://fit.cvut.cz/"),
  faculty("vse-ffu", "vse", "Fakulta financí a účetnictví", "FFÚ", "https://ffu.vse.cz/"), faculty("vse-fmv", "vse", "Fakulta mezinárodních vztahů", "FMV", "https://fmv.vse.cz/"), faculty("vse-fph", "vse", "Fakulta podnikohospodářská", "FPH", "https://fph.vse.cz/"), faculty("vse-fis", "vse", "Fakulta informatiky a statistiky", "FIS", "https://fis.vse.cz/"), faculty("vse-nf", "vse", "Národohospodářská fakulta", "NF", "https://nf.vse.cz/"),
  faculty("czu-fappz", "czu", "Fakulta agrobiologie, potravinových a přírodních zdrojů", "FAPPZ", "https://www.fappz.czu.cz/"), faculty("czu-pef", "czu", "Provozně ekonomická fakulta", "PEF", "https://www.pef.czu.cz/"), faculty("czu-tf", "czu", "Technická fakulta", "TF", "https://www.tf.czu.cz/"), faculty("czu-fld", "czu", "Fakulta lesnická a dřevařská", "FLD", "https://www.fld.czu.cz/"), faculty("czu-fzp", "czu", "Fakulta životního prostředí", "FŽP", "https://www.fzp.czu.cz/"), faculty("czu-ftz", "czu", "Fakulta tropického zemědělství", "FTZ", "https://www.ftz.czu.cz/"),
  faculty("vscht-fcht", "vscht", "Fakulta chemické technologie", "FCHT", "https://fcht.vscht.cz/"), faculty("vscht-ftop", "vscht", "Fakulta technologie ochrany prostředí", "FTOP", "https://ftop.vscht.cz/"), faculty("vscht-fpbt", "vscht", "Fakulta potravinářské a biochemické technologie", "FPBT", "https://fpbt.vscht.cz/"), faculty("vscht-fchi", "vscht", "Fakulta chemicko-inženýrská", "FCHI", "https://fchi.vscht.cz/"),
];

export const fallbackAcademicCatalog: AcademicCatalog = { universities, faculties };

export function universityById(id?: string | null) { return universities.find((item) => item.id === id); }
export function facultiesFor(universityId?: string | null) { return faculties.filter((item) => item.universityId === universityId); }
export function facultyById(id?: string | null) { return faculties.find((item) => item.id === id); }
export function universitiesForCity(cityId: string, catalog: AcademicCatalog = fallbackAcademicCatalog) { return catalog.universities.filter((item) => item.active && item.cityIds.includes(cityId)); }
export function academicCatalogForCity(cityId: string, catalog: AcademicCatalog = fallbackAcademicCatalog): AcademicCatalog { const selectedUniversities = universitiesForCity(cityId, catalog); const ids = new Set(selectedUniversities.map((item) => item.id)); return { universities: selectedUniversities, faculties: catalog.faculties.filter((item) => item.active && ids.has(item.universityId)) }; }
export function resolveStudySelection(universityId?: string | null, facultyId?: string | null, catalog: AcademicCatalog = fallbackAcademicCatalog) {
  const university = catalog.universities.find((item) => item.id === universityId && item.active);
  const faculty = university ? catalog.faculties.find((item) => item.id === facultyId && item.universityId === university.id && item.active) : undefined;
  return { universityId: university?.id || "", facultyId: faculty?.id || "" };
}
