import type { AcademicEvent, Job, Offer, Place } from "@/lib/types";

const verifiedAt = "2026-08-01T00:00:00+02:00";

export const verifiedAcademicEvents: AcademicEvent[] = [
  { id: "muni-semester-start-2026", externalId: "muni-2026-semester-start", title: "Začátek podzimního semestru 2026", category: "Začátek semestru", school: "MUNI", faculty: "Všechny fakulty", start: "2026-09-01T00:00:00+02:00", allDay: true, timezone: "Europe/Prague", academicYear: "2026/2027", source: "Kalendář Masarykovy univerzity", sourceId: "src-muni-fi", sourceUrl: "https://www.muni.cz/kalendar/zari-2026", updatedAt: "2026-08-01", lastVerifiedAt: verifiedAt, description: "Oficiálně zveřejněný začátek podzimního semestru. Začátek výuky se může lišit podle fakulty.", confidence: 0.98, status: "approved", scope: "university", universityId: "muni" },
  { id: "vut-fit-teaching-winter-2026", externalId: "fit-2026-winter-teaching", title: "Výuka v zimním semestru FIT VUT", category: "Výuka", school: "VUT", faculty: "FIT", start: "2026-09-14T00:00:00+02:00", end: "2026-12-11T23:59:59+01:00", allDay: true, timezone: "Europe/Prague", academicYear: "2026/2027", source: "Časový plán FIT VUT 2026/2027", sourceId: "src-vut-fit", sourceUrl: "https://www.fit.vut.cz/study/calendar/2026/.cs", updatedAt: "2026-08-01", lastVerifiedAt: verifiedAt, description: "Období výuky v zimním semestru podle veřejného časového plánu FIT VUT.", confidence: 1, status: "approved", scope: "faculty", universityId: "vut", facultyId: "vut-fit" },
  { id: "vut-fit-exams-winter-2027", externalId: "fit-2026-winter-exams", title: "Zkouškové období zimního semestru FIT VUT", category: "Zkouškové období", school: "VUT", faculty: "FIT", start: "2027-01-04T00:00:00+01:00", end: "2027-02-05T23:59:59+01:00", allDay: true, timezone: "Europe/Prague", academicYear: "2026/2027", source: "Časový plán FIT VUT 2026/2027", sourceId: "src-vut-fit", sourceUrl: "https://www.fit.vut.cz/study/calendar/2026/.cs", updatedAt: "2026-08-01", lastVerifiedAt: verifiedAt, description: "Zkouškové období zimního semestru zveřejněné FIT VUT.", confidence: 1, status: "approved", scope: "faculty", universityId: "vut", facultyId: "vut-fit" },
  { id: "vut-fsi-teaching-winter-2026", externalId: "fsi-2026-winter-teaching", title: "Zahájení výuky v zimním semestru FSI VUT", category: "Výuka", school: "VUT", faculty: "FSI", start: "2026-09-14T00:00:00+02:00", allDay: true, timezone: "Europe/Prague", academicYear: "2026/2027", source: "Časový plán studia FSI VUT", sourceId: "src-vut-fsi", sourceUrl: "https://www.fme.vutbr.cz/studenti/plan?degree=0&mode=0&year=2026", updatedAt: "2026-08-01", lastVerifiedAt: verifiedAt, description: "Zahájení výuky zveřejněné v časovém plánu FSI pro akademický rok 2026/2027.", confidence: 0.98, status: "approved", scope: "faculty", universityId: "vut", facultyId: "vut-fsi" },
  { id: "mendelu-pef-teaching-winter-2026", externalId: "pef-2026-winter-teaching", title: "Výuka v zimním semestru PEF MENDELU", category: "Výuka", school: "MENDELU", faculty: "PEF", start: "2026-09-21T00:00:00+02:00", end: "2026-12-20T23:59:59+01:00", allDay: true, timezone: "Europe/Prague", academicYear: "2026/2027", source: "Úřední deska PEF MENDELU", sourceId: "src-mendelu-pef", sourceUrl: "https://pef.mendelu.cz/o-fakulte/uredni-deska/", updatedAt: "2026-08-01", lastVerifiedAt: verifiedAt, description: "Rozvrhovaná výuka v zimním semestru podle zveřejněného harmonogramu PEF.", confidence: 1, status: "approved", scope: "faculty", universityId: "mendelu", facultyId: "mendelu-pef" },
  { id: "mendelu-pef-exams-winter-2027", externalId: "pef-2026-winter-exams", title: "Zkouškové období zimního semestru PEF MENDELU", category: "Zkouškové období", school: "MENDELU", faculty: "PEF", start: "2026-12-21T00:00:00+01:00", end: "2027-02-05T23:59:59+01:00", allDay: true, timezone: "Europe/Prague", academicYear: "2026/2027", source: "Úřední deska PEF MENDELU", sourceId: "src-mendelu-pef", sourceUrl: "https://pef.mendelu.cz/o-fakulte/uredni-deska/", updatedAt: "2026-08-01", lastVerifiedAt: verifiedAt, description: "Zkouškové období podle veřejného harmonogramu PEF MENDELU.", confidence: 1, status: "approved", scope: "faculty", universityId: "mendelu", facultyId: "mendelu-pef" },
  { id: "vetuni-teaching-winter-2026", externalId: "vetuni-2026-winter-teaching", title: "Výuka v zimním semestru VETUNI", category: "Výuka", school: "VETUNI", faculty: "FVL a FVHE", start: "2026-09-14T00:00:00+02:00", end: "2026-12-11T23:59:59+01:00", allDay: true, timezone: "Europe/Prague", academicYear: "2026/2027", source: "Rozpis výuky VETUNI 2026/2027", sourceId: "src-vetuni-fvl", sourceUrl: "https://www.vetuni.cz/files/articles/rozpis-vyuky-vetuni-2026-27-1763708605.pdf", updatedAt: "2026-08-01", lastVerifiedAt: verifiedAt, description: "Společný rozpis výuky; pro šestý ročník mohou platit zvláštní fakultní termíny.", confidence: 0.96, status: "approved", scope: "university", universityId: "vetuni" },
  { id: "jamu-hf-registration-winter-2026", externalId: "jamu-hf-zima-2026-registration", title: "Registrace předmětů na HF JAMU", category: "Registrace předmětů", school: "JAMU", faculty: "HF", start: "2026-08-03T17:00:00+02:00", end: "2026-08-31T23:59:59+02:00", allDay: false, timezone: "Europe/Prague", academicYear: "2026/2027", source: "Veřejný přehled období IS JAMU", sourceId: "src-jamu-hf", sourceUrl: "https://is.jamu.cz/predmety/obdobi?fakulta=5451%3Bid%3D718", updatedAt: "2026-08-01", lastVerifiedAt: verifiedAt, description: "Veřejně dostupné období registrace předmětů pro zimní semestr 2026.", confidence: 0.98, status: "approved", scope: "faculty", universityId: "jamu", facultyId: "jamu-hf" },
  { id: "jamu-df-teaching-winter-2026", externalId: "jamu-df-zima-2026-teaching", title: "Výuka v zimním semestru Divadelní fakulty JAMU", category: "Výuka", school: "JAMU", faculty: "DF", start: "2026-10-05T00:00:00+02:00", end: "2027-01-10T23:59:59+01:00", allDay: true, timezone: "Europe/Prague", academicYear: "2026/2027", source: "Veřejný přehled období IS JAMU", sourceId: "src-jamu-df", sourceUrl: "https://is.jamu.cz/predmety/obdobi?fakulta=5451%3Bid%3D718", updatedAt: "2026-08-01", lastVerifiedAt: verifiedAt, description: "Období výuky zveřejněné ve veřejném přehledu období JAMU.", confidence: 0.98, status: "approved", scope: "faculty", universityId: "jamu", facultyId: "jamu-df" },
];

export const verifiedPlaces: Place[] = [
  { id: "place-muni-kuk", name: "Knihovna univerzitního kampusu MUNI", category: "Knihovna", address: "Kamenice 753/5, Brno, budova B09", hours: "Po–Čt 8:00–19:00, Pá 8:00–18:00, So 8:00–15:00", website: "https://www.muni.cz/o-univerzite/fakulty-a-pracoviste/sprava-univerzitniho-kampusu-bohunice/824000-knihovna-univerzitniho-kampusu/o-pracovisti", sourceUrl: "https://www.muni.cz/o-univerzite/fakulty-a-pracoviste/sprava-univerzitniho-kampusu-bohunice/824000-knihovna-univerzitniho-kampusu/o-pracovisti", lastVerifiedAt: verifiedAt, verificationStatus: "verified", lat: 49.1776, lng: 16.5698, note: "Knihovna v kampusu Bohunice; aktuální omezení provozu ověřte před cestou na webu.", universityIds: ["muni"], facultyIds: ["muni-lf", "muni-prf", "muni-fsps"], campus: "Bohunice" },
  { id: "place-vut-central-library", name: "Ústřední knihovna VUT", category: "Knihovna", address: "Kolejní 2906/4, Brno", hours: "Po–Pá 8:00–18:00", website: "https://www.vut.cz/knihovny/seznam", sourceUrl: "https://www.vut.cz/knihovny/seznam", lastVerifiedAt: verifiedAt, verificationStatus: "verified", lat: 49.2304, lng: 16.5727, note: "Ústřední knihovna a studijní zázemí VUT v areálu Pod Palackého vrchem.", universityIds: ["vut"], campus: "Pod Palackého vrchem" },
  { id: "place-vut-fekt-library", name: "Areálová knihovna FEKT VUT", category: "Knihovna", address: "Technická 12, Brno", hours: "Letní provoz se mění; ověřte aktuální rozpis na webu", website: "https://www.fekt.vut.cz/o_fakulte/organizacni_struktura/knihovna_doba", sourceUrl: "https://www.fekt.vut.cz/o_fakulte/organizacni_struktura/knihovna_doba", lastVerifiedAt: verifiedAt, verificationStatus: "verified", lat: 49.2267, lng: 16.5757, note: "Knihovna FEKT zveřejňuje sezónní změny otevírací doby.", universityIds: ["vut"], facultyIds: ["vut-fekt"], campus: "Pod Palackého vrchem" },
  { id: "place-mendelu-evening-study", name: "Večerní studovna MENDELU", category: "Studovna", address: "Zemědělská 1, Brno, budova A", hours: "Po–Pá 6:00–22:00, So–Ne 8:00–20:00", website: "https://uvis.mendelu.cz/en/study-rooms", sourceUrl: "https://uvis.mendelu.cz/en/study-rooms", lastVerifiedAt: verifiedAt, verificationStatus: "verified", lat: 49.2107, lng: 16.6158, note: "Studovna je přístupná s platnou studentskou nebo zaměstnaneckou kartou.", universityIds: ["mendelu"], campus: "Černá Pole" },
  { id: "place-vetuni-library", name: "Univerzitní knihovna VETUNI", category: "Knihovna", address: "Palackého třída 1946/1, Brno, budova 24", hours: "Provoz se mění podle období; ověřte aktuální tabulku na webu", website: "https://www.vetuni.cz/studijni-a-informacni-stredisko", sourceUrl: "https://www.vetuni.cz/navody/datab/informace-o-knihovne", lastVerifiedAt: verifiedAt, verificationStatus: "verified", lat: 49.2181, lng: 16.5958, note: "Knihovna se nachází ve 4. patře Studijního a informačního centra.", universityIds: ["vetuni"], campus: "Královo Pole" },
  { id: "place-jamu-library", name: "Knihovna JAMU", category: "Knihovna", address: "Novobranská 3, Brno", hours: "Po, St 9:00–18:00; Út, Čt 9:00–17:00; Pá 9:00–15:00", website: "https://www.jamu.cz/jamu/fakulty-a-soucasti-jamu/knihovna-jamu/", sourceUrl: "https://www.jamu.cz/jamu/fakulty-a-soucasti-jamu/knihovna-jamu/", lastVerifiedAt: verifiedAt, verificationStatus: "verified", lat: 49.1949, lng: 16.6116, note: "Specializovaný fond pro hudební a divadelní obory; provozní změny sledujte na webu.", universityIds: ["jamu"], campus: "Centrum" },
  { id: "place-muni-canteen-vinarska", name: "Menza Vinařská MUNI", category: "Menza", address: "Vinařská 499/5, Brno", website: "https://www.skm.muni.cz/stravovani/menzy-muni/menza-vinarska", sourceUrl: "https://www.skm.muni.cz/stravovani/menzy-muni/menza-vinarska", lastVerifiedAt: verifiedAt, verificationStatus: "verified", lat: 49.1879, lng: 16.5849, note: "Jídelníček a aktuální provozní dobu ověřte na webu Správy kolejí a menz MUNI.", universityIds: ["muni"], campus: "Vinařská" },
];

export const verifiedOffers: Offer[] = [];
export const verifiedJobs: Job[] = [];

export const verifiedFallbackData = { academic_events: verifiedAcademicEvents, places: verifiedPlaces, offers: verifiedOffers, jobs: verifiedJobs };
