import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";
import { CookieSettingsButton } from "@/components/legal-links";
import { legalDocuments, operator } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Zásady používání cookies a lokálního úložiště",
  description: "Jak StudentHub používá cookies, lokální a relační úložiště a jak lze změnit volitelný souhlas.",
  alternates: { canonical: "https://studenthubapp.cz/cookies" },
  openGraph: { title: "Cookies | StudentHub", description: "Cookies a úložiště prohlížeče ve StudentHubu.", url: "https://studenthubapp.cz/cookies", locale: "cs_CZ", type: "article" },
};

const sections = [
  ["co-jsou", "Co jsou cookies a lokální úložiště"], ["kategorie", "Používané kategorie"], ["technicke", "Technické prostředky"],
  ["analyticke", "Analytické cookies"], ["marketingove", "Marketingové cookies"], ["volba", "Jak funguje volba"],
  ["odvolani", "Změna nebo odvolání souhlasu"], ["doba", "Doba uchování volby"], ["treti-strany", "Služby třetích stran"],
  ["pravni-rezim", "Právní režim"], ["prohlizec", "Nastavení prohlížeče"], ["zmeny", "Změny zásad"], ["kontakt", "Kontakt"],
].map(([id, label]) => ({ id, label }));

export default function CookiesPage() {
  const document = legalDocuments.cookies;
  return <LegalPage title="Zásady používání cookies a lokálního úložiště StudentHub" description="Technické prostředky udržují službu bezpečnou. Volitelná analytika se spustí pouze po vašem souhlasu." version={document.version} effectiveDate={document.effectiveDate} updatedDate={document.updatedDate} sections={sections}>
    <p>Tyto zásady vysvětlují, jak platforma StudentHub, dostupná zejména na adrese <a href="https://studenthubapp.cz">studenthubapp.cz</a>, používá cookies, lokální úložiště prohlížeče a obdobné technologie.</p>
    <p>Cookies a podobné technologie používáme pouze v rozsahu popsaném níže. Technické prostředky nezbytné pro fungování, zabezpečení a uživatelem vyžádané funkce mohou být používány bez marketingového souhlasu. Analytické a marketingové technologie jsou ve výchozím stavu vypnuté a mohou být aktivovány až po odpovídající volbě uživatele.</p>

    <section id="co-jsou"><h2>1. Co jsou cookies a lokální úložiště</h2><p>Cookies jsou malé datové soubory, které webová stránka ukládá do zařízení uživatele prostřednictvím internetového prohlížeče.</p><p>Lokální úložiště (<code>localStorage</code>) je obdobný mechanismus pro ukládání informací přímo v prohlížeči uživatele. Na rozdíl od běžné cookie se obsah <code>localStorage</code> neposílá automaticky při každém požadavku na server.</p><p>Relační úložiště (<code>sessionStorage</code>) uchovává údaje pro právě otevřenou kartu. Pro účely těchto zásad používáme pojem „cookies“ také obecně pro obdobné technologie ukládající nebo čtoucí informace v zařízení uživatele, pokud z kontextu nevyplývá něco jiného.</p></section>

    <section id="kategorie"><h2>2. Jaké kategorie používáme</h2><p>StudentHub rozlišuje tyto kategorie:</p><ol><li>technické a nezbytné cookies a lokální úložiště,</li><li>analytické cookies,</li><li>marketingové cookies.</li></ol><p>Technické prostředky jsou aktivní pouze v rozsahu potřebném pro požadované funkce. Analytické a marketingové prostředky nejsou aktivovány bez předchozí volby uživatele.</p></section>

    <section id="technicke"><h2>3. Technické cookies a lokální úložiště</h2><p>Technické cookies a lokální úložiště používáme k zajištění bezpečného a správného fungování StudentHubu a uživatelem vyžádaných funkcí.</p><p>Slouží zejména k:</p><ul><li>bezpečné správě přihlášení a relace prostřednictvím Supabase,</li><li>správě administrátorské relace tam, kde je relevantní,</li><li>rozpoznání vlastních požadavků a ochraně proti zneužití,</li><li>zapamatování volby uživatele v oblasti cookies,</li><li>uložení motivu vzhledu,</li><li>uložení vybraného města,</li><li>uložení vybrané školy,</li><li>uložení vybrané fakulty.</li></ul><p>Tyto prostředky nejsou používány k reklamnímu profilování ani k marketingovému sledování.</p><h3>Přehled technických prostředků</h3><div className="legal-table-scroll"><table><thead><tr><th>Prostředek</th><th>Typ</th><th>Účel</th><th>Kdy se používá</th><th>Doba uložení</th></tr></thead><tbody>
      <tr><td><code>sb-&lt;projekt&gt;-auth-token</code> včetně případných číslovaných částí a PKCE verifieru</td><td>HttpOnly cookie první strany</td><td>Přihlášení přes Supabase Auth, zabezpečení relace, obnova relace a jednorázový callback</td><td>Pouze pokud uživatel využívá funkci vyžadující přihlášení</td><td>Podle životnosti relace Supabase; přístupový token nyní 3 600 sekund a relace se obnovuje rotovaným refresh tokenem</td></tr>
      <tr><td>Administrátorská session</td><td>Stejná Supabase autentizační cookie</td><td>Zabezpečené přihlášení oprávněného administrátora</td><td>Pouze v administraci</td><td>Podle stejné životnosti relace Supabase; administrace nepoužívá samostatný autentizační systém</td></tr>
      <tr><td><code>sh_installation</code></td><td>HttpOnly cookie první strany</td><td>Náhodný identifikátor instalace pro ochranu proti duplicitám a spamu; server ukládá jen jeho hash</td><td>Při použití funkcí chráněných proti opakovanému hlasování nebo spamu</td><td>Nejvýše 2 roky</td></tr>
      <tr><td><code>sh_help_owner</code></td><td>HttpOnly cookie první strany</td><td>Rozpoznání vlastní anonymní technické žádosti a bezpečná správa jejího stavu</td><td>Při odeslání anonymní žádosti o technickou pomoc</td><td>Nejvýše 1 rok</td></tr>
      <tr><td><code>sh_password_recovery</code></td><td>HttpOnly cookie první strany</td><td>Ochrana jednorázového toku obnovy hesla</td><td>Při obnově hesla</td><td>15 minut</td></tr>
      <tr><td><code>studenthub-consent</code></td><td><code>localStorage</code></td><td>Zapamatování udělené nebo odmítnuté analytické a marketingové volby</td><td>Po provedení volby uživatelem</td><td>Do změny volby nebo smazání dat webu</td></tr>
      <tr><td><code>studenthub-theme</code></td><td><code>localStorage</code></td><td>Zapamatování světlého, tmavého nebo systémového motivu</td><td>Po změně vzhledu uživatelem</td><td>Do změny volby nebo smazání dat webu</td></tr>
      <tr><td><code>studenthub-preference-v4</code></td><td><code>localStorage</code></td><td>Vybrané město, univerzita, fakulta, kampus a ročník bez nutnosti účtu</td><td>Po nastavení preference</td><td>Do změny volby nebo smazání dat webu</td></tr>
      <tr><td><code>studenthub-saved-events-v1</code>, <code>studenthub-event-interests-v1</code>, <code>studenthub-marketplace-favorites-v1</code> a <code>studenthub-place-suggestion-v1</code></td><td><code>localStorage</code></td><td>Uložené akce, zájem, oblíbené inzeráty a rozpracovaný návrh místa</td><td>Po použití příslušné lokální funkce</td><td>Do odebrání uživatelem nebo smazání dat webu</td></tr>
      <tr><td><code>studenthub-tutorial-state</code></td><td><code>localStorage</code></td><td>Stav úvodního potvrzení, průběh a verze návodu</td><td>Po zobrazení nebo použití návodu</td><td>Do nové verze návodu nebo smazání dat webu</td></tr>
      <tr><td>Rozpracované formuláře komunity, akcí a Burzy a <code>studenthub-chat-dock-v1</code></td><td><code>sessionStorage</code></td><td>Obnovení rozpracované práce a stavu chatovacího okna v jedné kartě</td><td>Po použití příslušné funkce</td><td>Do zavření karty nebo ručního smazání</td></tr>
      <tr><td>Referral, analytická relace a jednorázové označení zobrazené stránky</td><td><code>sessionStorage</code></td><td>Po souhlasu zabrání duplicitnímu měření v jedné kartě a přiřadí komunitní referral</td><td>Po souhlasu a při návštěvě příslušné stránky</td><td>Do zavření karty</td></tr>
      <tr><td><code>studenthub-static-v8</code></td><td>Cache Storage</td><td>Offline stránka a verzované statické ikony PWA; dynamické HTML, API, administrace ani osobní údaje se necachují</td><td>Po aktivaci service workeru</td><td>Do instalace nové verze service workeru nebo smazání dat webu</td></tr>
    </tbody></table></div><p>Přihlašovací, instalační, vlastnické a recovery cookies používají <code>Path=/</code>, <code>SameSite=Lax</code> a v produkci <code>Secure</code>. Citlivé cookies jsou <code>HttpOnly</code>, takže k nim nemá přímý přístup klientský JavaScript.</p></section>

    <section id="analyticke"><h2>4. Analytické cookies</h2><p>Analytika StudentHubu je volitelná.</p><p>Bez výslovného souhlasu uživatele:</p><ul><li>nevznikne analytická cookie <code>sh_analytics_consent</code>,</li><li>aplikace neukládá analytická zobrazení stránek,</li><li>nenačítá se žádný externí analytický skript,</li><li>analytické technologie zůstávají vypnuté.</li></ul><p>Po udělení souhlasu může vzniknout technická cookie:</p><div className="legal-table-scroll"><table><thead><tr><th>Název</th><th>Typ</th><th>Účel</th><th>Doba uložení</th></tr></thead><tbody><tr><td><code>sh_analytics_consent</code></td><td>Cookie první strany</td><td>Zaznamenání, že uživatel povolil volitelnou privacy-first analytiku</td><td>Nejvýše 1 rok, do odvolání souhlasu nebo smazání cookie uživatelem</td></tr></tbody></table></div><p>Po udělení souhlasu aplikace odesílá privacy-first zobrazení stránky: cestu bez query parametrů, datum, město a volitelně školu či fakultu, typ zařízení, doménu odkazující stránky, referral kód a pseudonymní hash relace. Vlastní analytická tabulka neukládá jméno, e-mail, přesnou polohu, původní IP adresu ani celý user-agent.</p><p>StudentHub před udělením souhlasu nenačítá žádný externí analytický skript.</p><p>Pokud uživatel analytický souhlas odvolá:</p><ul><li>cookie <code>sh_analytics_consent</code> se smaže,</li><li>další analytická zobrazení stránky se již neukládají,</li><li>odvolání souhlasu nemá zpětný účinek na zpracování, které proběhlo oprávněně před jeho odvoláním.</li></ul><p>Pokud bude v budoucnu přidán externí analytický poskytovatel nebo se změní rozsah odesílaných údajů, budou tyto zásady před spuštěním takové změny aktualizovány.</p></section>

    <section id="marketingove"><h2>5. Marketingové cookies</h2><p>Marketingové cookies a reklamní identifikátory jsou volitelné.</p><p>Ve výchozím a současném produkčním stavu StudentHub:</p><ul><li>nenačítá reklamní skripty třetích stran,</li><li>nevytváří marketingové identifikátory,</li><li>neprovádí marketingové profilování,</li><li>nepředává údaje reklamním sítím za účelem personalizované reklamy.</li></ul><p>Samotné zobrazení neutrálního reklamního prostoru bez sledovací technologie nepředstavuje automaticky marketingové sledování.</p><p>Reklamní a marketingové technologie jsou ve výchozím stavu vypnuté. Pokud budou v budoucnu aktivovány, nesmějí se technologie vyžadující souhlas spustit před jeho udělením.</p><p>Před případným zavedením marketingových cookies musí StudentHub v těchto zásadách uvést zejména:</p><ul><li>název cookie nebo jiné technologie,</li><li>poskytovatele,</li><li>účel,</li><li>dobu uložení,</li><li>zda dochází k profilování,</li><li>komu mohou být údaje předávány,</li><li>zda dochází k předávání mimo Evropský hospodářský prostor.</li></ul></section>

    <section id="volba"><h2>6. Jak funguje volba uživatele</h2><p>Při první návštěvě nebo v situaci, kdy StudentHub již nemá uloženou platnou volbu, je uživateli zobrazena možnost nastavit používání volitelných cookies.</p><p>Uživatel má možnost:</p><ul><li>analytické cookies přijmout,</li><li>analytické cookies odmítnout,</li><li>marketingové cookies přijmout, pokud budou někdy používány,</li><li>marketingové cookies odmítnout,</li><li>ponechat aktivní pouze nezbytné technické prostředky.</li></ul><p>Netechnické cookies ani obdobné technologie vyžadující souhlas nejsou aktivovány jen tím, že uživatel pokračuje v prohlížení stránky, zavře informační okno nebo neprovede žádnou volbu.</p><p>Odmítnutí volitelných cookies nebrání použití funkcí StudentHubu, které tyto cookies objektivně nepotřebují.</p></section>

    <section id="odvolani"><h2>7. Změna nebo odvolání souhlasu</h2><p>Uživatel může svou volbu kdykoli změnit nebo odvolat prostřednictvím odkazu <CookieSettingsButton className="legal-inline-button" /> v navigaci nebo patičce každé stránky.</p><p>Odvolání souhlasu je bezplatné a nemá zpětný účinek.</p><p>Po odvolání analytického souhlasu se:</p><ul><li>smaže cookie <code>sh_analytics_consent</code>,</li><li>zastaví ukládání dalších analytických zobrazení.</li></ul><p>Po případném odvolání marketingového souhlasu se zastaví další používání marketingových technologií, pro které je souhlas nutný.</p><p>Uživatel může cookies a <code>localStorage</code> také smazat přímo v nastavení svého prohlížeče. V takovém případě může být nutné některé volby StudentHubu nastavit znovu.</p></section>

    <section id="doba"><h2>8. Jak dlouho volbu uchováváme</h2><p>Volbu uživatele v <code>studenthub-consent</code> uchováváme do její změny nebo smazání dat webu. Potvrzovací analytická cookie má maximální dobu jeden rok.</p><p>Pokud se významně změní účel zpracování, zapojení poskytovatelé nebo technologie, může být uživatel požádán o novou volbu dříve.</p></section>

    <section id="treti-strany"><h2>9. Cookies třetích stran</h2><p>StudentHub před udělením souhlasu nenačítá externí analytické ani reklamní skripty.</p><p>Externí služby používané pro základní infrastrukturu, zejména Supabase, Vercel, OpenStreetMap, Nominatim a platformní poskytovatel Web Push, mohou v rámci poskytování vyžádané funkce pracovat s technickými údaji nebo autentizačními prostředky. Tyto prostředky jsou používány pouze v rozsahu nezbytném pro poskytovanou funkci. Mapové dlaždice se načítají při zobrazení mapy; adresa se odesílá Nominatimu pouze po uživatelem vyžádaném hledání.</p><p>Externí pracovní odkaz se otevře až po kliknutí uživatele. StudentHub nepoužívá vložená videa ani sociální pluginy, které by samy četly marketingové cookies.</p><p>Pokud StudentHub v budoucnu přidá externí analytiku, reklamní systém, vložené video, sociální plugin nebo jinou službu třetí strany, která ukládá nebo čte netechnické informace v zařízení uživatele, bude před jejím spuštěním posouzen režim souhlasu a tyto zásady aktualizovány.</p></section>

    <section id="pravni-rezim"><h2>10. Právní režim</h2><p>Technické cookies a obdobné technologie používáme pouze tehdy, pokud jsou nezbytné pro:</p><ul><li>přenos komunikace,</li><li>zabezpečení,</li><li>přihlášení,</li><li>uložení uživatelem zvolené preference,</li><li>nebo poskytnutí jiné funkce, kterou uživatel výslovně požaduje.</li></ul><p>Pro takové technické prostředky se nevyžaduje předchozí souhlas s jejich uložením nebo čtením.</p><p>Netechnické technologie, zejména analytické a marketingové cookies, aktivujeme pouze po předchozím souhlasu tam, kde jej vyžadují právní předpisy.</p><p>Pokud prostřednictvím cookies nebo podobných technologií dochází také ke zpracování osobních údajů, musí mít toto zpracování samostatný odpovídající právní základ podle GDPR.</p></section>

    <section id="prohlizec"><h2>11. Nastavení prohlížeče</h2><p>Většina prohlížečů umožňuje cookies:</p><ul><li>zobrazit,</li><li>smazat,</li><li>blokovat,</li><li>omezit jejich použití,</li><li>nebo automaticky odstranit po ukončení relace.</li></ul><p>Zablokování všech cookies nebo odstranění technických údajů může způsobit, že některé funkce StudentHubu, zejména přihlášení, rozpoznání vlastní žádosti nebo zapamatování nastavení, nebudou fungovat správně.</p><p>Smazání <code>localStorage</code> odstraní také lokálně uložené preference, například motiv, vybrané město, školu nebo fakultu, stav návodu a lokálně uložené oblíbené položky.</p></section>

    <section id="zmeny"><h2>12. Změny těchto zásad</h2><p>Tyto zásady můžeme změnit, pokud se změní technologie, používaní poskytovatelé, rozsah analytiky, reklamní funkce nebo právní požadavky.</p><p>Pokud změna ovlivní rozsah zpracování založeného na souhlasu, vyžádáme nový souhlas všude tam, kde je to podle povahy změny nutné.</p><p>Aktuální verze bude vždy dostupná na webu StudentHubu.</p></section>

    <section id="kontakt"><h2>13. Kontakt</h2><p>Máte-li dotaz k používání cookies nebo k ochraně osobních údajů ve StudentHubu, můžete kontaktovat správce:</p><dl className="legal-definition"><div><dt>Správce</dt><dd>{operator.name}, {operator.status}</dd></div><div><dt>E-mail</dt><dd><a href={`mailto:${operator.email}`}>{operator.email}</a></dd></div></dl><p>Další informace o zpracování osobních údajů jsou uvedeny v <Link href="/soukromi">Zásadách ochrany osobních údajů StudentHub</Link>.</p></section>
  </LegalPage>;
}
