import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";
import { legalDocuments, minimumUserAge, operator } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Podmínky a pravidla",
  description: "Pravidla účtů, komunity, chatu, Burzy, moderace a dalších funkcí StudentHubu.",
  alternates: { canonical: "https://studenthubapp.cz/podminky" },
  openGraph: { title: "Podmínky a pravidla | StudentHub", description: "Pravidla bezpečného a férového používání StudentHubu.", url: "https://studenthubapp.cz/podminky", locale: "cs_CZ", type: "article" },
};

const sections = [
  ["provozovatel", "Provozovatel"], ["sluzba", "Co StudentHub poskytuje"], ["ucet", "Účet a používání"],
  ["obsah", "Obecná pravidla obsahu"], ["bezpecnost", "Osobní údaje a bezpečnost"], ["burza", "Studentská burza"],
  ["komunita", "Studentská komunita"], ["chat", "Soukromý chat"], ["autorska-prava", "Autorská práva"],
  ["hlaseni", "Hlášení obsahu"], ["moderace", "Moderace"], ["namitka", "Námitka proti zásahu"],
  ["poruseni", "Závažné porušování"], ["placene", "Placené zvýraznění"], ["spotrebitele", "Placené služby spotřebitelům"],
  ["reklamace", "Reklamace"], ["odpovednost", "Odpovědnost a dostupnost"], ["zmeny", "Změny a ukončení"],
  ["pravo", "Rozhodné právo"], ["adr", "Mimosoudní řešení"], ["kontakt", "Kontakt"], ["zaver", "Závěrečná ustanovení"],
].map(([id, label]) => ({ id, label }));

const List = ({ children }: { children: React.ReactNode }) => <ul>{children}</ul>;

export default function TermsPage() {
  const document = legalDocuments.terms;
  return <LegalPage title="Podmínky a pravidla StudentHub" description="Pravidla chrání studenty, autory i férovou komunikaci. Používáním StudentHubu souhlasíte s těmito podmínkami v rozsahu, v jakém se na vás vztahují." version={document.version} effectiveDate={document.effectiveDate} updatedDate={document.updatedDate} sections={sections}>
    <p>Tyto podmínky upravují používání platformy StudentHub, dostupné zejména na adrese <a href="https://studenthubapp.cz">studenthubapp.cz</a>.</p>

    <section id="provozovatel"><h2>1. Provozovatel StudentHubu</h2><p>Provozovatelem platformy je <strong>{operator.name}, {operator.status}</strong>.</p><dl className="legal-definition"><div><dt>E-mail</dt><dd><a href={`mailto:${operator.email}`}>{operator.email}</a></dd></div></dl><p>StudentHub není oficiálně spojený s žádnou univerzitou, pokud u konkrétní spolupráce není výslovně uvedeno jinak.</p></section>

    <section id="sluzba"><h2>2. Co StudentHub poskytuje</h2><p>StudentHub je studentská online platforma, která může podle aktuálně dostupných funkcí umožňovat zejména:</p><List><li>vytvoření uživatelského účtu a profilu,</li><li>zveřejňování příspěvků a komunitního obsahu,</li><li>soukromou komunikaci mezi uživateli,</li><li>zveřejňování nabídek a poptávek ve Studentské burze,</li><li>zveřejňování nabídek bydlení,</li><li>hledání spolužáků, parťáků nebo jiných kontaktů,</li><li>zobrazování komunitních akcí,</li><li>zobrazování pracovních nebo partnerských nabídek,</li><li>placené zvýraznění vybraného obsahu nebo reklamní pozice, pokud bude tato služba zavedena.</li></List><p>Dostupnost jednotlivých funkcí se může v čase měnit.</p><p>StudentHub není bankou, platební institucí, úschovou peněz, dopravcem ani garantem obchodů uzavíraných mezi uživateli.</p><p>Online objednávky placeného zvýraznění, platby, fakturace ani reklamní síť nejsou v současné produkční verzi aktivní.</p></section>

    <section id="ucet"><h2>3. Účet a používání služby</h2><p>Pro používání některých funkcí může být nutná registrace a ověření e-mailové adresy. Jedinou aktivní metodou přihlášení je e-mail a heslo prostřednictvím Supabase Auth. Volbu školy lze uložit lokálně i bez účtu.</p><p>Uživatel je povinen:</p><List><li>uvádět pravdivé údaje v rozsahu, v jakém jsou pro danou funkci požadovány,</li><li>chránit svůj účet a přístupové údaje před zneužitím,</li><li>nepředávat účet jiné osobě způsobem, který by mohl vést k obcházení pravidel nebo klamání ostatních,</li><li>bez zbytečného odkladu řešit podezření na zneužití účtu,</li><li>neobcházet omezení, blokaci nebo moderátorské opatření novým účtem.</li></List><p>Minimální věk pro registraci a používání uživatelských funkcí StudentHubu je <strong>{minimumUserAge} let</strong>.</p><p>Pokud uživatel nemá podle právních předpisů dostatečnou způsobilost k samostatnému právnímu jednání, musí být používání služby a případné placené objednávky řešeny způsobem odpovídajícím jeho věku a právní způsobilosti.</p></section>

    <section id="obsah"><h2>4. Obecná pravidla obsahu</h2><p>Uživatel odpovídá za obsah, který do StudentHubu vloží nebo odešle.</p><p>Je zakázáno zejména:</p><List><li>zveřejňovat nebo šířit protiprávní obsah,</li><li>porušovat autorská práva, ochranné známky nebo jiná práva třetích osob,</li><li>vydávat cizí obsah za vlastní,</li><li>podvádět nebo uvádět ostatní uživatele v omyl,</li><li>zveřejňovat podvodné nabídky,</li><li>rozesílat spam nebo nevyžádané hromadné zprávy,</li><li>obtěžovat, vyhrožovat nebo cíleně zastrašovat jiné osoby,</li><li>zveřejňovat nenávistný nebo jinak protiprávní diskriminační obsah,</li><li>zveřejňovat obsah podporující nebezpečné nebo protiprávní jednání,</li><li>pokoušet se neoprávněně získat přístup k účtům, datům nebo systémům,</li><li>šířit malware, phishing nebo jiný škodlivý kód,</li><li>obcházet technická nebo moderátorská omezení služby.</li></List><p>StudentHub může mít pro konkrétní funkce další pravidla, která budou uvedena přímo u dané části služby.</p></section>

    <section id="bezpecnost"><h2>5. Osobní údaje a bezpečná komunikace</h2><p>Ve veřejných příspěvcích a komunitních částech nezveřejňujte zbytečně:</p><List><li>e-mailové adresy,</li><li>telefonní čísla,</li><li>soukromé adresy,</li><li>přesnou aktuální polohu,</li><li>školní přihlašovací údaje,</li><li>hesla,</li><li>osobní doklady,</li><li>platební údaje,</li><li>jiné citlivé nebo neveřejné osobní údaje.</li></List><p>Nikdy neposílejte jiné osobě své heslo ke StudentHubu ani heslo ke školnímu systému.</p><p>Podrobnosti o zpracování osobních údajů jsou uvedeny v <Link href="/soukromi">Zásadách ochrany osobních údajů StudentHub</Link>.</p></section>

    <section id="burza"><h2>6. Studentská burza</h2><p>StudentHub ve Studentské burze poskytuje prostor pro zveřejnění inzerátu a umožňuje následnou soukromou domluvu mezi uživateli.</p><p>StudentHub:</p><List><li>není stranou kupní, směnné ani jiné smlouvy mezi uživateli,</li><li>nezpracovává platbu za předmět inzerátu,</li><li>nedrží peníze v úschově,</li><li>nerezervuje platbu,</li><li>nepočítá provizi z obchodu mezi uživateli,</li><li>nezajišťuje dopravu ani předání,</li><li>negarantuje pravost, vlastnictví, kvalitu, stav, bezpečnost, doručení ani předání nabízené věci.</li></List><p>Uživatelé si cenu, způsob platby, kontrolu věci, dopravu a předání domlouvají sami.</p><p>Tím nejsou dotčeny případné zákonné povinnosti StudentHubu, které nelze smluvně vyloučit.</p>
      <h3>6.1 Zveřejnění a platnost inzerátu</h3><p>Inzerát může zveřejnit účet s ověřenou e-mailovou adresou a dokončeným profilem. Pokud u konkrétního inzerátu není uvedeno jinak, standardně expiruje po 30 dnech.</p><p>Autor může podle dostupných funkcí inzerát:</p><List><li>upravit,</li><li>označit jako rezervovaný,</li><li>označit jako prodaný,</li><li>prodloužit,</li><li>odstranit.</li></List><p>Vlastnictví inzerátu je vázáno na přihlášený profil. Uživatel nesmí měnit autora ani spravovat cizí obsah.</p>
      <h3>6.2 Bezpečnost při obchodování</h3><p>StudentHub doporučuje:</p><List><li>před nákupem ověřit stav a původ věci,</li><li>u dražších předmětů preferovat bezpečné osobní předání,</li><li>neposílat citlivé platební údaje přes chat,</li><li>neposílat zálohy neznámým osobám bez dostatečného ověření,</li><li>nereagovat na podezřelé odkazy nebo žádosti o přihlášení mimo StudentHub,</li><li>podezřelé nabídky nahlásit.</li></List><p>StudentHub nemůže zaručit identitu ani poctivost každého uživatele.</p>
      <h3>6.3 Zakázané nabídky</h3><p>Ve Studentské burze je zakázáno nabízet zejména:</p><List><li>kradené věci,</li><li>padělky,</li><li>zboží nebo služby, jejichž nabídka je protiprávní,</li><li>nelegální drogy a jiné zakázané látky,</li><li>zbraně, střelivo, výbušniny nebo jiné regulované předměty, pokud jejich nabídka není výslovně právně dovolená a StudentHub ji nepovolil,</li><li>osobní údaje, účty, přihlašovací údaje nebo přístupová oprávnění,</li><li>nelegální kopie knih, skript nebo jiných děl,</li><li>neoprávněně šířené PDF, e-knihy nebo jiné digitální kopie,</li><li>cizí poznámky vydávané za vlastní,</li><li>neveřejné materiály vyučujících bez svolení,</li><li>nahrávky přednášek nebo výuky pořízené nebo šířené bez potřebného oprávnění,</li><li>zadání, odpovědi nebo jiné neveřejné materiály ke zkouškám,</li><li>řešení právě hodnocených úkolů způsobem podporujícím podvod,</li><li>plagiáty nebo služby založené na akademickém podvodu.</li></List><p>Digitální soubor určený k prodeji nebo předání se přes StudentHub nenahrává, pokud StudentHub u konkrétní funkce výslovně nestanoví jinak.</p><p>K inzerátu lze nahrát pouze vlastní fotografii nebo jiný obrazový materiál, k jehož použití má uživatel oprávnění.</p>
    </section>

    <section id="komunita"><h2>7. Studentská komunita</h2><p>Komunitní část je určena k věcné a férové komunikaci.</p><p>Zakázáno je zejména:</p><List><li>spamování,</li><li>opakované nevyžádané oslovování,</li><li>obtěžování,</li><li>vyhrožování,</li><li>podvody,</li><li>vydávání se za jinou osobu,</li><li>neoprávněné zveřejňování soukromých informací jiné osoby,</li><li>porušování autorských práv,</li><li>zveřejňování protiprávního nebo nebezpečného obsahu,</li><li>obcházení blokace nebo moderátorského opatření.</li></List><p>Nesouhlas s jiným uživatelem sám o sobě není porušením pravidel. Moderace se zaměřuje na konkrétní jednání a obsah, nikoli na legitimní odlišný názor.</p></section>

    <section id="chat"><h2>8. Soukromý chat</h2><p>Soukromý chat není veřejný, ale není určen pro sdílení hesel, platebních údajů nebo jiných vysoce citlivých informací.</p><p>Uživatel nesmí prostřednictvím chatu:</p><List><li>obtěžovat jiné osoby,</li><li>obcházet jejich blokaci,</li><li>rozesílat spam,</li><li>provozovat phishing,</li><li>šířit škodlivý obsah,</li><li>vyhrožovat,</li><li>používat chat k podvodu nebo jiné protiprávní činnosti.</li></List><p>Soukromé zprávy nejsou end-to-end šifrované.</p><p>Pokud je zpráva nahlášena, může ji v nezbytném rozsahu zobrazit oprávněný moderátor společně s omezeným kontextem potřebným k posouzení hlášení.</p></section>

    <section id="autorska-prava"><h2>9. Autorská práva a licence k uživatelskému obsahu</h2><p>Uživatel si ponechává práva ke svému vlastnímu obsahu.</p><p>Vložením obsahu do StudentHubu uživatel potvrzuje, že:</p><List><li>je jeho autorem, nebo</li><li>má potřebné oprávnění obsah použít a zveřejnit.</li></List><p>V rozsahu nezbytném pro provoz StudentHubu poskytuje uživatel provozovateli nevýhradní a bezúplatné oprávnění obsah technicky ukládat, zobrazovat, přenášet, dočasně kopírovat, přizpůsobit technickému formátu a zpřístupnit ostatním uživatelům podle zvolené funkce služby.</p><p>Toto oprávnění není určeno k samostatnému prodeji uživatelského obsahu StudentHubem.</p><p>Po odstranění obsahu oprávnění zaniká v rozsahu, v jakém již není jeho další zpracování nezbytné například kvůli technickým zálohám, řešení hlášení, právní povinnosti nebo ochraně právních nároků.</p></section>

    <section id="hlaseni"><h2>10. Hlášení závadného nebo protiprávního obsahu</h2><p>Obsah lze nahlásit prostřednictvím funkce „Nahlásit“ nebo e-mailem na <a href={`mailto:${operator.email}`}>{operator.email}</a>.</p><p>Oznámení by mělo podle povahy případu obsahovat zejména:</p><List><li>označení konkrétního obsahu,</li><li>odkaz nebo jiný údaj umožňující obsah přesně najít,</li><li>stručné vysvětlení, proč je obsah považován za protiprávní nebo porušující pravidla,</li><li>kontaktní údaj oznamovatele, pokud je potřebný,</li><li>pravdivé informace umožňující oznámení posoudit.</li></List><p>StudentHub posoudí hlášení v přiměřené době podle jeho povahy a závažnosti.</p><p>Pokud se na StudentHub vztahují konkrétní povinnosti podle nařízení EU o digitálních službách (DSA), bude mechanismus hlášení a vyřizování oznámení provozován v odpovídajícím rozsahu podle těchto pravidel.</p></section>

    <section id="moderace"><h2>11. Moderace a zásahy do obsahu</h2><p>Provozovatel může zejména:</p><List><li>skrýt nebo odstranit závadný obsah,</li><li>omezit jeho viditelnost,</li><li>odstranit inzerát,</li><li>omezit některé funkce účtu,</li><li>dočasně účet pozastavit,</li><li>účet v závažných nebo opakovaných případech zablokovat,</li><li>přijmout přiměřená technická opatření proti spamu, podvodům a zneužití.</li></List><p>Při rozhodování zohledňujeme zejména:</p><List><li>závažnost porušení,</li><li>jeho dopad na ostatní,</li><li>opakování jednání,</li><li>úmyslnost,</li><li>možnost nápravy,</li><li>bezpečnostní riziko.</li></List><p>Automatické nástroje mohou sloužit jako pomoc při odhalování spamu nebo závadného obsahu, ale automatická kontrola sama o sobě nenahrazuje právní posouzení tam, kde je potřebné.</p><p>V případech, kde to vyžaduje DSA nebo jiný právní předpis, StudentHub poskytne dotčenému uživateli srozumitelné odůvodnění omezení nebo odstranění obsahu a informaci o dostupných možnostech nápravy.</p></section>

    <section id="namitka"><h2>12. Námitka proti moderátorskému zásahu</h2><p>Pokud uživatel nesouhlasí s moderátorským rozhodnutím, může požádat o jeho přezkoumání na <a href={`mailto:${operator.email}`}>{operator.email}</a>.</p><p>Do žádosti je vhodné uvést:</p><List><li>identifikaci účtu,</li><li>označení dotčeného obsahu nebo rozhodnutí,</li><li>důvod, proč uživatel považuje rozhodnutí za nesprávné.</li></List><p>StudentHub může přezkum odmítnout u opakovaných, zjevně zneužívajících nebo totožných žádostí, pokud tím nejsou dotčena práva, která uživateli přímo přiznává zákon nebo DSA.</p><p>Pokud uživateli vzniká podle DSA právo na jiný interní nebo mimosoudní mechanismus nápravy, tímto ustanovením není omezeno.</p></section>

    <section id="poruseni"><h2>13. Opakované a závažné porušování pravidel</h2><p>Při opakovaném nebo závažném porušování může StudentHub účet dočasně omezit nebo ukončit.</p><p>Za závažné porušení lze považovat zejména:</p><List><li>podvod,</li><li>phishing,</li><li>cílené obtěžování,</li><li>závažné vyhrožování,</li><li>zneužití osobních údajů,</li><li>nabízení protiprávního obsahu nebo zboží,</li><li>systematické porušování autorských práv,</li><li>obcházení dříve uložené blokace,</li><li>útok na bezpečnost nebo dostupnost služby.</li></List><p>Zásah má být přiměřený povaze a závažnosti porušení.</p></section>

    <section id="placene"><h2>14. Placené zvýraznění a reklama</h2><p>Tato část se použije pouze v případě, že StudentHub takovou službu skutečně aktivuje. Placené zvýraznění, reklamní pozice a jejich online objednávka nejsou v současné produkční verzi aktivní.</p><p>Partner nebo jiný oprávněný objednatel může podle budoucí aktuální nabídky StudentHubu objednat časově omezené:</p><List><li>zvýraznění nabídky,</li><li>zvýraznění brigády,</li><li>reklamní pozici,</li><li>jinou výslovně popsanou propagační službu.</li></List><p>Placený nebo sponzorovaný obsah musí být zřetelně označen tak, aby nebyl zaměnitelný s běžným neplaceným obsahem.</p><p>Objednatel odpovídá za:</p><List><li>pravdivost dodaných údajů,</li><li>oprávnění použít dodaný text, logo, fotografie a jiné podklady,</li><li>soulad reklamy a nabídky s právními předpisy,</li><li>správnost fakturačních údajů.</li></List><p>StudentHub může odmítnout reklamu nebo zvýraznění, které je protiprávní, klamavé, v rozporu s těmito pravidly nebo nepřiměřeně rizikové pro uživatele.</p>
      <h3>14.1 Cena a objednávka</h3><p>Před závazným objednáním musí být objednateli sděleny alespoň:</p><List><li>přesný předmět služby,</li><li>cena a případná daň,</li><li>doba zvýraznění nebo reklamního prostoru,</li><li>datum nebo způsob zahájení služby,</li><li>způsob platby,</li><li>fakturační podmínky,</li><li>storno podmínky,</li><li>způsob uplatnění reklamace,</li><li>další podstatné podmínky konkrétní objednávky.</li></List><p>Konkrétní objednávka má v případě rozporu přednost před obecnou částí těchto podmínek, pokud tím nejsou omezena práva, která nelze podle zákona vyloučit.</p>
    </section>

    <section id="spotrebitele"><h2>15. Placené služby pro spotřebitele</h2><p>Tato část se použije pouze tehdy, pokud StudentHub v budoucnu aktivuje placenou službu a objednává ji fyzická osoba jako spotřebitel, nikoli v rámci své podnikatelské činnosti.</p><p>U smlouvy uzavřené na dálku může spotřebiteli vzniknout právo odstoupit od smlouvy ve lhůtě 14 dnů od uzavření smlouvy, pokud zákon nestanoví výjimku.</p><p>Má-li placená služba začít před uplynutím této lhůty, StudentHub si v případech vyžadovaných zákonem vyžádá výslovnou žádost nebo souhlas se zahájením plnění a poskytne příslušné poučení.</p><p>Pokud spotřebitel odstoupí poté, co na jeho výslovnou žádost již začalo poskytování služby, může být v zákonem stanovených případech povinen uhradit poměrnou část ceny za již poskytnuté plnění.</p><p>Pokud byla služba v plném rozsahu poskytnuta před uplynutím lhůty pro odstoupení za podmínek stanovených zákonem, může právo na odstoupení zaniknout.</p><p>Před zavedením automatické online objednávky placeného zvýraznění musí být uživatelské rozhraní doplněno o všechna zákonná předsmluvní poučení a případně vzorový formulář pro odstoupení.</p></section>

    <section id="reklamace"><h2>16. Reklamace placené služby</h2><p>Pokud StudentHub v budoucnu poskytne placenou službu vadně, může objednatel uplatnit reklamaci na <a href={`mailto:${operator.email}`}>{operator.email}</a>.</p><p>Reklamace by měla obsahovat zejména:</p><List><li>identifikaci objednávky,</li><li>popis vady,</li><li>datum, kdy se problém projevil,</li><li>požadovaný způsob řešení, je-li relevantní.</li></List><p>Práva spotřebitele z vadného plnění ani jiná zákonná práva nelze těmito podmínkami omezit.</p></section>

    <section id="odpovednost"><h2>17. Odpovědnost za obsah a dostupnost služby</h2><p>StudentHub neodpovídá za pravdivost každého tvrzení, nabídky nebo příspěvku vloženého uživatelem a před zveřejněním automaticky právně nekontroluje každý jednotlivý obsah.</p><p>Tím nejsou dotčeny povinnosti, které provozovateli vzniknou poté, co se věrohodně dozví o konkrétním protiprávním obsahu, ani jiné povinnosti podle platných právních předpisů.</p><p>StudentHub se snaží službu udržovat bezpečnou a dostupnou, ale nemůže zaručit nepřetržitý provoz bez výpadků.</p><p>Služba může být dočasně omezena zejména kvůli:</p><List><li>údržbě,</li><li>bezpečnostnímu incidentu,</li><li>technické poruše,</li><li>výpadku externí infrastruktury,</li><li>nutné změně služby,</li><li>zásahu orgánu veřejné moci.</li></List><p>Žádné ustanovení těchto podmínek nevylučuje nebo neomezuje odpovědnost provozovatele v rozsahu, v jakém ji podle platného práva vyloučit nebo omezit nelze.</p></section>

    <section id="zmeny"><h2>18. Změny a ukončení služby</h2><p>StudentHub může funkce služby měnit, doplňovat nebo ukončit.</p><p>Podstatné změny těchto podmínek budou zveřejněny s novým datem účinnosti. Pokud to vyžaduje povaha změny nebo zákon, budou registrovaní uživatelé vhodně upozorněni.</p><p>Uživatel může přestat StudentHub používat a podle dostupných funkcí odstranit svůj účet.</p><p>Podrobnosti o nakládání s osobními údaji a obsahem po odstranění účtu jsou uvedeny v <Link href="/soukromi">Zásadách ochrany osobních údajů</Link>.</p></section>

    <section id="pravo"><h2>19. Rozhodné právo</h2><p>Pokud není právními předpisy stanoveno jinak, řídí se právní vztahy mezi provozovatelem a uživatelem právem České republiky.</p><p>Tím nejsou spotřebiteli odňata kogentní práva, která mu poskytují právní předpisy země jeho obvyklého bydliště, pokud se podle příslušných pravidel použijí.</p></section>

    <section id="adr"><h2>20. Mimosoudní řešení spotřebitelských sporů</h2><p>Tato část se vztahuje pouze na případné budoucí spory mezi StudentHubem jako podnikatelem a spotřebitelem ze smlouvy o placené službě nebo jiné spotřebitelské smlouvy. Provozovatel nyní vystupuje jako fyzická osoba nepodnikající a placené služby nejsou aktivní.</p><p>Tato část se nevztahuje na běžný spor mezi dvěma uživateli Studentské burzy, pokud StudentHub není stranou jejich smlouvy.</p><p>Pokud budou placené spotřebitelské služby aktivovány a spor se nepodaří vyřešit přímo s provozovatelem, může se spotřebitel za podmínek zákona obrátit na subjekt mimosoudního řešení spotřebitelských sporů:</p><address><strong>Česká obchodní inspekce</strong><br />Ústřední inspektorát – oddělení ADR<br />Gorazdova 1969/24<br />120 00 Praha 2<br />E-mail: <a href="mailto:adr@coi.gov.cz">adr@coi.gov.cz</a><br />Web: <a href="https://coi.gov.cz/informace-o-adr/" rel="external">coi.gov.cz/informace-o-adr/</a></address></section>

    <section id="kontakt"><h2>21. Kontakt</h2><dl className="legal-definition"><div><dt>Dotazy k provozu StudentHubu</dt><dd><a href={`mailto:${operator.email}`}>{operator.email}</a></dd></div><div><dt>Hlášení závadného nebo protiprávního obsahu</dt><dd><a href={`mailto:${operator.email}`}>{operator.email}</a></dd></div><div><dt>Námitky proti moderaci</dt><dd><a href={`mailto:${operator.email}`}>{operator.email}</a></dd></div><div><dt>Reklamace případných placených služeb</dt><dd><a href={`mailto:${operator.email}`}>{operator.email}</a></dd></div></dl></section>

    <section id="zaver"><h2>22. Závěrečná ustanovení</h2><p>Pokud je některé ustanovení těchto podmínek neplatné nebo nepoužitelné, nemá to samo o sobě vliv na platnost ostatních ustanovení.</p><p>Nadpisy slouží pouze pro přehlednost.</p></section>
  </LegalPage>;
}
