import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";
import { legalDocuments, minimumUserAge, operator } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Zásady ochrany osobních údajů",
  description: "Jak StudentHub zpracovává osobní údaje, k jakým účelům, po jakou dobu a jaká práva mají uživatelé.",
  alternates: { canonical: "https://studenthubapp.cz/soukromi" },
  openGraph: { title: "Zásady ochrany osobních údajů | StudentHub", description: "Informace o zpracování osobních údajů ve StudentHubu.", url: "https://studenthubapp.cz/soukromi", locale: "cs_CZ", type: "article" },
};

const sections = [
  ["spravce", "Kdo osobní údaje zpracovává"], ["pusobnost", "Pro koho jsou zásady určeny"], ["udaje", "Jaké údaje zpracováváme"],
  ["ucely", "Účely a právní základy"], ["povinne", "Povinné a dobrovolné údaje"], ["prijemci", "Příjemci údajů"],
  ["predavani", "Předávání mimo EHP"], ["uchovani", "Doba uchování"], ["odstraneni", "Veřejný obsah a odstranění účtu"],
  ["prava", "Vaše práva"], ["technologie", "Cookies a lokální úložiště"], ["bezpecnost", "Bezpečnost údajů"],
  ["incidenty", "Bezpečnostní incidenty"], ["automatizace", "Automatizované rozhodování"], ["externi", "Externí odkazy"],
  ["zmeny", "Změny zásad"], ["stiznost", "Stížnost u dozorového úřadu"],
].map(([id, label]) => ({ id, label }));

const List = ({ children }: { children: React.ReactNode }) => <ul>{children}</ul>;

export default function PrivacyPage() {
  const document = legalDocuments.privacy;
  return <LegalPage title="Zásady ochrany osobních údajů StudentHub" description="Jaké údaje potřebujeme, proč je zpracováváme a jak nad nimi můžete uplatnit svá práva." version={document.version} effectiveDate={document.effectiveDate} updatedDate={document.updatedDate} sections={sections}>
    <section id="spravce"><h2>1. Kdo osobní údaje zpracovává</h2><p>Správcem osobních údajů a provozovatelem platformy je <strong>{operator.name}, {operator.status}</strong>.</p><dl className="legal-definition"><div><dt>E-mail pro otázky k ochraně osobních údajů</dt><dd><a href={`mailto:${operator.email}`}>{operator.email}</a></dd></div><div><dt>Služba</dt><dd>StudentHub, dostupný zejména na adrese <a href="https://studenthubapp.cz">studenthubapp.cz</a></dd></div></dl><p>StudentHub není oficiálně spojený s žádnou univerzitou, pokud není u konkrétní spolupráce výslovně uvedeno jinak. Uživatelé by do služby neměli zadávat školní hesla ani jiné přihlašovací údaje ke školním systémům.</p></section>

    <section id="pusobnost"><h2>2. Pro koho jsou tyto zásady určeny</h2><p>Tyto zásady vysvětlují, jak StudentHub zpracovává osobní údaje:</p><List><li>návštěvníků webu,</li><li>registrovaných uživatelů,</li><li>osob, které zveřejní obsah,</li><li>osob používajících chat a další komunitní funkce,</li><li>osob kontaktujících provozovatele,</li><li>osob, jejichž údaje se objeví v hlášení, moderátorském podnětu nebo bezpečnostním incidentu,</li><li>případně osob, jejichž údaje byly získány z externího zdroje.</li></List><p>StudentHub je určen především studentům. Minimální věk pro registraci a používání uživatelských funkcí je <strong>{minimumUserAge} let</strong>.</p><p>Pokud je zpracování osobních údajů dítěte založeno na souhlasu a jde o nabídku služby informační společnosti přímo dítěti, český zákon č. 110/2019 Sb. stanoví způsobilost dítěte k udělení takového souhlasu od 15 let. Tato hranice sama o sobě neurčuje způsobilost ke každému právnímu jednání; ta se posuzuje podle povahy jednání, věku a platných právních předpisů.</p></section>

    <section id="udaje"><h2>3. Jaké osobní údaje zpracováváme</h2><p>Rozsah údajů závisí na tom, jakou funkci uživatel používá.</p>
      <h3>3.1 Účet a přihlášení</h3><p>Při registraci a používání účtu můžeme zpracovávat zejména:</p><List><li>e-mailovou adresu,</li><li>technický identifikátor účtu,</li><li>údaje potřebné pro ověření a správu přihlášení,</li><li>údaje o potvrzení účtu,</li><li>údaje potřebné k obnově účtu,</li><li>bezpečnostní údaje související s přihlášením a relací.</li></List><p>Jedinou aktivní metodou přihlášení je e-mail a heslo. Autentizaci zajišťuje Supabase Auth. StudentHub neukládá hesla v čitelné podobě; hesla zpracovává autentizační služba. Přístupový token má v současné konfiguraci platnost 3 600 sekund a relace se obnovuje pomocí rotovaného refresh tokenu.</p>
      <h3>3.2 Profil</h3><p>Uživatel může podle dostupných funkcí dobrovolně zadat zejména:</p><List><li>přezdívku,</li><li>uživatelské jméno,</li><li>popis profilu,</li><li>zájmy,</li><li>profilovou fotografii,</li><li>školu,</li><li>fakultu,</li><li>studijní program nebo ročník,</li><li>další údaje výslovně označené jako dobrovolné.</li></List><p>Veřejný profil zobrazuje pouze údaje určené ke zveřejnění. E-mailová adresa, telefonní číslo, přesná poloha, neveřejné kontaktní údaje, interní moderátorské údaje a bezpečnostní záznamy nejsou veřejně dostupné. Uživatel může celý profil nastavit jako soukromý a samostatně vypnout zobrazení fakulty, studijního programu nebo ročníku.</p><p>Profilová fotografie se na serveru dekóduje, zmenší a převede do formátu WebP bez původních EXIF metadat. Ukládá se do neveřejného úložiště Supabase Storage a aplikace ji zpřístupňuje časově omezeným podepsaným odkazem.</p>
      <h3>3.3 Komunita, Burza, Bydlení, Hledám parťáka a akce</h3><p>Podle použité funkce můžeme zpracovávat zejména:</p><List><li>příspěvky, komentáře a reakce,</li><li>nabídky a poptávky ve Studentské burze,</li><li>údaje uvedené v nabídce bydlení,</li><li>údaje uvedené při hledání parťáka,</li><li>údaje o vytvoření nebo zájmu o komunitní akci,</li><li>fotografie vložené uživatelem,</li><li>údaje o autorovi obsahu,</li><li>čas vytvoření, úpravy, skrytí nebo odstranění obsahu,</li><li>hlášení obsahu a související moderátorské údaje.</li></List><p>Uživatel by neměl veřejně zveřejňovat více osobních údajů, než je pro daný účel nezbytné.</p>
      <h3>3.4 Soukromé zprávy a chat</h3><p>Při používání soukromých zpráv můžeme zpracovávat zejména:</p><List><li>identifikátory účastníků konverzace,</li><li>text zpráv,</li><li>čas odeslání a stav moderace zprávy,</li><li>stav přečtení,</li><li>ztlumení, archivaci, blokace a další uživatelská nastavení,</li><li>nahlášení zprávy,</li><li>nezbytný kontext potřebný k posouzení nahlášení.</li></List><p>Soukromé zprávy nejsou veřejné a nejde o end-to-end šifrovanou komunikaci. Po nahlášení může oprávněný moderátor zobrazit nahlášenou zprávu a nejvýše omezený okolní kontext, který je nezbytný k posouzení hlášení. Moderátorský zásah se zapisuje do auditní historie. Push upozornění ve výchozím nastavení neobsahuje text soukromé zprávy.</p>
      <h3>3.5 Kontaktní formulář a komunikace s podporou</h3><p>Pokud nás uživatel kontaktuje, můžeme zpracovávat:</p><List><li>jméno nebo přezdívku,</li><li>e-mailovou adresu,</li><li>předmět zprávy,</li><li>obsah zprávy,</li><li>technické údaje nezbytné k doručení a zabezpečení komunikace.</li></List><p>Současný kontaktní formulář nepřijímá přílohy. Tyto údaje používáme k vyřízení dotazu, zpětné vazby, žádosti o opravu, žádosti týkající se osobních údajů nebo partnerské nabídky.</p>
      <h3>3.6 Technické a bezpečnostní údaje</h3><p>Při používání služby mohou vznikat například:</p><List><li>datum a čas požadavku,</li><li>navštívená část služby,</li><li>technický identifikátor relace nebo instalace,</li><li>údaje o zařízení nebo prohlížeči v rozsahu, který vytváří používaná infrastruktura,</li><li>IP adresa zpracovaná hostingem, databázovou, bezpečnostní, mapovou nebo push infrastrukturou,</li><li>záznamy o chybách a výpadcích,</li><li>záznamy potřebné k odhalování zneužití, spamu, automatizovaných útoků nebo neoprávněného přístupu,</li><li>auditní a bezpečnostní logy.</li></List><p>Vlastní analytická tabulka StudentHubu neukládá původní IP adresu ani celý user-agent. Infrastrukturní poskytovatelé však mohou IP adresu a další technické údaje zpracovávat ve svých provozních a bezpečnostních logách.</p>
      <h3>3.7 Cookies, lokální úložiště a analytika</h3><p>Informace o cookies a podobných technologiích jsou podrobněji uvedeny v <Link href="/cookies">Zásadách používání cookies a lokálního úložiště</Link>. Technické technologie používáme v rozsahu nezbytném pro fungování služby, zabezpečení, přihlášení nebo uložení uživatelské volby. Vlastní privacy-first analytika se aktivuje až po souhlasu; externí analytický ani reklamní skript se nepoužívá.</p>
      <h3>3.8 Zvláštní kategorie osobních údajů</h3><p>StudentHub standardně nevyžaduje, aby uživatelé zadávali zvláštní kategorie osobních údajů podle čl. 9 GDPR, například údaje o zdravotním stavu, náboženském vyznání, politických názorech, sexuálním životě nebo sexuální orientaci.</p><p>Uživatelé by takové údaje neměli zveřejňovat, pokud to není skutečně nutné. Pokud je uživatel přesto vloží do veřejného příspěvku, profilu, soukromé zprávy nebo hlášení, může dojít k jejich technickému zpracování v rozsahu potřebném k provozu, zabezpečení nebo moderaci služby.</p>
      <h3>3.9 Údaje z externích zdrojů</h3><p>StudentHub zobrazuje pracovní nabídky ze smluvně povoleného XML feedu Fajn-brigády.cz a obsah z dalších schválených veřejných zdrojů. Z pracovního feedu přebírá identifikátor nabídky, název, zaměstnavatele, popis, lokalitu, odměnu, časové a klasifikační údaje a odkaz na původní nabídku. Zdrojové XML se do databáze neukládá; ukládá se pouze normalizovaná veřejná podoba. Synchronizace probíhá nejvýše v desetihodinovém intervalu a nabídka chybějící ve třech po sobě jdoucích úplných a důvěryhodných aktualizacích se archivuje.</p><p>Po kliknutí na nabídku se uživatel přesune na web třetí strany. StudentHub před přechodem uloží vlastní záznam prokliku bez přímého identifikátoru osoby; cílový web následně zpracovává požadavek podle vlastních pravidel. Pokud StudentHub získává osobní údaje jinak než přímo od dotčené osoby, může vzniknout informační povinnost podle čl. 14 GDPR.</p>
    </section>

    <section id="ucely"><h2>4. Proč údaje používáme a na jakém právním základě</h2><div className="legal-table-scroll"><table><thead><tr><th>Účel</th><th>Příklady údajů</th><th>Právní základ</th></tr></thead><tbody>
      <tr><td>Registrace a provoz účtu</td><td>e-mail, identifikátor účtu, profil, údaje o přihlášení</td><td>plnění smlouvy nebo kroky před jejím uzavřením podle čl. 6 odst. 1 písm. b) GDPR</td></tr>
      <tr><td>Profil a uživatelský obsah</td><td>profil, příspěvky, nabídky, účast na akcích</td><td>zpravidla plnění smlouvy podle čl. 6 odst. 1 písm. b) GDPR</td></tr>
      <tr><td>Soukromé zprávy</td><td>účastníci, text zpráv, stav přečtení</td><td>zpravidla plnění smlouvy podle čl. 6 odst. 1 písm. b) GDPR</td></tr>
      <tr><td>Moderace a ochrana uživatelů</td><td>hlášení, blokace, omezení účtu, auditní záznamy</td><td>oprávněný zájem podle čl. 6 odst. 1 písm. f) GDPR</td></tr>
      <tr><td>Zabezpečení služby</td><td>technické identifikátory, bezpečnostní logy, IP adresa v nezbytném rozsahu</td><td>oprávněný zájem podle čl. 6 odst. 1 písm. f) GDPR; případně právní povinnost</td></tr>
      <tr><td>Vyřízení dotazu</td><td>jméno, e-mail, obsah zprávy</td><td>čl. 6 odst. 1 písm. b) GDPR, pokud jde o službu nebo smlouvu; jinak zpravidla oprávněný zájem podle písm. f)</td></tr>
      <tr><td>Žádost podle GDPR</td><td>identifikační a kontaktní údaje, obsah žádosti</td><td>právní povinnost podle čl. 6 odst. 1 písm. c) GDPR</td></tr>
      <tr><td>Další zákonné povinnosti</td><td>údaje vyžádané oprávněným orgánem</td><td>právní povinnost podle čl. 6 odst. 1 písm. c) GDPR</td></tr>
      <tr><td>Obhajoba právních nároků</td><td>nezbytné údaje z účtu, komunikace, hlášení a logů</td><td>oprávněný zájem podle čl. 6 odst. 1 písm. f) GDPR</td></tr>
      <tr><td>Volitelná analytika</td><td>údaje o návštěvě a používání služby</td><td>souhlas podle čl. 6 odst. 1 písm. a) GDPR</td></tr>
      <tr><td>Marketing nebo personalizovaná reklama</td><td>cookies, identifikátory a marketingové údaje</td><td>pouze pokud bude funkce zavedena a bude existovat odpovídající právní základ; kde je vyžadován souhlas, až po jeho udělení</td></tr>
    </tbody></table></div><h3>Oprávněné zájmy</h3><p>Pokud zpracování zakládáme na oprávněném zájmu, jde zejména o:</p><List><li>ochranu StudentHubu a jeho uživatelů před zneužitím,</li><li>prevenci podvodů, spamu a neoprávněných přístupů,</li><li>vymáhání komunitních pravidel,</li><li>vyšetřování hlášení a bezpečnostních incidentů,</li><li>zachování spolehlivosti a stability služby,</li><li>ochranu a obhajobu právních nároků.</li></List><p>U každého takového zpracování posuzujeme, zda nad těmito zájmy nepřevažují práva a svobody uživatelů.</p></section>

    <section id="povinne"><h2>5. Které údaje jsou povinné a které dobrovolné</h2><p>Údaje označené v registračním nebo jiném formuláři jako povinné jsou potřebné k vytvoření účtu nebo poskytnutí konkrétní funkce. Pokud je uživatel neposkytne, nemusí být možné účet vytvořit nebo danou funkci použít.</p><p>Údaje označené jako dobrovolné uživatel poskytovat nemusí. Neposkytnutí dobrovolného údaje samo o sobě nebrání používání funkcí, které tento údaj objektivně nepotřebují.</p></section>

    <section id="prijemci"><h2>6. Kdo může osobní údaje přijímat</h2><p>Osobní údaje mohou být zpřístupněny pouze v nezbytném rozsahu zejména:</p><List><li><strong>Supabase, Inc.</strong> – Postgres databáze, Supabase Auth, neveřejné Storage, Realtime a provozní logy; primární databáze je v regionu Central EU (Frankfurt), <code>eu-central-1</code>,</li><li><strong>Vercel Inc.</strong> – hosting, CDN, serverové funkce, cron úlohy a technické logy; serverové funkce projektu jsou konfigurované pro Frankfurt (<code>fra1</code>), zatímco síť CDN a podpůrné zpracování mohou být globální,</li><li><strong>Supabase Auth</strong> – doručení potvrzení registrace a obnovy hesla přes výchozí e-mailovou službu Supabase; vlastní SMTP není aktivní,</li><li><strong>OpenStreetMap Foundation a její veřejné služby</strong> – mapové dlaždice a serverové geokódování Nominatim při použití mapy nebo ručním vyhledání adresy,</li><li><strong>provozovatel push služby zvolený prohlížečem nebo operačním systémem</strong> – například služba výrobce prohlížeče; StudentHub odesílá Web Push přímo na uložený endpoint,</li><li>oprávnění moderátoři a administrátoři StudentHubu,</li><li>právní, bezpečnostní nebo technický poradce, pokud je zapojení nezbytné a je vázán odpovídajícími povinnostmi,</li><li>orgán veřejné moci, pokud zpřístupnění vyžaduje právní předpis nebo vykonatelné rozhodnutí.</li></List><p>StudentHub nepoužívá Google Analytics, Vercel Analytics, Sentry, externí fonty ani externí reklamní skripty. Kontaktní zpráva se ukládá v Supabase; samostatný e-mailový relay pro kontaktní formulář není aktivní. Veřejné příspěvky, nabídky a veřejná část profilu mohou být dostupné ostatním uživatelům nebo návštěvníkům internetu podle nastavení služby a uživatele.</p><p>Aktuální seznamy subdodavatelů a podmínky zpracování zveřejňují poskytovatelé na svých stránkách: <a href="https://supabase.com/legal/dpa" rel="external">Supabase DPA</a> a <a href="https://security.vercel.com" rel="external">Vercel Trust Center</a>.</p></section>

    <section id="predavani"><h2>7. Předávání osobních údajů mimo Evropský hospodářský prostor</h2><p>Primární databáze Supabase je umístěna v Německu. Supabase, Vercel a jejich subdodavatelé však mohou při poskytování podpůrných, bezpečnostních nebo infrastrukturních služeb zpracovávat údaje také mimo Evropský hospodářský prostor, zejména ve Spojených státech nebo dalších zemích, kde působí jejich subdodavatelé.</p><p>Pro takové předávání poskytovatelé ve svých smluvních dokumentech uvádějí mechanismy podle kapitoly V GDPR, zejména rozhodnutí o odpovídající ochraně nebo standardní smluvní doložky. Přesný seznam subdodavatelů a míst zpracování se může měnit a je dostupný v aktuální dokumentaci Supabase a Vercelu.</p></section>

    <section id="uchovani"><h2>8. Jak dlouho údaje uchováváme</h2><p>Osobní údaje uchováváme pouze po dobu nezbytnou pro daný účel. Níže je popsáno skutečné současné chování aktivního systému. U kategorií bez schválené maximální lhůty neuvádíme odhad; záznam zůstává do odstranění účtu, obsahu nebo oprávněného administrativního zásahu.</p><div className="legal-table-scroll"><table><thead><tr><th>Kategorie</th><th>Aktivní systém a automatický úklid</th><th>Po odstranění účtu nebo obsahu</th></tr></thead><tbody>
      <tr><td>Účet a profil</td><td>po dobu existence účtu; automatický časový výmaz není nastaven</td><td>profil a autentizační účet se odstraní po opětovném ověření hesla</td></tr>
      <tr><td>Profilová fotografie</td><td>po dobu, kdy ji má profil nastavenou</td><td>odstraní se při odebrání fotografie nebo účtu</td></tr>
      <tr><td>Veřejné příspěvky a komentáře</td><td>do odstranění nebo moderátorského zásahu; bez obecné automatické lhůty</td><td>mohou zůstat bez vazby na profil; autor může požádat i o odstranění rozpoznatelného textu nebo fotografie</td></tr>
      <tr><td>Reakce, oblíbené a sledování</td><td>do odebrání uživatelem nebo odstranění účtu; lokální oblíbené do smazání úložiště zařízení</td><td>profilové vazby se odstraní; lokální kopii maže uživatel ve svém prohlížeči</td></tr>
      <tr><td>Studentská burza</td><td>aktivní inzerát standardně 30 dnů; poté se automaticky označí jako expirovaný</td><td>inzerát se skryje jako odstraněný a oddělí od profilu; fotografie se odstraňují při odstranění inzerátu</td></tr>
      <tr><td>Bydlení</td><td>aktivní inzerát 30 dnů; poté se automaticky označí jako expirovaný</td><td>při odstranění účtu se inzerát a jeho fotografie odstraní z aktivního systému</td></tr>
      <tr><td>Hledám parťáka</td><td>do konce události a nejvýše do času expirace uloženého u příspěvku</td><td>příspěvek se uzavře a skryje; vazba na profil se odstraní</td></tr>
      <tr><td>Komunitní akce</td><td>po skončení se automaticky archivují; neověřené změny čekají na moderaci</td><td>vlastní akce se označí jako odstraněná a archivuje</td></tr>
      <tr><td>Návrhy míst a zkušenosti</td><td>do vyřízení, stažení nebo administrativního zásahu; bez obecné automatické lhůty</td><td>při odstranění účtu se neveřejné návrhy a vlastní zkušenosti odstraní včetně navázaných fotografií</td></tr>
      <tr><td>Soukromé zprávy a žádosti</td><td>do odstranění účtu některého účastníka; samostatná časová expirace historie není nastavena</td><td>konverzace, členství, zprávy a související profilové vazby se odstraní kaskádou</td></tr>
      <tr><td>Blokace</td><td>do odblokování nebo odstranění účtu</td><td>profilové vazby blokace se odstraní</td></tr>
      <tr><td>Hlášení, moderace a auditní historie</td><td>po dobu potřebnou k vyřízení, vymáhání pravidel a obraně právních nároků; maximální lhůta není nyní technicky nastavena</td><td>identifikátor zaniklého profilu se podle typu záznamu odstraní nebo nahradí prázdnou vazbou; samotný bezpečnostní záznam může zůstat</td></tr>
      <tr><td>Rate-limit záznamy</td><td>Burza a Bydlení mažou záznamy starší 8 dnů; část krátkodobých limitů existuje pouze v paměti běžící serverové instance</td><td>po uplynutí příslušného okna se nepoužívají; incidentní záznam může být odděleně uchován déle</td></tr>
      <tr><td>Kontaktní formulář</td><td>do vyřízení a ručního odstranění; maximální automatická lhůta není nastavena</td><td>na žádost lze záznam po posouzení právních důvodů odstranit</td></tr>
      <tr><td>Žádosti podle GDPR</td><td>po dobu nezbytnou k vyřízení a doložení splnění právní povinnosti; maximální lhůta není technicky nastavena</td><td>po odpadnutí právního důvodu budou odstraněny</td></tr>
      <tr><td>Vlastní analytická data</td><td>uložená zobrazení nemají automatickou časovou expiraci; nové záznamy vznikají pouze po souhlasu</td><td>odvolání zastaví další ukládání, nemá však zpětný účinek</td></tr>
      <tr><td>Technické logy</td><td>Supabase Free uchovává API a databázové logy přibližně 1 den; doby logů Vercelu se řídí jeho aktuálním plánem a konfigurací</td><td>řídí se retenčním režimem poskytovatele a nemusí být odstraněny současně s účtem</td></tr>
      <tr><td>Zálohy</td><td>projekt Supabase je na Free plánu bez garantovaných dostupných automatických záloh; StudentHub nemá vlastní off-site zálohu ani zapnuté PITR</td><td>nelze slíbit dodatečnou maximální dobu přepsání záloh, které mohou vznikat v infrastruktuře poskytovatele</td></tr>
    </tbody></table></div><p>Pokud jsou údaje anonymizovány tak, že již není možné osobu rozumně identifikovat, nemusí se na ně GDPR dále vztahovat. Pouhé odstranění jména nebo jeho nahrazení identifikátorem nemusí být skutečnou anonymizací.</p></section>

    <section id="odstraneni"><h2>9. Veřejný obsah a odstranění účtu</h2><p>Uživatel může podle dostupných funkcí upravit nebo odstranit svůj profil a vlastní obsah. Odstranění účtu vyžaduje nové ověření hesla.</p><p>Při odstranění účtu se odstraní profil a profilová fotografie, soukromé chaty a nepotřebné profilové vazby. Vlastní akce a příspěvky Hledám parťáka se skryjí, inzeráty Burzy se označí jako odstraněné a odpojí od profilu. Neveřejné návrhy míst, vlastní zkušenosti a nabídky Bydlení se odstraní. Veřejné příspěvky a komentáře mohou zůstat bez přímé profilové vazby kvůli návaznosti diskuse.</p><p>Text nebo fotografie mohou i po odstranění jména umožnit rozpoznání autora. Pokud chcete odstranit také konkrétní rozpoznatelný obsah, napište na <a href={`mailto:${operator.email}`}>{operator.email}</a>. Údaje ponecháme pouze tehdy, pokud pro to existuje samostatný právní důvod, například právní povinnost, bezpečnostní potřeba nebo ochrana právních nároků.</p></section>

    <section id="prava"><h2>10. Vaše práva</h2><p>Za podmínek stanovených GDPR máte právo:</p><List><li>požádat o přístup ke svým osobním údajům,</li><li>požádat o opravu nepřesných nebo neúplných údajů,</li><li>požádat o výmaz osobních údajů,</li><li>požádat o omezení zpracování,</li><li>vznést námitku proti zpracování založenému na oprávněném zájmu,</li><li>požádat o přenositelnost údajů, pokud jsou splněny zákonné podmínky,</li><li>kdykoli odvolat souhlas, pokud je konkrétní zpracování na souhlasu založeno,</li><li>podat stížnost u příslušného dozorového úřadu.</li></List><p>Žádost můžete poslat na <a href={`mailto:${operator.email}`}>{operator.email}</a>. Před vyřízením žádosti můžeme v přiměřeném rozsahu ověřit totožnost žadatele, pokud máme důvodné pochybnosti o jeho totožnosti.</p><p>Na žádost odpovíme bez zbytečného odkladu a nejpozději do jednoho měsíce od jejího obdržení. U složitých nebo početných žádostí může být tato lhůta za podmínek GDPR prodloužena o další dva měsíce; o prodloužení a jeho důvodech bude žadatel informován v původní jednoměsíční lhůtě.</p></section>

    <section id="technologie"><h2>11. Cookies a lokální úložiště</h2><p>Technické cookies a lokální úložiště používáme pouze v rozsahu nezbytném pro provoz požadované funkce, zabezpečení, přihlášení nebo uložení uživatelské volby.</p><p>Netechnické cookies nebo obdobné technologie, například některé analytické nebo marketingové nástroje, aktivujeme pouze v souladu s právními požadavky. Tam, kde je nutný souhlas, nejsou takové technologie spuštěny před jeho udělením.</p><p>Souhlas lze odmítnout i později změnit nebo odvolat. Odmítnutí volitelných cookies nebrání používání služby, která je bez těchto cookies technicky dostupná.</p><p>Podrobnosti včetně účelu, poskytovatele a doby platnosti jednotlivých technologií jsou uvedeny v <Link href="/cookies">Zásadách používání cookies a lokálního úložiště</Link>.</p></section>

    <section id="bezpecnost"><h2>12. Bezpečnost osobních údajů</h2><p>Používáme přiměřená technická a organizační opatření odpovídající rizikům zpracování, zejména:</p><List><li>řízení přístupů podle rolí,</li><li>princip nejmenších oprávnění,</li><li>omezení přístupu moderátorů na nezbytný rozsah,</li><li>zabezpečený přenos dat,</li><li>ochranu účtů a relací,</li><li>omezení spamu a automatizovaných útoků,</li><li>auditní záznamy přístupů a moderátorských zásahů k citlivému nebo nahlášenému obsahu,</li><li>bezpečnou správu tajných klíčů a přístupových údajů,</li><li>pravidelné vyhodnocování bezpečnostních incidentů,</li><li>oddělení veřejných a neveřejných dat databázovými pravidly Row Level Security.</li></List><p>Tato opatření odpovídají současnému systému, ale nezaručují absolutní bezpečnost. StudentHub neslibuje end-to-end šifrování, úplnou anonymitu ani to, že infrastrukturní poskytovatelé nezpracují žádné technické údaje.</p></section>

    <section id="incidenty"><h2>13. Bezpečnostní incidenty</h2><p>Pokud zjistíme porušení zabezpečení osobních údajů, vyhodnotíme jeho rozsah, pravděpodobné dopady a přijmeme opatření k omezení následků.</p><p>Pokud to vyžaduje GDPR, oznámíme porušení zabezpečení Úřadu pro ochranu osobních údajů bez zbytečného odkladu a pokud možno do 72 hodin od okamžiku, kdy se o něm dozvíme. Pokud porušení pravděpodobně představuje vysoké riziko pro práva a svobody fyzických osob, informujeme za podmínek GDPR také dotčené osoby.</p></section>

    <section id="automatizace"><h2>14. Automatizované rozhodování a profilování</h2><p>StudentHub nepoužívá výlučně automatizované rozhodování, které by vůči uživateli vyvolávalo právní účinky nebo jej obdobným způsobem významně ovlivňovalo.</p><p>Pokud by StudentHub v budoucnu používal například automatické skórování rizika, profilování, automatické blokování účtu nebo jiný systém s významnými účinky, bude tato část před spuštěním funkce znovu posouzena a doplněna.</p><p>Běžné technické filtrování spamu nebo automatické bezpečnostní kontroly samy o sobě nepředstavují rozhodování podle čl. 22 GDPR, pokud nemají takový významný účinek; vždy záleží na jejich konkrétním účinku a způsobu použití. Významné moderátorské zásahy může posoudit oprávněná osoba.</p></section>

    <section id="externi"><h2>15. Externí odkazy a služby třetích stran</h2><p>StudentHub může obsahovat odkazy na weby nebo služby třetích stran, například na původní zdroj pracovní nabídky.</p><p>Po přechodu na externí web se zpracování osobních údajů řídí také podmínkami a zásadami dané třetí strany. StudentHub neodpovídá za obsah jejích zásad ochrany osobních údajů.</p><p>U externích pracovních nabídek StudentHub měří proklik vlastním agregovatelným záznamem bez jména, e-mailu nebo přesné IP adresy. Cílový web obdrží běžné technické údaje HTTP požadavku podle nastavení prohlížeče a své infrastruktury. Affiliate nebo reklamní měření není aktivní.</p></section>

    <section id="zmeny"><h2>16. Změny těchto zásad</h2><p>Tyto zásady můžeme aktualizovat například při změně funkcí StudentHubu, dodavatelů, technického řešení nebo právních požadavků.</p><p>U podstatných změn uvedeme novou verzi a datum účinnosti a podle povahy změny uživatele vhodným způsobem upozorníme, například přímo v aplikaci nebo e-mailem. Nový souhlas vyžádáme pouze tehdy, pokud je pro nové nebo změněné zpracování právně potřeba; samotná změna textu zásad neznamená automaticky nutnost získat nový souhlas.</p></section>

    <section id="stiznost"><h2>17. Stížnost u dozorového úřadu</h2><p>Pokud se domníváte, že s vašimi osobními údaji nakládáme v rozporu s právními předpisy, můžete se nejprve obrátit na správce prostřednictvím <a href={`mailto:${operator.email}`}>{operator.email}</a>.</p><p>Máte také právo podat stížnost u příslušného dozorového úřadu, zejména v členském státě svého obvyklého bydliště, místa výkonu zaměstnání nebo místa údajného porušení.</p><address><strong>Úřad pro ochranu osobních údajů</strong><br />Pplk. Sochora 27<br />170 00 Praha 7<br />E-mail: <a href="mailto:posta@uoou.gov.cz">posta@uoou.gov.cz</a><br />Datová schránka: qkbaa2n<br />Web: <a href="https://uoou.gov.cz" rel="external">uoou.gov.cz</a></address></section>
  </LegalPage>;
}
