import { NextResponse } from "next/server";
import { cleanPlaceText, invalidPlaceCommentReason } from "@/lib/place-community-server";
import { allowRequest, requestFingerprint } from "@/lib/rate-limit";
import { placeCommentUpdateSchema } from "@/lib/schemas";
import { createServiceClient } from "@/lib/supabase-server";
import { getCurrentAccount } from "@/lib/user-auth";

export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){const account=await getCurrentAccount();if(!account)return NextResponse.json({message:"Přihlaste se."},{status:401});if(!allowRequest(`place-comment-edit:${account.id}:${requestFingerprint(request)}`,40,60*60*1000))return NextResponse.json({message:"Limit úprav byl vyčerpán."},{status:429});const parsed=placeCommentUpdateSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Neplatná úprava."},{status:422});const body=cleanPlaceText(parsed.data.body,true);const invalid=invalidPlaceCommentReason(body);if(invalid)return NextResponse.json({message:invalid},{status:422});const id=(await context.params).id;const client=createServiceClient();const {data:item}=await client.from("place_comments").select("id,status").eq("id",id).eq("author_id",account.id).maybeSingle();if(!item||item.status!=="active")return NextResponse.json({message:"Zkušenost nebyla nalezena nebo vám nepatří."},{status:404});const {error}=await client.from("place_comments").update({body,edited_at:new Date().toISOString()}).eq("id",id).eq("author_id",account.id);if(error)return NextResponse.json({message:"Zkušenost se nepodařilo upravit."},{status:422});await client.from("place_comment_traits").delete().eq("comment_id",id);if(parsed.data.traits.length)await client.from("place_comment_traits").insert(parsed.data.traits.map((trait)=>({comment_id:id,trait})));return NextResponse.json({message:"Zkušenost byla upravena."});}
export async function DELETE(_request:Request,context:{params:Promise<{id:string}>}){const account=await getCurrentAccount();if(!account)return NextResponse.json({message:"Přihlaste se."},{status:401});const id=(await context.params).id;const {data,error}=await createServiceClient().from("place_comments").update({status:"deleted",deleted_at:new Date().toISOString()}).eq("id",id).eq("author_id",account.id).in("status",["active","hidden"]).select("id").maybeSingle();if(error||!data)return NextResponse.json({message:"Zkušenost nebyla nalezena nebo vám nepatří."},{status:404});return new NextResponse(null,{status:204});}
