-- Ověřená studentská místa pro Brno, Prahu, Olomouc a Ostravu.
-- Souřadnice vycházejí z oficiálních adres a byly ověřeny přes Nominatim/OSM.
-- Opakované spuštění je idempotentní; ruční textové úpravy existujících řádků se nepřepisují.

alter table public.places
  add column if not exists subcategory text,
  add column if not exists access_type text check (access_type is null or access_type in ('public','student','registered','mixed')),
  add column if not exists isic_required boolean,
  add column if not exists library_card_required boolean,
  add column if not exists registration_required boolean,
  add column if not exists reservation_url text check (reservation_url is null or reservation_url ~ '^https://'),
  add column if not exists opening_exceptions text,
  add column if not exists eduroam_available boolean,
  add column if not exists computers_available boolean,
  add column if not exists printing_available boolean,
  add column if not exists copying_available boolean,
  add column if not exists scanning_available boolean,
  add column if not exists study_mode text check (study_mode is null or study_mode in ('quiet','group','mixed','none')),
  add column if not exists reservable boolean,
  add column if not exists evening_access boolean,
  add column if not exists nonstop_access boolean,
  add column if not exists temporary_status text check (temporary_status is null or temporary_status in ('open','limited','temporarily_closed')),
  add column if not exists source_etag text,
  add column if not exists source_last_modified text,
  add column if not exists source_content_hash text check (source_content_hash is null or source_content_hash ~ '^[a-f0-9]{64}$');

create index if not exists places_public_city_category_subcategory_idx
  on public.places(city_id,category,subcategory,name)
  where status='approved' and is_demo=false and verification_status='verified';
create index if not exists places_public_viewport_idx
  on public.places(city_id,latitude,longitude,category)
  where status='approved' and is_demo=false and verification_status='verified';

grant select (subcategory,access_type,isic_required,library_card_required,registration_required,reservation_url,opening_exceptions,eduroam_available,computers_available,printing_available,copying_available,scanning_available,study_mode,reservable,evening_access,nonstop_access,temporary_status)
  on public.places to anon, authenticated;

with seed as (
  select * from jsonb_to_recordset($json$
  [
    {"id":"c1070001-0000-4000-8000-000000000001","city":"brno","name":"Knihovna Fakulty architektury VUT","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna a studijní zázemí Fakulty architektury VUT.","address":"Poříčí 273/5, Brno","lat":49.186872,"lng":16.593911,"hours":"Po–Čt 9:00–16:00, Pá 9:00–14:00","source":"https://www.vut.cz/knihovny/seznam","university":"vut","faculty":"vut-fa","access":"Aktuální režim vstupu a výpůjček ověřte v oficiálním seznamu knihoven VUT.","study_mode":"quiet"},
    {"id":"c1070002-0000-4000-8000-000000000002","city":"brno","name":"Knihovna Fakulty stavební VUT","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna a studijní zázemí FAST VUT.","address":"Veveří 331/95, Brno","lat":49.206410,"lng":16.592335,"hours":"Po–Pá 7:30–18:00","source":"https://www.vut.cz/knihovny/seznam","university":"vut","faculty":"vut-fast","access":"Aktuální režim vstupu a výpůjček ověřte v oficiálním seznamu knihoven VUT.","study_mode":"quiet","evening":true},
    {"id":"c1070003-0000-4000-8000-000000000003","city":"brno","name":"Knihovna Fakulty chemické VUT","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna a studijní zázemí FCH VUT.","address":"Purkyňova 464/118, Brno","lat":49.231308,"lng":16.578448,"hours":"Po–Čt 9:00–16:00, Pá 9:00–14:00","source":"https://www.vut.cz/knihovny/seznam","university":"vut","faculty":"vut-fch","access":"Aktuální režim vstupu a výpůjček ověřte v oficiálním seznamu knihoven VUT.","study_mode":"quiet"},
    {"id":"c1070004-0000-4000-8000-000000000004","city":"brno","name":"Knihovna Fakulty strojního inženýrství VUT","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna a studijní zázemí FSI VUT.","address":"Technická 2896/2, Brno","lat":49.224387,"lng":16.577028,"hours":"Po–Čt 7:30–16:00, Pá 7:30–11:00","source":"https://www.vut.cz/knihovny/seznam","university":"vut","faculty":"vut-fsi","access":"Aktuální režim vstupu a výpůjček ověřte v oficiálním seznamu knihoven VUT.","study_mode":"quiet"},
    {"id":"c1070005-0000-4000-8000-000000000005","city":"brno","name":"Knihovna Přírodovědecké fakulty MUNI","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna PřF MUNI v areálu na Kotlářské.","address":"Kotlářská 267/2, pavilon 12, Brno","lat":49.203869,"lng":16.597439,"source":"https://knihovny.muni.cz/knihovny-masarykovy-univerzity","university":"muni","faculty":"muni-prf","access":"Podmínky vstupu a výpůjček ověřte na oficiální stránce knihoven MUNI.","study_mode":"quiet"},
    {"id":"c1070006-0000-4000-8000-000000000006","city":"brno","name":"Knihovna Pedagogické fakulty MUNI","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna PdF MUNI na Poříčí.","address":"Poříčí 997/31a, Brno","lat":49.186865,"lng":16.599136,"source":"https://knihovny.muni.cz/knihovny-masarykovy-univerzity","university":"muni","faculty":"muni-pedf","access":"Podmínky vstupu a výpůjček ověřte na oficiální stránce knihoven MUNI.","study_mode":"quiet"},
    {"id":"c1070007-0000-4000-8000-000000000007","city":"brno","name":"Knihovna Ekonomicko-správní fakulty MUNI","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna ESF MUNI v areálu na Lipové.","address":"Lipová 507/41a, Brno","lat":49.193293,"lng":16.577299,"source":"https://knihovny.muni.cz/knihovny-masarykovy-univerzity","university":"muni","faculty":"muni-esf","access":"Podmínky vstupu a výpůjček ověřte na oficiální stránce knihoven MUNI.","study_mode":"quiet"},
    {"id":"c1070008-0000-4000-8000-000000000008","city":"brno","name":"Knihovna Fakulty sociálních studií MUNI","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna FSS MUNI na Joštově.","address":"Joštova 218/10, Brno","lat":49.197344,"lng":16.602246,"source":"https://knihovny.muni.cz/knihovny-masarykovy-univerzity","university":"muni","faculty":"muni-fss","access":"Podmínky vstupu a výpůjček ověřte na oficiální stránce knihoven MUNI.","study_mode":"quiet"},
    {"id":"c1070009-0000-4000-8000-000000000009","city":"brno","name":"Ústřední knihovna Právnické fakulty MUNI","category":"library","subcategory":"faculty_library","description":"Knihovna a studijní prostor Právnické fakulty MUNI.","address":"Veveří 70, Brno","lat":49.208356,"lng":16.592524,"source":"https://knihovny.muni.cz/knihovny-masarykovy-univerzity","university":"muni","faculty":"muni-prav","access":"Podmínky vstupu a výpůjček ověřte na oficiální stránce knihoven MUNI.","study_mode":"quiet"},
    {"id":"c1070010-0000-4000-8000-000000000010","city":"brno","name":"Středisko Teiresiás – knihovní a studijní služby","category":"student_service","subcategory":"accessible_study_support","description":"Studijní a knihovní podpora MUNI pro studenty se specifickými nároky.","address":"Komenského náměstí 220/2, Brno","lat":49.196674,"lng":16.602867,"source":"https://knihovny.muni.cz/knihovny-masarykovy-univerzity","university":"muni","access":"Služby a režim návštěvy ověřte na oficiálním webu střediska.","student_only":true,"access_type":"student","study_mode":"mixed","accessibility":"accessible"},

    {"id":"c2070001-0000-4000-8000-000000000001","city":"praha","name":"Knihovna ČVUT – FJFI","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna ČVUT pro FJFI v Břehové ulici.","address":"Břehová 78/7, Praha 1","lat":50.090899,"lng":14.416235,"source":"https://www.knihovna.cvut.cz/o-nas/kontakt/kde-nas-najdete","university":"cvut","faculty":"cvut-fjfi","access":"Podmínky vstupu a výpůjček ověřte na oficiální stránce knihovny ČVUT.","study_mode":"quiet"},
    {"id":"c2070002-0000-4000-8000-000000000002","city":"praha","name":"Knihovna ČVUT – Fakulta dopravní","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna ČVUT pro Fakultu dopravní v Horské ulici.","address":"Horská 2040/3, Praha 2","lat":50.067503,"lng":14.424079,"source":"https://www.knihovna.cvut.cz/o-nas/kontakt/kde-nas-najdete","university":"cvut","faculty":"cvut-fd","access":"Podmínky vstupu a výpůjček ověřte na oficiální stránce knihovny ČVUT.","study_mode":"quiet"},
    {"id":"c2070003-0000-4000-8000-000000000003","city":"praha","name":"Studijní knihovna VŠE Jižní Město","category":"library","subcategory":"university_library","description":"Studijní knihovna VŠE se studijními místy, počítači, Wi-Fi a reprografickými službami.","address":"Ekonomická 957, Praha 4","lat":50.020340,"lng":14.492525,"hours":"Po–Pá 9:00–16:00","source":"https://knihovna.vse.cz/knihovny-studovny/studijni-knihovna-jizni-mesto-skjm/","university":"vse","access":"Vstup a výpůjční služby jsou vázané na registraci nebo školní kartu podle pravidel VŠE.","student_only":true,"access_type":"student","registration_required":true,"study_mode":"quiet","wifi":true,"computers":true,"printing":true,"copying":true,"scanning":true},
    {"id":"c2070004-0000-4000-8000-000000000004","city":"praha","name":"Ústřední knihovna Městské knihovny v Praze","category":"library","subcategory":"public_library","description":"Hlavní veřejná knihovna s čítárnami, Wi-Fi, počítači a tiskem v centru Prahy.","address":"Mariánské náměstí 98/1, Praha 1","lat":50.087453,"lng":14.417381,"source":"https://www.mlp.cz/pobocky/ustredni-knihovna/","access":"Studium na místě je veřejné; pro výpůjčky je potřeba registrace čtenáře.","public_access":true,"access_type":"public","library_card_required":true,"study_mode":"mixed","wifi":true,"computers":true,"printing":true,"accessibility":"accessible"},
    {"id":"c2070005-0000-4000-8000-000000000005","city":"praha","name":"Dům čtení Městské knihovny v Praze","category":"library","subcategory":"public_library","description":"Veřejná pobočka MLP zaměřená na čtení, literaturu a klidný pobyt.","address":"Ruská 1455/192, Praha 10","lat":50.072291,"lng":14.483549,"source":"https://www.mlp.cz/cz/pobocky","access":"Studium na místě je veřejné; pro výpůjčky je potřeba registrace čtenáře.","public_access":true,"access_type":"public","library_card_required":true,"study_mode":"quiet"},
    {"id":"c2070006-0000-4000-8000-000000000006","city":"praha","name":"Městská knihovna v Praze – Smíchov","category":"library","subcategory":"public_library","description":"Veřejná pobočka MLP na Smíchově vhodná pro čtení a studium.","address":"náměstí 14. října 83/15, Praha 5","lat":50.073920,"lng":14.406673,"source":"https://www.mlp.cz/cz/pobocky","access":"Studium na místě je veřejné; pro výpůjčky je potřeba registrace čtenáře.","public_access":true,"access_type":"public","library_card_required":true,"study_mode":"quiet"},
    {"id":"c2070007-0000-4000-8000-000000000007","city":"praha","name":"Počítačová studovna VŠCHT","category":"study_room","subcategory":"computer_study_room","description":"Počítačová studovna VŠCHT určená pro samostatné studium a práci se školním softwarem.","address":"Technická 1905/5, Praha 6","lat":50.103351,"lng":14.389830,"hours":"Po–Čt 7:30–19:30, Pá 7:30–17:45","source":"https://vc.vscht.cz/stud/ucebny","university":"vscht","access":"Pouze pro studenty VŠCHT; vstup do vybraných učeben vyžaduje identifikační kartu školy.","student_only":true,"access_type":"student","study_mode":"quiet","computers":true,"printing":true,"evening":true},
    {"id":"c2070008-0000-4000-8000-000000000008","city":"praha","name":"Knihovna a studovna 1. LF UK","category":"library","subcategory":"faculty_library","description":"Knihovna, studovna a PC terminálovna 1. LF UK s tiskem, kopírováním a skenováním.","address":"U Nemocnice 4, Praha 2","lat":50.073535,"lng":14.423237,"hours":"Po 8:00–19:45, Út 10:00–19:45, St–Čt 8:00–19:45, Pá 8:00–15:45","source":"https://uvi.lf1.cuni.cz/navody-a-pomucky/zakladni-informace-pro-studenty-1-rocniku","university":"cuni","faculty":"cuni-lf1","access":"Pro vstup a knihovní služby je potřeba průkaz UK nebo odpovídající externí průkaz.","student_only":true,"access_type":"registered","isic_required":true,"registration_required":true,"study_mode":"quiet","wifi":true,"eduroam":true,"computers":true,"printing":true,"copying":true,"scanning":true,"evening":true},
    {"id":"c2070009-0000-4000-8000-000000000009","city":"praha","name":"Knihovna a studovna informatiky MFF UK","category":"library","subcategory":"faculty_library","description":"Knihovna a klidná studovna informatiky MFF UK v malostranské rotundě.","address":"Malostranské náměstí 2/25, Praha 1","lat":50.088487,"lng":14.403186,"source":"https://cs.mff.cuni.cz/cs/pro-studenty/pro-prvaky","university":"cuni","faculty":"cuni-mff","access":"Fakultní studijní prostor; aktuální podmínky vstupu ověřte na webu MFF UK.","student_only":true,"access_type":"student","study_mode":"quiet","outlets":true,"accessibility":"accessible"},
    {"id":"c2070010-0000-4000-8000-000000000010","city":"praha","name":"Knihovna Právnické fakulty UK","category":"library","subcategory":"faculty_library","description":"Odborná právnická knihovna se studovnami v budově Právnické fakulty UK.","address":"náměstí Curieových 901/7, Praha 1","lat":50.091839,"lng":14.417215,"source":"https://knihovna.prf.cuni.cz/o-nas","university":"cuni","faculty":"cuni-prf","access":"Přístup ke službám a databázím se liší podle kategorie uživatele; ověřte na webu knihovny.","access_type":"mixed","study_mode":"quiet"},

    {"id":"c3070001-0000-4000-8000-000000000001","city":"olomouc","name":"Knihovna PřF UP – Envelopa","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna Přírodovědecké fakulty UP v areálu Envelopa.","address":"17. listopadu 1192/12, Olomouc","lat":49.592400,"lng":17.263500,"hours":"Po–St 8:00–18:00, Čt 8:00–15:00, Pá 8:00–14:00","source":"https://www.knihovna.upol.cz/pobocky/prf/","university":"upol","faculty":"upol-prf","access":"Podmínky vstupu a výpůjček ověřte na stránce pobočky Knihovny UP.","study_mode":"quiet","evening":true},
    {"id":"c3070002-0000-4000-8000-000000000002","city":"olomouc","name":"Knihovna PřF UP – Holice","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna Přírodovědecké fakulty UP v areálu Holice.","address":"Šlechtitelů 27, Olomouc","lat":49.575619,"lng":17.282793,"hours":"Po–Čt 8:00–15:00, Pá 8:00–14:00; přestávka 12:00–12:30","source":"https://www.knihovna.upol.cz/pobocky/prf/","university":"upol","faculty":"upol-prf","access":"Podmínky vstupu a výpůjček ověřte na stránce pobočky Knihovny UP.","study_mode":"quiet"},
    {"id":"c3070003-0000-4000-8000-000000000003","city":"olomouc","name":"Knihovna CMTF UP","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna Cyrilometodějské teologické fakulty UP.","address":"Univerzitní 22, Olomouc","lat":49.594718,"lng":17.254944,"hours":"Po a St 9:00–18:00, Út a Čt 9:00–16:00, Pá 9:00–13:00, So 9:30–13:30","source":"https://www.knihovna.upol.cz/pobocky/cmtf/","university":"upol","faculty":"upol-cmtf","access":"Podmínky vstupu a výpůjček ověřte na stránce pobočky Knihovny UP.","study_mode":"quiet","evening":true},
    {"id":"c3070004-0000-4000-8000-000000000004","city":"olomouc","name":"Knihovna LF a FZV UP","category":"library","subcategory":"faculty_library","description":"Společná lékařská knihovna a studovna pro LF a FZV UP s reprografickými službami.","address":"Hněvotínská 3, Olomouc","lat":49.586281,"lng":17.236603,"hours":"Po–St 8:00–18:00, Čt–Pá 8:00–15:30","source":"https://www.knihovna.upol.cz/pobocky/lf/","university":"upol","faculty":"upol-lf","access":"Podmínky vstupu a výpůjček ověřte na stránce pobočky Knihovny UP.","study_mode":"quiet","printing":true,"copying":true,"scanning":true,"evening":true},
    {"id":"c3070005-0000-4000-8000-000000000005","city":"olomouc","name":"Knihovna FTK UP","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna FTK UP s počítači, skenerem a studijními místy.","address":"třída Míru 117, Olomouc","lat":49.594453,"lng":17.213474,"hours":"Po–Čt 9:00–16:00, Pá 9:00–14:00","source":"https://www.knihovna.upol.cz/pobocky/ftk/","university":"upol","faculty":"upol-ftk","access":"Podmínky vstupu a výpůjček ověřte na stránce pobočky Knihovny UP.","study_mode":"quiet","computers":true,"copying":true,"scanning":true},
    {"id":"c3070006-0000-4000-8000-000000000006","city":"olomouc","name":"Vědecká knihovna v Olomouci","category":"library","subcategory":"public_library","description":"Veřejná krajská knihovna se studijními místy a počítači v centru Olomouce.","address":"Bezručova 659/2, Olomouc","lat":49.593817,"lng":17.247018,"hours":"Po–Pá 8:30–19:00, So 9:00–13:00","source":"https://www.vkol.cz/knihovny-olomouckeho-kraje/olomouc/vedecka-knihovna-v-olomouci","access":"Studium na místě je veřejné; výpůjční služby se řídí registrací a knihovním řádem.","public_access":true,"access_type":"public","library_card_required":true,"study_mode":"mixed","computers":true,"evening":true},

    {"id":"c4070001-0000-4000-8000-000000000001","city":"ostrava","name":"Knihovna VŠB-TUO – FBI","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna a studovna Fakulty bezpečnostního inženýrství VŠB-TUO.","address":"Lumírova 630/13, Ostrava","lat":49.777546,"lng":18.218776,"hours":"Po–St 8:00–11:30 a 12:30–15:30, Čt 12:00–15:30, Pá 8:00–11:30 a 12:30–15:30","source":"https://knihovna.vsb.cz/cs/o-knihovne/kontakty/","university":"vsbtuo","faculty":"vsbtuo-fbi","access":"Podmínky vstupu a výpůjček ověřte na webu Ústřední knihovny VŠB-TUO.","student_only":true,"access_type":"student","study_mode":"quiet"},
    {"id":"c4070002-0000-4000-8000-000000000002","city":"ostrava","name":"Knihovna VŠB-TUO – FAST","category":"library","subcategory":"faculty_library","description":"Fakultní knihovna a studovna Fakulty stavební VŠB-TUO.","address":"Ludvíka Podéště 1875/17, Ostrava","lat":49.845182,"lng":18.153340,"hours":"Po–St 8:00–11:30 a 12:30–15:30, Čt 12:00–15:30, Pá 8:00–11:30 a 12:30–15:30","source":"https://knihovna.vsb.cz/cs/o-knihovne/kontakty/","university":"vsbtuo","faculty":"vsbtuo-fast","access":"Podmínky vstupu a výpůjček ověřte na webu Ústřední knihovny VŠB-TUO.","student_only":true,"access_type":"student","study_mode":"quiet"},
    {"id":"c4070003-0000-4000-8000-000000000003","city":"ostrava","name":"Moravskoslezská vědecká knihovna v Ostravě","category":"library","subcategory":"public_library","description":"Veřejná krajská knihovna s odbornými fondy, studijními a informačními službami.","address":"Prokešovo náměstí 1802/9, Ostrava","lat":49.841103,"lng":18.291120,"source":"https://www.msvk.cz/kontakty/zakladni-informace/","access":"Studium na místě je veřejné; výpůjční služby se řídí registrací a knihovním řádem.","public_access":true,"access_type":"public","library_card_required":true,"study_mode":"quiet"},
    {"id":"c4070004-0000-4000-8000-000000000004","city":"ostrava","name":"Knihovna města Ostravy – Malá půjčovna","category":"library","subcategory":"public_library","description":"Dočasné omezené pracoviště Ústřední knihovny KMO během rekonstrukce.","address":"28. října 2, Ostrava","lat":49.837333,"lng":18.295502,"hours":"Po–Út 8:00–18:00, St 12:00–18:00, Čt–Pá 8:00–18:00, So 8:30–12:00","source":"https://www.kmo.cz/pobocky/ustredni-knihovna/mala-pujcovna/","access":"Veřejná knihovna; pro výpůjčky je potřeba registrace. Rozsah služeb je během rekonstrukce omezený.","public_access":true,"access_type":"public","library_card_required":true,"study_mode":"none","temporary_status":"limited","opening_exceptions":"Ústřední knihovna je v rekonstrukci; Malá půjčovna poskytuje služby v omezeném režimu.","accessibility":"accessible","evening":true},
    {"id":"c4070005-0000-4000-8000-000000000005","city":"ostrava","name":"Knihovna města Ostravy – Vietnamská","category":"library","subcategory":"public_library","description":"Veřejná pobočka KMO v Porubě s oddělením pro dospělé a studijním zázemím.","address":"Vietnamská 1541/3, Ostrava-Poruba","lat":49.822158,"lng":18.191024,"hours":"Po–Út 8:00–18:00, Čt 8:00–18:00, Pá 8:00–16:00","source":"https://www.kmo.cz/pobocky/vietnamska/","access":"Veřejná knihovna; pro výpůjčky je potřeba registrace čtenáře.","public_access":true,"access_type":"public","library_card_required":true,"study_mode":"quiet","accessibility":"accessible","evening":true},
    {"id":"c4070006-0000-4000-8000-000000000006","city":"ostrava","name":"Studovna Fakulty umění OU","category":"study_room","subcategory":"faculty_study_room","description":"Fakultní studovna OU s odbornou literaturou, počítači, eduroamem, tiskem, kopírováním a skenováním.","address":"Podlahova 382/3, Ostrava","lat":49.832594,"lng":18.255334,"hours":"Út–St 9:00–12:00 a 13:00–17:00","source":"https://knihovna.osu.cz/studovna-fu/","university":"osu","faculty":"osu-fu","access":"Studovna je součástí Univerzitní knihovny OU; výpůjční služby se řídí registrací uživatele.","student_only":true,"access_type":"student","registration_required":true,"study_mode":"quiet","eduroam":true,"computers":true,"printing":true,"copying":true,"scanning":true},
    {"id":"c4070007-0000-4000-8000-000000000007","city":"ostrava","name":"Studovna Filozofické fakulty OU","category":"study_room","subcategory":"faculty_study_room","description":"Fakultní studovna OU s odborným fondem a místy pro samostatné studium.","address":"Reální 1476/5, Ostrava","lat":49.836365,"lng":18.290068,"source":"https://knihovna.osu.cz/studovna-ff/","university":"osu","faculty":"osu-ff","access":"Studovna je součástí Univerzitní knihovny OU; aktuální podmínky ověřte na webu.","student_only":true,"access_type":"student","study_mode":"quiet"},
    {"id":"c4070008-0000-4000-8000-000000000008","city":"ostrava","name":"Studovna Lékařské fakulty OU","category":"study_room","subcategory":"faculty_study_room","description":"Fakultní studovna OU pro studenty a pracovníky Lékařské fakulty.","address":"Syllabova 2883/19, Ostrava","lat":49.811835,"lng":18.250504,"source":"https://knihovna.osu.cz/studovna-lf/","university":"osu","faculty":"osu-lf","access":"Studovna je součástí Univerzitní knihovny OU; aktuální podmínky ověřte na webu.","student_only":true,"access_type":"student","study_mode":"quiet"},
    {"id":"c4070009-0000-4000-8000-000000000009","city":"ostrava","name":"Studovna Pedagogické fakulty OU","category":"study_room","subcategory":"faculty_study_room","description":"Fakultní studovna OU pro studenty a pracovníky Pedagogické fakulty.","address":"Fráni Šrámka 1121/3, Ostrava","lat":49.827398,"lng":18.262770,"source":"https://knihovna.osu.cz/studovna-pdf/","university":"osu","faculty":"osu-pdf","access":"Studovna je součástí Univerzitní knihovny OU; aktuální podmínky ověřte na webu.","student_only":true,"access_type":"student","study_mode":"quiet"},
    {"id":"c4070010-0000-4000-8000-000000000010","city":"ostrava","name":"Studovna Přírodovědecké fakulty OU","category":"study_room","subcategory":"faculty_study_room","description":"Fakultní studovna OU pro studenty a pracovníky Přírodovědecké fakulty.","address":"30. dubna 1404/22, Ostrava","lat":49.840603,"lng":18.288330,"source":"https://knihovna.osu.cz/studovna-prf/","university":"osu","faculty":"osu-prf","access":"Studovna je součástí Univerzitní knihovny OU; aktuální podmínky ověřte na webu.","student_only":true,"access_type":"student","study_mode":"quiet"}
  ]
  $json$::jsonb) as p(
    id text, city text, name text, category text, subcategory text, description text,
    address text, lat numeric, lng numeric, hours text, source text, university text,
    faculty text, access text, public_access boolean, student_only boolean,
    access_type text, isic_required boolean, library_card_required boolean,
    registration_required boolean, study_mode text, wifi boolean, eduroam boolean,
    outlets boolean, computers boolean, printing boolean, copying boolean, scanning boolean,
    reservable boolean, evening boolean, nonstop boolean, temporary_status text,
    opening_exceptions text, accessibility text
  )
)
insert into public.places (
  id,city_id,name,category,subcategory,description,why_visit,address,latitude,longitude,
  opening_hours,website_url,source_url,last_verified_at,opening_hours_verified_at,
  verification_status,source_sync_status,source_checked_at,status,is_demo,access_conditions,
  university_id,faculty_id,origin,study_suitable,wifi_available,eduroam_available,
  outlets_available,computers_available,printing_available,copying_available,scanning_available,
  public_access,student_only,access_type,isic_required,library_card_required,registration_required,
  study_mode,reservable,evening_access,nonstop_access,temporary_status,opening_exceptions,
  accessibility,source_license,source_external_id,source_dataset_updated_at
)
select
  id::uuid,city,name,category::public.place_category,subcategory,description,
  case when category='student_service' then 'Praktická podpora při studiu.' else 'Ověřené místo pro studium, práci s odbornými zdroji nebo klidný pobyt.' end,
  address,lat,lng,hours,source,source,'2026-10-07 12:00:00+02'::timestamptz,
  case when hours is not null then '2026-10-07 12:00:00+02'::timestamptz end,
  'verified','verified','2026-10-07 12:00:00+02'::timestamptz,'approved',false,access,
  university,faculty,'official',category in ('library','study_room','student_service'),wifi,eduroam,
  outlets,computers,printing,copying,scanning,public_access,student_only,access_type,
  isic_required,library_card_required,registration_required,study_mode,reservable,evening,nonstop,
  coalesce(temporary_status,'open'),opening_exceptions,accessibility,
  'Oficiální veřejný web provozovatele; poloha ověřena pomocí OpenStreetMap',
  'official-place:' || city || ':' || regexp_replace(lower(name),'[^a-z0-9]+','-','g'),
  '2026-10-07 12:00:00+02'::timestamptz
from seed
on conflict (id) do update set
  source_url=excluded.source_url,
  website_url=excluded.website_url,
  last_verified_at=excluded.last_verified_at,
  source_checked_at=excluded.source_checked_at,
  verification_status='verified',
  source_sync_status='verified',
  subcategory=coalesce(public.places.subcategory,excluded.subcategory),
  access_type=coalesce(public.places.access_type,excluded.access_type),
  study_mode=coalesce(public.places.study_mode,excluded.study_mode),
  source_dataset_updated_at=excluded.source_dataset_updated_at;

-- Dvě dříve založené kopie byly v produkci potvrzeny jako stejné provozovny.
-- Zachováváme jejich historii, ale v katalogu ponecháváme pouze bohatší ověřený záznam.
update public.places set status='archived', updated_at=now()
where id in (
  '52222222-2222-4222-8222-222222222226'::uuid,
  '52222222-2222-4222-8222-222222222227'::uuid
) and city_id='brno' and status='approved';
