import { readFileSync } from "node:fs";
import { afterEach, describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { filterMarketplaceListings, publicMarketplaceListing } from "@/lib/marketplace-public";
import { marketplaceDuplicateFingerprint, marketplaceHash, newMarketplaceToken, prohibitedMarketplaceReason, relayMarketplaceContact } from "@/lib/marketplace-server";
import { marketplacePriceLabel, type MarketplaceListing } from "@/lib/marketplace-types";
import { marketplaceContactSchema, marketplaceListingSchema, marketplaceReportSchema, marketplaceVerificationSchema } from "@/lib/schemas";

const valid = { listingType: "offer", category: "textbook", title: "Lineární algebra", shortDescription: "Zachovalá učebnice pro první ročník.", description: "Vlastní fyzický výtisk učebnice je zachovalý a bez chybějících stran.", priceMode: "fixed", priceAmount: 240, priceScope: "item", universityId: "vut", facultyId: "vut-fekt", studyProgram: "Elektrotechnika", subjectName: "Matematika", subjectCode: "BMA1", teacherName: "", recommendedYear: 1, semester: "winter", academicYear: "2026/2027", materialFormat: "printed", itemCondition: "used", handoffMethod: "in_person", handoffLocation: "Technická", publicAlias: "Adam", sellerEmail: "adam@example.cz", copyrightConfirmed: true, ownNotesConfirmed: false, privacyConsent: true, company: "", cityId: "brno" };
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllEnvs(); });

function listing(overrides: Partial<MarketplaceListing> = {}): MarketplaceListing { return { id: "11111111-1111-4111-8111-111111111111", cityId: "brno", listingType: "offer", category: "textbook", title: "Lineární algebra", shortDescription: "Zachovalá učebnice", description: "Dlouhý bezpečný popis fyzické učebnice.", priceMode: "fixed", priceAmount: 240, priceScope: "item", universityId: "vut", facultyId: "vut-fekt", subjectName: "Matematika", teacherName: "Novák", recommendedYear: 1, semester: "winter", academicYear: "2026/2027", materialFormat: "printed", itemCondition: "used", handoffMethod: "in_person", handoffLocation: "Technická", publicAlias: "Adam", status: "active", publishedAt: "2026-08-23T10:00:00Z", expiresAt: "2026-09-22T10:00:00Z", createdAt: "2026-08-23T09:00:00Z", updatedAt: "2026-08-23T10:00:00Z", photos: [], ...overrides }; }

describe("Studentská burza – validace", () => {
  it("přijme úplný inzerát a zachová vazbu VUT + FEKT", () => { const result = marketplaceListingSchema.safeParse(valid); expect(result.success).toBe(true); if (result.success) expect(result.data).toMatchObject({ universityId: "vut", facultyId: "vut-fekt", priceAmount: 240 }); });
  it("odmítne cizí fakultu, chybějící cenu, stav digitálního souboru a honeypot", () => { expect(marketplaceListingSchema.safeParse({ ...valid, universityId: "muni" }).success).toBe(false); expect(marketplaceListingSchema.safeParse({ ...valid, priceAmount: undefined }).success).toBe(false); expect(marketplaceListingSchema.safeParse({ ...valid, materialFormat: "digital", itemCondition: "used" }).success).toBe(false); expect(marketplaceListingSchema.safeParse({ ...valid, company: "robot" }).success).toBe(false); });
  it("vyžaduje autorství vlastních poznámek", () => { expect(marketplaceListingSchema.safeParse({ ...valid, category: "own_notes", ownNotesConfirmed: false }).success).toBe(false); expect(marketplaceListingSchema.safeParse({ ...valid, category: "own_notes", ownNotesConfirmed: true }).success).toBe(true); });
  it("validuje ověření, kontakt a hlášení", () => { expect(marketplaceVerificationSchema.safeParse({ verificationToken: "a".repeat(64), managementToken: "b".repeat(64) }).success).toBe(true); expect(marketplaceContactSchema.safeParse({ buyerEmail: "buyer@example.cz", message: "Mám zájem, je učebnice stále dostupná?", consent: true, company: "" }).success).toBe(true); expect(marketplaceContactSchema.safeParse({ buyerEmail: "x", message: "krátká", consent: false, company: "bot" }).success).toBe(false); expect(marketplaceReportSchema.safeParse({ reason: "copyright", detail: "Podezření na nelegální kopii.", company: "" }).success).toBe(true); });
  it("odesílá kontakt jen serverovým relayem s adresou zájemce jako Reply-To", async () => { vi.stubEnv("RESEND_API_KEY", "server-test-key"); vi.stubEnv("MARKETPLACE_FROM_EMAIL", "StudentHub Burza <burza@example.cz>"); const fetchMock = vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response(JSON.stringify({ id: "mail-test" }), { status: 200, headers: { "content-type": "application/json" } })); const result = await relayMarketplaceContact({ sellerEmail: "seller@example.cz", buyerEmail: "buyer@example.cz", title: "Lineární algebra", message: "Mám zájem o osobní předání učebnice." }); expect(result).toEqual({ ok: true, id: "mail-test" }); const request = JSON.parse(String(fetchMock.mock.calls[0][1]?.body)); expect(request).toMatchObject({ to: ["seller@example.cz"], reply_to: "buyer@example.cz" }); });
});

describe("Studentská burza – soukromí a filtrování", () => {
  it("veřejný mapper nikdy nepropustí e-mail, token ani interní poznámku", () => { const item = publicMarketplaceListing({ id: listing().id, city_id: "brno", listing_type: "offer", category: "textbook", title: "Lineární algebra", short_description: "Zachovalá učebnice", description: "Dlouhý bezpečný popis fyzické učebnice.", price_mode: "fixed", price_amount: 240, price_scope: "item", semester: "winter", material_format: "printed", item_condition: "used", handoff_method: "in_person", public_alias: "Adam", status: "active", published_at: "2026-08-23T10:00:00Z", expires_at: "2026-09-22T10:00:00Z", created_at: "2026-08-23T09:00:00Z", seller_email: "private@example.cz", buyer_email: "buyer@example.cz", management_token_hash: "secret", moderation_note: "private" }); const json = JSON.stringify(item); expect(item).not.toBeNull(); expect(json).not.toMatch(/private@example|buyer@example|secret|moderation_note|seller_email/); });
  it("filtruje školu, fakultu, vyučujícího, stav, cenu a řadí podle relevance", () => { const items = [listing(), listing({ id: "22222222-2222-4222-8222-222222222222", universityId: "muni", facultyId: "muni-fi", teacherName: "Svoboda", priceAmount: 0, priceMode: "free", itemCondition: "like_new", publishedAt: "2026-08-24T10:00:00Z" })]; expect(filterMarketplaceListings(items, { university: "vut", faculty: "vut-fekt", teacher: "nov", condition: "used", minPrice: 200 })).toHaveLength(1); expect(filterMarketplaceListings(items, { condition: "worn" })).toHaveLength(0); expect(filterMarketplaceListings(items, { sort: "free" })[0].priceMode).toBe("free"); expect(filterMarketplaceListings(items, { sort: "relevant" }, { universityId: "vut", facultyId: "vut-fekt" })[0].facultyId).toBe("vut-fekt"); });
  it("formátuje zdarma, dohodou a cenu za balíček", () => { expect(marketplacePriceLabel(listing({ priceMode: "free", priceAmount: 0 }))).toBe("Zdarma"); expect(marketplacePriceLabel(listing({ priceMode: "negotiable", priceAmount: undefined }))).toBe("Dohodou"); expect(marketplacePriceLabel(listing({ priceAmount: 1200, priceScope: "bundle" }))).toContain("za balíček"); });
});

describe("Studentská burza – bezpečnostní primitiva a migrace", () => {
  it("vytváří náhodný 256bit token a ukládá pouze stabilní hash", () => { const first = newMarketplaceToken(); const second = newMarketplaceToken(); expect(first.token).toMatch(/^[a-f0-9]{64}$/); expect(first.hash).toBe(marketplaceHash(first.token)); expect(first.token).not.toBe(second.token); expect(marketplaceDuplicateFingerprint({ title: "Žluťoučká učebnice", category: "textbook", subjectCode: "BMA1" })).toBe(marketplaceDuplicateFingerprint({ title: "Zlutoucka ucebnice", category: "textbook", subjectCode: "BMA1" })); });
  it("zachytí typické nelegální kopie a akademické podvádění", () => { expect(prohibitedMarketplaceReason({ title: "PDF učebnice", shortDescription: "Levně", description: "Prodám PDF učebnice jako nelegální kopii." })).toMatch(/kopii/); expect(prohibitedMarketplaceReason({ title: "Hotový projekt", shortDescription: "Odevzdání", description: "Napíšu za tebe celý hodnocený projekt." })).toMatch(/podvádění/); expect(prohibitedMarketplaceReason({ title: "Fyzická kniha", shortDescription: "Použitá", description: "Prodám vlastní fyzický výtisk knihy." })).toBeNull(); });
  it("migrace odděluje burzu od technických žádostí, chrání RLS a privátní bucket", () => { const sql = readFileSync("supabase/migrations/202608230028_student_marketplace.sql", "utf8"); for (const table of ["marketplace_listings", "marketplace_listing_photos", "marketplace_messages", "marketplace_reports", "marketplace_history", "marketplace_moderation_actions"]) expect(sql).toContain(`public.${table}`); expect(sql).toContain("public=false"); expect(sql).toContain("revoke all on public.marketplace_listings"); expect(sql).not.toMatch(/insert into public\.service_requests/i); expect(sql).not.toMatch(/demo|ukázkov/i); });
});
