import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { cleanPlaceText, invalidPlaceCommentReason, publicPlaceComments } from "@/lib/place-community-server";
import { allowRequest, requestFingerprint } from "@/lib/rate-limit";
import { placeCommentSchema } from "@/lib/schemas";
import { createServiceClient, isSupabaseConfigured } from "@/lib/supabase-server";
import { getCurrentAccount } from "@/lib/user-auth";

export async function GET(_request:Request,context:{params:Promise<{id:string}>}){if(!isSupabaseConfigured())return NextResponse.json({items:[],aggregate:[],viewer:{loggedIn:false}});const id=(await context.params).id;const client=createServiceClient();const {data:place}=await client.from("places").select("id").eq("id",id).eq("status","approved").eq("is_demo",false).eq("verification_status","verified").maybeSingle();if(!place)return NextResponse.json({message:"Místo nebylo nalezeno."},{status:404});const account=await getCurrentAccount();const result=await publicPlaceComments(id,account?.id);return NextResponse.json({...result,viewer:{loggedIn:Boolean(account),profileComplete:Boolean(account?.complete)}},{headers:{"Cache-Control":"private, no-store"}});}

export async function POST(request:Request,context:{params:Promise<{id:string}>}){const account=await getCurrentAccount();if(!account)return NextResponse.json({message:"Pro přidání zkušenosti se přihlaste."},{status:401});if(account.accountStatus!=="active")return NextResponse.json({message:"Váš účet má publikování pozastavené."},{status:403});if(!account.complete)return NextResponse.json({message:"Nejdřív dokončete profil a přijměte pravidla komunity.",profileRequired:true},{status:428});if(!allowRequest(`place-comment-ip:${requestFingerprint(request)}`,25,24*60*60*1000)||!allowRequest(`place-comment-user:${account.id}`,12,24*60*60*1000))return NextResponse.json({message:"Denní limit zkušeností byl vyčerpán."},{status:429});const parsed=placeCommentSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Zkontrolujte zkušenost.",issues:parsed.error.flatten().fieldErrors},{status:422});const body=cleanPlaceText(parsed.data.body,true);const invalid=invalidPlaceCommentReason(body);if(invalid)return NextResponse.json({message:invalid},{status:422});const placeId=(await context.params).id;const client=createServiceClient();const {data:place}=await client.from("places").select("id").eq("id",placeId).eq("status","approved").eq("is_demo",false).eq("verification_status","verified").maybeSingle();if(!place)return NextResponse.json({message:"Místo nebylo nalezeno."},{status:404});const {data:existing}=await client.from("place_comments").select("id").eq("place_id",placeId).eq("author_id",account.id).eq("body",body).in("status",["active","hidden"]).maybeSingle();if(existing)return NextResponse.json({message:"Stejnou zkušenost už jste přidali."},{status:409});const id=randomUUID();const {error}=await client.from("place_comments").insert({id,place_id:placeId,author_id:account.id,body,status:"active"});if(error)return NextResponse.json({message:"Zkušenost se nepodařilo uložit."},{status:422});if(parsed.data.traits.length){const traits=await client.from("place_comment_traits").insert(parsed.data.traits.map((trait)=>({comment_id:id,trait})));if(traits.error){await client.from("place_comments").delete().eq("id",id);return NextResponse.json({message:"Zkušenost se nepodařilo dokončit."},{status:422});}}const result=await publicPlaceComments(placeId,account.id);return NextResponse.json({item:result.items.find((item)=>item.id===id),aggregate:result.aggregate,message:"Zkušenost je zveřejněná."},{status:201});}
